/**
 * Run with:  npx ts-node -r dotenv/config src/scripts/seed-problems-extra.ts
 * Adds 33 more problems (total ≥ 53).
 */
import 'dotenv/config'
import mongoose from 'mongoose'
import { Problem } from '../models/problem.model'

const EXTRA_PROBLEMS = [
  // ─── EASY ─────────────────────────────────────────────────────────────────
  {
    slug: 'chess-game',
    title: 'Chess Game',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a two-player chess game with all piece types, legal move validation, check/checkmate detection, and turn management.',
    companies: ['Google', 'Microsoft', 'Amazon'],
    tags: ['OOP', 'Game Design', 'Board Game'],
    order: 8,
    functionalRequirements: [
      'Support all six piece types: King, Queen, Rook, Bishop, Knight, Pawn',
      'Validate legal moves for each piece type',
      'Detect check and prevent moves that leave the King in check',
      'Detect checkmate and stalemate to end the game',
      'Support special moves: castling, en passant, pawn promotion',
      'Track move history and allow display of past moves',
      'Two-player turn-based gameplay',
    ],
    nonFunctionalRequirements: [
      'Move validation completes in O(1) or O(board_size)',
      'Board state serializable for save/resume',
      'Checkmate detection runs in O(n) where n = legal moves',
    ],
    hints: [
      'Core entities: Game, Board, Cell, Piece (with subclasses: King, Queen, Rook, Bishop, Knight, Pawn), Player, Move. Board is an 8×8 grid of Cells; each Cell holds a Piece or is empty.',
      'Use polymorphism for move generation: each Piece subclass implements getValidMoves(board) returning a list of target cells. Filter out moves that leave your own King in check by simulating each move.',
      'For check detection: after every move, scan all opponent pieces and see if any can reach the current player\'s King cell. For checkmate: if the current player is in check AND has zero legal moves, it\'s checkmate.',
    ],
  },
  {
    slug: 'deck-of-cards',
    title: 'Deck of Cards / Blackjack',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a generic deck of cards library and use it to implement a Blackjack game with dealer logic.',
    companies: ['Amazon', 'Airbnb', 'Microsoft'],
    tags: ['OOP', 'Game Design'],
    order: 9,
    functionalRequirements: [
      'Represent a standard 52-card deck with suits and ranks',
      'Shuffle the deck using a fair algorithm',
      'Deal cards to players and the dealer',
      'Calculate hand value with Ace counting as 1 or 11',
      'Implement Blackjack rules: hit, stand, bust (> 21), dealer hits until ≥ 17',
      'Support multiple simultaneous players at the table',
      'Determine winner: closest to 21 without busting',
    ],
    nonFunctionalRequirements: [
      'Deck shuffling must be truly random (Fisher-Yates)',
      'Hand value calculation runs in O(n) where n = cards in hand',
      'Support up to 8 players at the table',
    ],
    hints: [
      'Core entities: Card, Suit (enum), Rank (enum), Deck, Hand, Player, Dealer (extends Player), BlackjackGame. Card has a suit and rank; its numeric value depends on game rules (Ace = 1 or 11 in Blackjack).',
      'Use the Strategy pattern for card value calculation — BlackjackValueStrategy returns the best value ≤ 21 by starting with all Aces as 11 then reducing each to 1 while the hand busts.',
      'Model game flow as a State Machine: PlacingBets → DealingCards → PlayerTurns → DealerTurn → Payout. Each state handles specific inputs; illegal actions in the wrong state throw an exception.',
    ],
  },
  {
    slug: 'traffic-light-system',
    title: 'Traffic Light System',
    difficulty: 'easy',
    category: 'Infrastructure',
    description: 'Design a traffic light controller for a multi-road intersection, managing signal cycles and supporting emergency overrides.',
    companies: ['Walmart', 'Cisco', 'Bosch'],
    tags: ['State Machine', 'OOP'],
    order: 10,
    functionalRequirements: [
      'Manage Red, Yellow, Green signal cycles for each road at an intersection',
      'Ensure mutually exclusive green signals (no two conflicting roads are green simultaneously)',
      'Support configurable cycle durations per road and per signal',
      'Emergency vehicle override: hold all roads red except the emergency path',
      'Pedestrian crossing requests extending the current red phase',
      'Timer-based automatic transitions with configurable delays',
    ],
    nonFunctionalRequirements: [
      'Signal transitions are atomic — no ambiguous intermediate states',
      'Override response time under 500ms',
      'System handles up to 8-road intersections',
    ],
    hints: [
      'Core entities: TrafficLight, Signal (enum: RED, YELLOW, GREEN), Road, Intersection, TrafficController, Timer. Each TrafficLight is a State Machine cycling: GREEN → YELLOW → RED → GREEN.',
      'The TrafficController coordinates all lights: only one road gets GREEN at a time (plus its paired non-conflicting direction). Use a round-robin scheduler with configurable durations per road.',
      'For the emergency override, add a HIGH_PRIORITY event that the Controller handles by immediately transitioning all active lights to RED and then granting GREEN to the emergency road. Store the previous state to restore after the override.',
    ],
  },
  {
    slug: 'logging-framework',
    title: 'Logging Framework',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design a logging framework like Log4j or SLF4J — supporting multiple log levels, configurable sinks, and formatted output.',
    companies: ['Microsoft', 'Adobe', 'Salesforce'],
    tags: ['OOP', 'Design Patterns'],
    order: 11,
    functionalRequirements: [
      'Log at levels: DEBUG, INFO, WARN, ERROR, FATAL',
      'Filter messages below the configured minimum level',
      'Support multiple sinks: console, file, remote server',
      'Format log messages: timestamp, level, logger name, message',
      'Named loggers per module/class for fine-grained control',
      'Async logging to avoid blocking the main thread',
      'Log file rotation by size or date',
    ],
    nonFunctionalRequirements: [
      'Logging overhead < 1ms for filtered-out messages',
      'Thread-safe for concurrent writes',
      'File sink flushes periodically, not on every write',
    ],
    hints: [
      'Core entities: Logger, LogLevel, LogRecord, Appender (Console/File/Remote), Formatter, LogManager. Logger is the user-facing API; it creates LogRecords and passes them to registered Appenders.',
      'Use the Chain of Responsibility pattern for level filtering: each Logger checks if the log level is sufficient before passing to Appenders. Appenders also have their own minimum level filter.',
      'Use the Singleton pattern for LogManager (one central config). Use the Builder pattern for Logger configuration. For async logging, put LogRecords on a BlockingQueue and consume with a background thread.',
    ],
  },
  {
    slug: 'rate-limiter',
    title: 'Rate Limiter',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design a rate limiter that restricts the number of requests a client can make within a time window.',
    companies: ['Stripe', 'Cloudflare', 'AWS', 'Uber'],
    tags: ['OOP', 'Algorithm', 'Sliding Window'],
    order: 12,
    functionalRequirements: [
      'Limit requests per user/IP to N per time window (e.g., 100 per minute)',
      'Return 429 Too Many Requests when limit is exceeded',
      'Support multiple algorithms: fixed window, sliding window, token bucket, leaky bucket',
      'Different rate limits per API endpoint or user tier',
      'Include rate limit headers in responses (X-RateLimit-Limit, X-RateLimit-Remaining)',
      'Admin can update rate limit rules at runtime',
    ],
    nonFunctionalRequirements: [
      'Rate limit check must complete in < 5ms',
      'Support 100,000 unique clients concurrently',
      'Thread-safe — concurrent requests from same client handled correctly',
    ],
    hints: [
      'Core entities: RateLimiter (interface), FixedWindowLimiter, SlidingWindowLimiter, TokenBucketLimiter, LeakyBucketLimiter, RateLimitRule, ClientBucket. Use the Strategy pattern — RateLimiter interface with allow(clientId) → boolean.',
      'Token Bucket: each client has a bucket of tokens that refills at rate R tokens/second up to capacity C. Each request consumes 1 token. If bucket is empty, reject. Store (tokens, lastRefillTime) per client.',
      'Sliding Window Log: store request timestamps in a queue per client. On each request, remove timestamps older than the window, count remaining. If count < limit, add new timestamp and allow; else reject. Uses O(n) memory per client but is most accurate.',
    ],
  },
  {
    slug: 'pub-sub-system',
    title: 'Pub-Sub Messaging System',
    difficulty: 'easy',
    category: 'Messaging',
    description: 'Design an in-memory publish-subscribe system where publishers send messages to topics and multiple subscribers receive them.',
    companies: ['Google', 'Amazon', 'Confluent'],
    tags: ['OOP', 'Design Patterns', 'Messaging'],
    order: 13,
    functionalRequirements: [
      'Publishers send messages to named topics',
      'Subscribers register interest in one or more topics',
      'All active subscribers of a topic receive every message',
      'Support subscribing and unsubscribing at any time',
      'Message delivery in the order they were published',
      'Support wildcard topic subscriptions (e.g., "orders.*")',
    ],
    nonFunctionalRequirements: [
      'Message delivery latency < 10ms for in-memory',
      'Support 10,000 topics and 1,000 subscribers per topic',
      'Thread-safe publish and subscribe operations',
    ],
    hints: [
      'Core entities: Topic, Message, Publisher, Subscriber (interface), EventBus/MessageBroker. The broker maintains a Map<topicName, List<Subscriber>> and calls each subscriber\'s onMessage() when a topic receives a message.',
      'Use the Observer pattern — Topic is the subject, Subscribers are observers. The broker acts as the mediator decoupling publishers from subscribers.',
      'For async delivery, dispatch messages on a thread pool rather than calling subscribers synchronously inside publish(). This prevents a slow subscriber from blocking all publishers.',
    ],
  },

  // ─── MEDIUM ───────────────────────────────────────────────────────────────
  {
    slug: 'online-stock-brokerage',
    title: 'Online Stock Brokerage',
    difficulty: 'medium',
    category: 'Fintech',
    description: 'Design an online stock trading system where users place buy/sell orders that are matched through an order book.',
    companies: ['Zerodha', 'Robinhood', 'Goldman Sachs', 'Morgan Stanley'],
    tags: ['Order Book', 'Matching Engine', 'Finance'],
    order: 8,
    functionalRequirements: [
      'Users place market orders and limit orders to buy or sell stocks',
      'Order book matches buy and sell orders by price-time priority',
      'Real-time price updates as orders are matched',
      'Cancel an unmatched pending order',
      'Portfolio view: current holdings and P&L',
      'Order history and trade confirmations',
      'Support stop-loss and take-profit orders',
    ],
    nonFunctionalRequirements: [
      'Order matching completes in < 1ms',
      'Handle 100,000 orders per second',
      'Order book operations O(log n) using sorted data structures',
      'All matched trades stored durably with exactly-once semantics',
    ],
    hints: [
      'Core entities: Order, OrderType (Market/Limit/StopLoss), Side (Buy/Sell), OrderBook, Trade, Portfolio, Stock, MatchingEngine. Each stock has its own OrderBook with two sorted lists: asks (ascending price) and bids (descending price).',
      'For matching: when a buy limit order arrives, compare with the lowest ask. If ask_price ≤ buy_price, match them (create a Trade), reduce quantities, and remove filled orders. Use a PriorityQueue (min-heap for asks, max-heap for bids).',
      'For market orders: match immediately at the best available price regardless of limit. For partial fills: when a new order quantity > available at best price, fill what\'s available, then continue down the order book until fully filled or book is exhausted.',
    ],
  },
  {
    slug: 'car-rental',
    title: 'Car Rental System',
    difficulty: 'medium',
    category: 'Transportation',
    description: 'Design a car rental platform like Hertz or Avis — users search available cars, book them, and manage reservations.',
    companies: ['Hertz', 'Ola', 'Uber', 'Zoomcar'],
    tags: ['OOP', 'Scheduling', 'Reservations'],
    order: 9,
    functionalRequirements: [
      'Browse available cars by type, location, and date range',
      'Reserve a car for a date range with pickup/drop location',
      'Multiple car categories: economy, sedan, SUV, luxury, electric',
      'Dynamic pricing by category, duration, and season',
      'Extend, modify, or cancel reservations',
      'Track vehicle location and mileage',
      'Late return fees and damage report on return',
    ],
    nonFunctionalRequirements: [
      'Prevent double-booking of the same vehicle',
      'Search returns available cars within 200ms',
      'Support 1,000 locations and 100,000 vehicles',
    ],
    hints: [
      'Core entities: Vehicle, VehicleCategory, Location, Reservation, Payment, Customer, RentalBranch. Vehicle tracks its status (Available, Reserved, Rented, Maintenance) and has a ReservationCalendar of blocked date ranges.',
      'For availability search, query vehicles at the requested location whose status is Available and have no Reservation overlapping [startDate, endDate). Use an interval tree or indexed date-range query for efficiency.',
      'Use the Strategy pattern for pricing: BaseDailyRate × CategoryMultiplier × SeasonalMultiplier × DurationDiscount. The Factory pattern for creating different VehicleCategory pricing strategies.',
    ],
  },
  {
    slug: 'flight-reservation',
    title: 'Flight Reservation System',
    difficulty: 'medium',
    category: 'Travel',
    description: 'Design a flight reservation system like MakeMyTrip — users search flights, book seats, and manage itineraries.',
    companies: ['MakeMyTrip', 'Amadeus', 'Sabre', 'Expedia'],
    tags: ['OOP', 'Concurrency', 'Seat Reservation'],
    order: 10,
    functionalRequirements: [
      'Search flights by origin, destination, date, and passenger count',
      'View flight details: airline, duration, stops, price',
      'Select specific seats from a seat map',
      'Book single or round-trip flights with passenger details',
      'Generate e-ticket with PNR code',
      'Cancel booking with refund based on policy',
      'Support multiple fare classes: economy, business, first',
    ],
    nonFunctionalRequirements: [
      'Seat booking is atomic — prevent double-booking',
      'Search across 10,000 flights returns in < 500ms',
      'PNR generation is globally unique',
    ],
    hints: [
      'Core entities: Airport, Flight, Aircraft, Seat, FlightInstance (a specific date\'s occurrence), Booking, Passenger, Ticket, FareClass. FlightInstance has a SeatMap — each Seat has a status (Available, Locked, Booked) and a FareClass.',
      'For booking, use a two-phase lock: phase 1 = temporarily lock selected seats (TTL 10 min) while payment is processed; phase 2 = confirm booking on successful payment. Use optimistic locking on the Seat status field.',
      'PNR = 6-character alphanumeric code (A-Z, 0-9). Generate using a combination of random bytes + checksum. Store in a hash map for O(1) lookup. Use the Facade pattern for the booking flow: SearchFacade, ReservationFacade, PaymentFacade.',
    ],
  },
  {
    slug: 'stack-overflow',
    title: 'Stack Overflow / Q&A Platform',
    difficulty: 'medium',
    category: 'Developer Tools',
    description: 'Design a developer Q&A platform like Stack Overflow with questions, answers, votes, tags, reputation, and search.',
    companies: ['Microsoft', 'Google', 'Atlassian'],
    tags: ['OOP', 'Search', 'Reputation System'],
    order: 11,
    functionalRequirements: [
      'Users post questions with a title, body, and tags',
      'Other users post answers to questions',
      'Upvote and downvote questions and answers',
      'Accept the best answer (only by question owner)',
      'Reputation system: gains/loses points based on votes',
      'Tag-based browsing and search by title/body',
      'Comments on questions and answers',
      'Badges awarded for reputation milestones and achievements',
    ],
    nonFunctionalRequirements: [
      'Search returns results in < 200ms',
      'Reputation updates are eventually consistent',
      'Support 10 million questions and 50 million answers',
    ],
    hints: [
      'Core entities: User, Question, Answer, Comment, Tag, Vote, Reputation, Badge. Question and Answer both extend a Post abstract class with common fields: body, createdAt, author, voteCount, comments.',
      'For voting, use a Vote entity linking (voter, post, value: +1/-1) with a unique constraint to prevent double-voting. Reputation change: question upvote = +10, answer upvote = +10, downvote = -2, accepted answer = +15.',
      'For search, build a full-text inverted index: Map<word, List<postId>>. Tag filtering uses a TagIndex: Map<tag, List<questionId>>. Combine results with AND/OR logic and rank by (voteCount × 0.6 + recency × 0.4).',
    ],
  },
  {
    slug: 'linkedin',
    title: 'LinkedIn / Professional Network',
    difficulty: 'medium',
    category: 'Social Media',
    description: 'Design a professional networking platform like LinkedIn — profiles, connections, feed, job postings, and messaging.',
    companies: ['LinkedIn', 'Microsoft', 'Glassdoor'],
    tags: ['Graph', 'Feed Generation', 'OOP'],
    order: 12,
    functionalRequirements: [
      'User profiles with experience, education, skills, and endorsements',
      'Send and accept connection requests (1st/2nd/3rd degree)',
      'News feed showing posts and activity from connections',
      'Job postings: companies post jobs, users apply',
      'Skill endorsements and recommendations',
      'Direct messaging between connected users',
      'People You May Know suggestions',
    ],
    nonFunctionalRequirements: [
      'Connection graph traversal for 2nd-degree connections in < 500ms',
      'Feed loads in < 300ms for users with up to 5,000 connections',
      'People You May Know computed offline and cached',
    ],
    hints: [
      'Core entities: User, Profile, Connection, Post, Job, Application, Endorsement, Recommendation, Message. The connection graph is an undirected graph — store edges as (userId1, userId2, status: Pending/Connected).',
      'For People You May Know: compute mutual connection count for 2nd-degree connections (BFS depth 2 from user). Rank by mutual_count. Run offline nightly and cache per user. Use a graph DB or adjacency list representation.',
      'Feed uses fan-out on write for users with < 5,000 connections: push post to all connections\' feed caches on create. For power users (> 5,000), fan-out on read: merge their posts at query time with the pre-built feed.',
    ],
  },
  {
    slug: 'spotify',
    title: 'Music Streaming (Spotify)',
    difficulty: 'medium',
    category: 'Streaming',
    description: 'Design a music streaming service like Spotify — song catalog, playlists, playback queues, recommendations, and offline mode.',
    companies: ['Spotify', 'Apple', 'JioSaavn'],
    tags: ['OOP', 'Streaming', 'Recommendation'],
    order: 13,
    functionalRequirements: [
      'Browse and search songs, albums, artists, and podcasts',
      'Create, edit, and share playlists',
      'Play songs with skip, repeat, shuffle controls',
      'Like songs and follow artists and playlists',
      'Personalized daily mixes and discover weekly',
      'Download songs for offline playback (premium)',
      'Real-time lyrics display',
      'Collaborative playlists (multiple editors)',
    ],
    nonFunctionalRequirements: [
      'Song start latency < 500ms globally via CDN',
      'Support 400 million users, 80 million songs',
      'Offline playback works without network',
      'Recommendation model updated daily',
    ],
    hints: [
      'Core entities: User, Song, Album, Artist, Playlist, PlaybackQueue, Like, Download, ListeningHistory. Song metadata (title, duration, artist) stored in a relational DB; audio files stored in object storage distributed via CDN.',
      'Playback queue is a user-session data structure: ordered list of song IDs with a currentIndex. Shuffle uses Fisher-Yates on the remaining unplayed songs. Repeat toggles a flag that resets currentIndex on completion.',
      'Recommendations use collaborative filtering: cluster users by listening history embeddings. Find the user\'s cluster, aggregate top songs not yet heard. Also use content-based filtering: recommend songs with similar audio features (tempo, key, energy) via cosine similarity.',
    ],
  },
  {
    slug: 'online-code-judge',
    title: 'Online Code Judge (LeetCode)',
    difficulty: 'medium',
    category: 'Developer Tools',
    description: 'Design an online code execution and judging platform like LeetCode — users submit code, it runs in a sandbox, and results are evaluated.',
    companies: ['Google', 'Meta', 'Codeforces'],
    tags: ['Sandboxing', 'OOP', 'Queue'],
    order: 14,
    functionalRequirements: [
      'Problems with description, input/output format, examples, and constraints',
      'Submit code in multiple languages (Python, Java, C++, JavaScript)',
      'Run code against hidden test cases in an isolated sandbox',
      'Judge verdicts: Accepted, Wrong Answer, Time Limit Exceeded, Memory Limit Exceeded, Runtime Error',
      'Show execution time and memory usage for each submission',
      'Global and per-problem leaderboard',
      'Discussion forum per problem',
    ],
    nonFunctionalRequirements: [
      'Code execution isolated — cannot affect other submissions or the host',
      'Execution timeout enforced within 10ms of the configured limit',
      'Support 10,000 concurrent submissions',
      'Results returned within 5 seconds for most problems',
    ],
    hints: [
      'Core entities: Problem, TestCase, Submission, Judge, ExecutionResult, Leaderboard, User. Submission is placed on a queue. A pool of Judge workers picks submissions, runs them in isolated containers (Docker/WASM), and writes results back.',
      'For sandboxing, spawn a Docker container (or use seccomp-filtered processes) with resource limits: CPU time, memory cap, no network, no filesystem writes outside /tmp. Kill the container after the time limit.',
      'Judge workflow: 1) Compile code (if compiled language); 2) Run against each test case; 3) Compare output with expected (exact or trimmed match); 4) Record verdict for each test; 5) Overall verdict = worst case. Store results in the Submission record.',
    ],
  },
  {
    slug: 'notification-service',
    title: 'Notification Service',
    difficulty: 'medium',
    category: 'Messaging',
    description: 'Design a multi-channel notification service that sends alerts via push, email, SMS, and in-app with user preference control.',
    companies: ['Twilio', 'AWS', 'SendGrid', 'Airbnb'],
    tags: ['OOP', 'Message Queue', 'Channels'],
    order: 15,
    functionalRequirements: [
      'Send notifications through multiple channels: push, email, SMS, in-app',
      'Users configure channel preferences per notification type',
      'Notification types: transactional, promotional, alert',
      'Template-based messages with dynamic variable substitution',
      'Delivery tracking: sent, delivered, read, failed',
      'Retry failed notifications with exponential backoff',
      'Scheduled notifications (send at a future time)',
      'Rate limiting to prevent spamming users',
    ],
    nonFunctionalRequirements: [
      'Transactional notifications delivered within 5 seconds',
      'Support 1 million notifications per hour',
      'At-least-once delivery with deduplication',
    ],
    hints: [
      'Core entities: Notification, NotificationType, Channel (Email/SMS/Push/InApp), Template, UserPreference, DeliveryRecord. Use the Strategy pattern for channels — each Channel implements send(notification) with its own third-party SDK.',
      'Use a Message Queue (Kafka or SQS) as the backbone: when a notification event fires, publish to the queue. Channel-specific consumers pick up messages and deliver via their respective APIs (SendGrid, Twilio, FCM).',
      'Template engine: store templates with placeholders like {{user_name}}, {{order_id}}. On notification creation, merge the template with the event payload. Use the Factory pattern to select the right template per (notificationType, channel) combination.',
    ],
  },
  {
    slug: 'coupon-system',
    title: 'Coupon & Discount System',
    difficulty: 'medium',
    category: 'E-commerce',
    description: 'Design a flexible coupon and discount management system for an e-commerce platform supporting various promotion types.',
    companies: ['Amazon', 'Flipkart', 'Shopify', 'Swiggy'],
    tags: ['OOP', 'Design Patterns', 'E-commerce'],
    order: 16,
    functionalRequirements: [
      'Create coupon codes with type: percentage off, flat amount off, free shipping, buy-X-get-Y',
      'Set validity period, minimum order value, and usage limits (total and per-user)',
      'Apply single or multiple coupons to a cart',
      'Auto-apply the best available coupon based on cart contents',
      'Coupon stacking rules: which types can be combined',
      'Admin dashboard to create, disable, and view coupon analytics',
      'Track coupon redemptions per user',
    ],
    nonFunctionalRequirements: [
      'Coupon validation under 50ms',
      'Prevent concurrent over-redemption using atomic decrement',
      'Support 100,000 active coupon codes',
    ],
    hints: [
      'Core entities: Coupon, DiscountType, UsageLimit, CouponRedemption, Cart, CartItem. Use the Strategy pattern for discount calculation — each DiscountType implements calculate(cart) → discountAmount.',
      'For usage limits, store a redemption counter in Redis with an atomic DECR operation. Before applying: DECR coupon:{code}:remaining. If result < 0, INCR back and reject. This prevents race conditions under high load.',
      'For stacking rules, model a DiscountChain: list of applicable strategies ordered by priority. Use the Chain of Responsibility — each strategy can decide to stop the chain or pass to the next. A StackingRule object defines which coupon types are mutually exclusive.',
    ],
  },
  {
    slug: 'inventory-management',
    title: 'Inventory Management System',
    difficulty: 'medium',
    category: 'E-commerce',
    description: 'Design a warehouse inventory system that tracks products, stock levels, restocking, and multi-warehouse fulfillment.',
    companies: ['Amazon', 'Walmart', 'Shopify', 'SAP'],
    tags: ['OOP', 'CRUD', 'Concurrency'],
    order: 17,
    functionalRequirements: [
      'Track product stock levels across multiple warehouses',
      'Reserve inventory when an order is placed, release on cancel',
      'Restock items: receive purchase orders from suppliers',
      'Low-stock alerts when quantity drops below threshold',
      'Transfer stock between warehouses',
      'FIFO or LIFO inventory costing for accounting',
      'Barcode/SKU-based product identification',
      'Audit log of all stock movements',
    ],
    nonFunctionalRequirements: [
      'Stock reservation is atomic — prevent overselling',
      'Audit log is append-only and immutable',
      'Support 1 million SKUs across 500 warehouses',
    ],
    hints: [
      'Core entities: Product, SKU, Warehouse, InventoryItem (product × warehouse), StockReservation, PurchaseOrder, StockMovement, LowStockAlert. InventoryItem tracks quantityOnHand, quantityReserved, quantityAvailable = onHand − reserved.',
      'For atomic reservation, use a database transaction: UPDATE inventory SET reserved = reserved + qty WHERE product_id = ? AND (on_hand - reserved) >= qty. If 0 rows updated, stock is insufficient — roll back and reject.',
      'Model all stock changes as immutable StockMovement records (type: Receive, Reserve, Release, Ship, Transfer, Adjust). The current stock level is the sum of all movements, making auditing trivial and rollback possible.',
    ],
  },
  {
    slug: 'zoom',
    title: 'Video Conferencing (Zoom)',
    difficulty: 'medium',
    category: 'Messaging',
    description: 'Design a video conferencing system like Zoom supporting scheduled meetings, screen sharing, recording, and participant management.',
    companies: ['Zoom', 'Google', 'Microsoft', 'Cisco'],
    tags: ['Real-time', 'WebRTC', 'OOP'],
    order: 18,
    functionalRequirements: [
      'Schedule meetings with a unique join link and meeting ID',
      'Join meetings as host or participant (up to 100 participants)',
      'Audio and video toggles per participant',
      'Screen and application sharing',
      'In-meeting chat with the group or privately',
      'Recording meetings to cloud or local storage',
      'Waiting room: host admits participants manually',
      'Raise hand and reaction emojis',
    ],
    nonFunctionalRequirements: [
      'Audio/video latency < 150ms end-to-end',
      'Support 1,000 concurrent meetings on the platform',
      'Recording stored durably with < 5 second delay',
    ],
    hints: [
      'Core entities: User, Meeting, MeetingParticipant, ChatMessage, Recording, WaitingRoom. Meeting has a unique ID and password. Participants join via a Signaling Server that exchanges SDP/ICE candidates for WebRTC peer-to-peer (or SFU-based) connection setup.',
      'For scalability with > 10 participants, use an SFU (Selective Forwarding Unit): each participant sends their stream to the SFU once; the SFU distributes it to all others, reducing each sender\'s upload burden from O(n) to O(1).',
      'Recording: capture streams at the server level (SFU can forward to a Recording Service). Recording Service muxes audio/video streams per participant into a single MP4 using a container like FFmpeg, then uploads to object storage.',
    ],
  },

  // ─── HARD ─────────────────────────────────────────────────────────────────
  {
    slug: 'youtube',
    title: 'YouTube',
    difficulty: 'hard',
    category: 'Streaming',
    description: 'Design YouTube — video upload, transcoding pipeline, search, recommendations, comments, monetization, and global CDN delivery.',
    companies: ['Google', 'Meta', 'TikTok'],
    tags: ['CDN', 'Transcoding', 'Search', 'Recommendation'],
    order: 7,
    functionalRequirements: [
      'Upload videos of any length (up to 12 hours)',
      'Transcode to multiple resolutions: 360p to 4K',
      'Adaptive bitrate streaming (HLS/DASH)',
      'Subscribe to channels, like, comment, share',
      'Search videos by title, description, and tags',
      'Personalised homepage and recommended videos',
      'Creator analytics: views, watch time, revenue',
      'Live streaming',
    ],
    nonFunctionalRequirements: [
      '500 hours of video uploaded per minute',
      'Video start time < 2 seconds globally',
      '2 billion logged-in users per month',
      'Transcoding pipeline completes 1-hour video in < 5 minutes',
    ],
    hints: [
      'Core entities: User, Channel, Video, VideoAsset (per resolution), Comment, Like, Subscription, WatchHistory. Upload pipeline: Raw upload to object storage → Message queue triggers Transcoding Workers → Segments stored in CDN-backed object storage → Metadata written to DB.',
      'Transcoding: split video into 2-second GOP-aligned segments. Transcode each segment at multiple bitrates in parallel (worker pool). Generate HLS manifests (.m3u8) listing all segments. CDN caches segments at edge nodes near viewers.',
      'Search uses an inverted index over video titles, descriptions, and auto-generated transcripts. Rank by: relevance score × log(views) × recency_decay. Recommendations use a two-tower neural network: user embedding × video embedding → affinity score, served via ANN index.',
    ],
  },
  {
    slug: 'url-shortener',
    title: 'URL Shortener (bit.ly)',
    difficulty: 'hard',
    category: 'Developer Tools',
    description: 'Design a URL shortening service at massive scale — generating unique short codes, redirecting users, and providing analytics.',
    companies: ['Bitly', 'TinyURL', 'Twitter'],
    tags: ['Distributed', 'Hashing', 'Analytics'],
    order: 8,
    functionalRequirements: [
      'Shorten a long URL to a 7-character unique code',
      'Redirect short URL to the original URL with < 10ms latency',
      'Custom aliases (e.g., bit.ly/my-brand)',
      'Optional expiration date on short URLs',
      'Click analytics: total clicks, unique visitors, country, device',
      'Bulk URL shortening via API',
      'Delete or deactivate a short URL',
    ],
    nonFunctionalRequirements: [
      '100 million URLs created per day',
      '10 billion redirects per day',
      'Redirect latency < 10ms (P99)',
      'Short codes globally unique with no collisions',
    ],
    hints: [
      'Core entities: ShortURL, OriginalURL, ClickEvent, Analytics. Short code generation: hash the long URL with MD5/SHA-256, base62-encode, take the first 7 chars. On collision, append a counter and retry. Alternatively, use a pre-generated sequence from a distributed ID generator (Snowflake).',
      'Redirect flow: browser hits short URL → load balancer → App Server → Redis cache lookup (shortCode → originalURL, O(1)) → if miss, DB lookup → cache the result → HTTP 301/302 redirect. Use 302 (not 301) to ensure analytics hit the server on every click.',
      'Analytics: asynchronously write ClickEvents to a Kafka topic. A stream processor aggregates counts by (shortCode, date, country, device) into a time-series store (e.g., ClickHouse). Never block the redirect path for analytics writes.',
    ],
  },
  {
    slug: 'distributed-cache',
    title: 'Distributed Cache (Redis-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a distributed in-memory cache system supporting key-value operations, TTL, eviction policies, and consistent hashing.',
    companies: ['Redis', 'Memcached', 'Amazon', 'Meta'],
    tags: ['Distributed Systems', 'Consistent Hashing', 'Eviction'],
    order: 9,
    functionalRequirements: [
      'GET, SET, DEL key-value operations',
      'TTL per key with lazy + active expiry',
      'LRU and LFU eviction when memory limit is reached',
      'Horizontal scaling by adding/removing cache nodes',
      'Data replication across replicas for high availability',
      'Pub-Sub for cache invalidation across nodes',
      'Atomic operations: INCR, SETNX (for distributed locks)',
    ],
    nonFunctionalRequirements: [
      'GET/SET latency < 1ms (P99)',
      'Consistent hashing for minimal key redistribution on node changes',
      'Support 1 TB total cached data across 20 nodes',
      '99.99% availability with replica failover',
    ],
    hints: [
      'Core entities: CacheNode, CacheEntry (key, value, TTL, lastAccessed, frequency), ConsistentHashRing, EvictionPolicy, ReplicationManager. Each node is an independent process with its own hash ring segment.',
      'Consistent hashing: place nodes on a virtual ring (0 to 2^32). Each key maps to the nearest node clockwise. Use virtual nodes (100–200 per physical node) for even load distribution. On node addition/removal, only the keys in the affected ring segment need migration.',
      'LRU eviction: maintain a doubly-linked list of CacheEntry nodes in access order + a hash map for O(1) lookup. On GET, move the accessed node to the head. On capacity exceeded, evict from the tail. Use a lock per hash bucket to reduce contention.',
    ],
  },
  {
    slug: 'payment-gateway',
    title: 'Payment Gateway (Stripe-like)',
    difficulty: 'hard',
    category: 'Fintech',
    description: 'Design a payment gateway supporting card processing, refunds, fraud detection, and PCI-compliant tokenization at scale.',
    companies: ['Stripe', 'PayPal', 'Razorpay', 'Visa'],
    tags: ['Finance', 'Security', 'Distributed Systems'],
    order: 10,
    functionalRequirements: [
      'Accept card payments (credit, debit, prepaid)',
      'Tokenize card data — merchants never see raw card numbers (PCI DSS)',
      'Authorize, capture, and refund payments',
      'Support 3D Secure (OTP) for strong customer authentication',
      'Webhook notifications for payment events',
      'Retry failed payments with intelligent retry logic',
      'Multi-currency support with FX conversion',
      'Fraud detection and risk scoring',
    ],
    nonFunctionalRequirements: [
      'Authorization response in < 300ms',
      'Exactly-once payment processing (idempotency keys)',
      'PCI DSS Level 1 compliance — card data never stored unencrypted',
      'Support 10,000 transactions per second',
    ],
    hints: [
      'Core entities: Payment, PaymentMethod, Token (replaces card number), Merchant, Refund, Webhook, FraudScore, IdempotencyKey. Flow: Merchant API call → Idempotency check → Tokenization → Authorization request to card network → Capture → Webhook delivery.',
      'Tokenization: store card data in a PCI-compliant Vault. Issue a random token (e.g., tok_abc123) to the merchant. All subsequent charges reference the token; the Vault resolves it to the real card number when communicating with the card network.',
      'Idempotency: each payment request includes an idempotency key. Store (key → response) in Redis with a TTL. If the same key is seen again within the TTL, return the cached response without re-processing. This prevents duplicate charges on network retries.',
    ],
  },
  {
    slug: 'search-autocomplete',
    title: 'Search Autocomplete System',
    difficulty: 'hard',
    category: 'Developer Tools',
    description: 'Design a real-time search autocomplete system like Google\'s suggest — returning top completions for a prefix as the user types.',
    companies: ['Google', 'Bing', 'Amazon', 'LinkedIn'],
    tags: ['Trie', 'Distributed Systems', 'Real-time'],
    order: 11,
    functionalRequirements: [
      'Return top-5 completions for any typed prefix in < 100ms',
      'Completions ranked by global search frequency',
      'Personalized suggestions based on user\'s search history',
      'Support 50+ languages and Unicode characters',
      'Filter adult/offensive completions',
      'Real-time updates — trending queries appear within minutes',
      'Log search selections to improve rankings',
    ],
    nonFunctionalRequirements: [
      'Handle 10,000 prefix queries per second',
      'Suggestions returned in < 100ms (P99)',
      'Trie fits in memory: compressed to handle millions of terms',
      'Ranking updated every 10 minutes from aggregated logs',
    ],
    hints: [
      'Core entities: TrieNode, SearchTerm, QueryLog, TopKCache, PersonalizationService. The Trie stores all indexed terms; each TrieNode caches the top-5 completions in its subtree (pre-computed). A prefix lookup = O(prefix_length) and then return cached top-5.',
      'For scale, shard the Trie by first letter (or first two letters for hot prefixes). Each shard runs on its own server. The frontend routes the query to the correct shard. All shards return candidates; the aggregator merges and returns top-5.',
      'Ranking pipeline: every 10 minutes, a MapReduce job processes QueryLogs to compute (term → frequency) counts. Merge with existing counts using exponential decay (recent queries weighted more). Update the top-5 cache for each TrieNode bottom-up.',
    ],
  },
  {
    slug: 'real-time-leaderboard',
    title: 'Real-Time Gaming Leaderboard',
    difficulty: 'hard',
    category: 'Gaming',
    description: 'Design a globally consistent real-time leaderboard for a game supporting millions of players with rank queries and score updates.',
    companies: ['Epic Games', 'Riot', 'Roblox', 'King'],
    tags: ['Distributed Systems', 'Redis', 'Real-time'],
    order: 12,
    functionalRequirements: [
      'Update a player\'s score in real time',
      'Query global rank for any player in < 50ms',
      'Top-100 leaderboard updated in near real-time',
      'Paginated leaderboard: any page of 20 players by rank',
      'Time-windowed leaderboards: daily, weekly, all-time',
      'Friend leaderboard: rank among only the player\'s friends',
      'Regional leaderboards by country',
    ],
    nonFunctionalRequirements: [
      'Handle 100,000 score updates per second',
      'Global rank query in < 50ms for 100 million players',
      'Leaderboard reads are highly available (eventual consistency OK)',
    ],
    hints: [
      'Core entities: Player, Score, Leaderboard (global/daily/friend), Rank. Use Redis Sorted Sets (ZADD, ZRANK, ZRANGE) as the primary data structure — score updates are O(log n), rank queries are O(log n), range queries are O(log n + k).',
      'For 100 million players, a single Redis sorted set can hold all of them (Redis handles 2^32 members per sorted set). Score updates: ZADD leaderboard <score> <playerId>. Rank query: ZREVRANK leaderboard <playerId> (0-indexed, add 1 for display).',
      'For time-windowed leaderboards, create separate sorted sets per window (leaderboard:daily:2024-01-15, leaderboard:weekly:2024-W03). Use EXPIRE to auto-clean old windows. Friend leaderboard: ZRANGEBYSCORE with a filter — fetch the player\'s friends list, then pipeline ZSCORE for each friend and sort client-side.',
    ],
  },
  {
    slug: 'distributed-message-queue',
    title: 'Distributed Message Queue (Kafka-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a distributed, durable message queue like Apache Kafka supporting topics, partitions, consumer groups, and replay.',
    companies: ['Confluent', 'LinkedIn', 'Uber', 'Airbnb'],
    tags: ['Distributed Systems', 'Messaging', 'Storage'],
    order: 13,
    functionalRequirements: [
      'Producers publish messages to named topics',
      'Topics partitioned for parallel consumption',
      'Consumer groups — each message delivered to exactly one consumer per group',
      'Message retention for a configurable period (replay)',
      'At-least-once and exactly-once delivery semantics',
      'Message ordering guaranteed within a partition',
      'Horizontal scaling: add brokers to increase throughput',
    ],
    nonFunctionalRequirements: [
      'Write throughput: 1 million messages per second per broker',
      'Message durability: replicated to N brokers before ACK',
      'Consumer lag monitoring per group',
      'Zero-copy I/O for high-throughput reads',
    ],
    hints: [
      'Core entities: Topic, Partition, Broker, Producer, Consumer, ConsumerGroup, Offset, Message. Each partition is an append-only log file on disk. Producers write to a partition (by key hash or round-robin). Consumers track their position via an Offset stored in a dedicated __consumer_offsets topic.',
      'Replication: each partition has a leader broker and N-1 follower replicas. Producers write to the leader; followers pull and replicate. A message is "committed" only after all ISR (in-sync replicas) acknowledge. Leader election uses a ZooKeeper/Raft consensus on broker failure.',
      'Zero-copy reads: use sendfile() system call to transfer data from the page cache directly to the network socket, bypassing user space. Combined with sequential disk I/O (append-only log), this achieves near-disk-speed throughput with very low CPU usage.',
    ],
  },
  {
    slug: 'api-gateway',
    title: 'API Gateway',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design an API Gateway that handles routing, authentication, rate limiting, load balancing, and observability for microservices.',
    companies: ['AWS', 'Kong', 'Nginx', 'Cloudflare'],
    tags: ['Distributed Systems', 'Proxy', 'Security'],
    order: 14,
    functionalRequirements: [
      'Route incoming requests to the correct microservice based on path/method',
      'Authenticate requests via API keys, JWT, or OAuth 2.0',
      'Rate limiting per client and per endpoint',
      'Load balance across multiple instances of each service',
      'Request/response transformation (header injection, body rewrite)',
      'Circuit breaker to stop routing to unhealthy services',
      'Centralized logging and distributed tracing (request correlation ID)',
    ],
    nonFunctionalRequirements: [
      'Add < 5ms latency to each proxied request',
      'Handle 100,000 requests per second',
      '99.99% availability — gateway itself must not be a single point of failure',
      'Configuration changes apply without downtime',
    ],
    hints: [
      'Core entities: Route, ServiceRegistry, AuthPlugin, RateLimitPlugin, LoadBalancer, CircuitBreaker, RequestContext. The gateway processes each request through a Plugin Chain: Auth → RateLimit → Route → Transform → Forward → Log.',
      'Use the Chain of Responsibility pattern for plugins. Each plugin implements handle(request, next) — it can reject the request or call next(). New plugins can be added without changing existing code. Store plugin config in a dynamic config store (etcd/Consul) to apply changes without restarts.',
      'Circuit Breaker states: Closed (normal) → Open (errors > threshold, stop routing) → Half-Open (allow one probe request) → Closed/Open based on result. Track error rates per service with a sliding window counter. Use Exponential backoff before retrying a tripped circuit.',
    ],
  },
  {
    slug: 'ride-sharing-backend',
    title: 'Ride Sharing — Backend Deep Dive',
    difficulty: 'hard',
    category: 'Transportation',
    description: 'Deep-dive backend design for a ride-sharing platform: geospatial indexing, dynamic dispatch, real-time tracking, and the pricing engine.',
    companies: ['Uber', 'Lyft', 'Rapido', 'Bolt'],
    tags: ['Geospatial', 'Real-time', 'Microservices'],
    order: 15,
    functionalRequirements: [
      'Index driver locations updated every 5 seconds',
      'Find available drivers within a configurable radius of a rider',
      'Dispatch optimization: minimize total wait time across all riders',
      'Dynamic surge pricing computed per geohash cell per minute',
      'ETA prediction using historical travel time data and current traffic',
      'Trip state machine with event-driven transitions',
      'Driver earnings calculation with incentive bonuses',
    ],
    nonFunctionalRequirements: [
      'Driver location index updated in < 50ms after each GPS ping',
      'Nearest driver search in < 100ms for 1 million active drivers',
      'Surge pricing recalculated every 60 seconds',
      'ETA accuracy within ±2 minutes for 90% of trips',
    ],
    hints: [
      'Location Service: store driver locations in Redis using Geohash or H3 hex cells (resolution 9 ≈ 0.1 km²). Use Redis GEO commands: GEOADD, GEORADIUSBYMEMBER for radius searches in O(N+log M). Update on every GPS ping via a write-through pipeline.',
      'Dispatch: when a trip request arrives, query the H3 cell and neighboring cells (k-ring 1 or 2) for available drivers. Score each driver: score = distance_penalty + direction_penalty + acceptance_rate_bonus. Send the trip offer to the top-scored driver; if no response in 8 seconds, try the next.',
      'Surge pricing: maintain a time-series of (requests, available_drivers) per H3 cell sampled every minute. surge = f(demand_rate / supply_rate). Use exponential smoothing to dampen noise. Store the surge multiplier map in Redis for O(1) per-cell lookups at pricing time.',
    ],
  },
  {
    slug: 'web-crawler',
    title: 'Web Crawler',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a scalable web crawler that discovers, fetches, and indexes web pages across billions of URLs.',
    companies: ['Google', 'Bing', 'Common Crawl'],
    tags: ['Distributed Systems', 'Graph', 'Queue'],
    order: 16,
    functionalRequirements: [
      'Start from seed URLs and discover new URLs via link extraction',
      'Respect robots.txt and crawl-delay directives',
      'De-duplicate URLs — never crawl the same page twice',
      'Prioritize URLs by freshness, PageRank, and domain importance',
      'Store fetched page content for indexing',
      'Handle redirects, broken links, and timeouts gracefully',
      'Support incremental re-crawl to keep content fresh',
    ],
    nonFunctionalRequirements: [
      'Crawl 1 billion URLs per day across a distributed cluster',
      'URL deduplication with < 1% false positives (Bloom filter)',
      'Politeness: max 1 request per domain per second',
      'Fault-tolerant: worker failures do not lose URLs',
    ],
    hints: [
      'Core entities: URLFrontier (priority queue of URLs to crawl), Fetcher (HTTP client), Parser (HTML/link extractor), DuplicateDetector (Bloom filter + fingerprint store), Storage (object store for raw pages), Scheduler (politeness delay per domain).',
      'URL Frontier is a multi-level priority queue. Level 1: per-domain back queues (FIFO, one per domain for politeness). Level 2: front queues sorted by priority. Selector picks a front queue by priority, then picks the next URL from the corresponding domain back queue that respects the crawl delay.',
      'Deduplication: use a Bloom filter (billions of bits in memory) for fast "probably not crawled" check. For confirmed duplicates, use a MinHash fingerprint of the page content stored in a DB. If two pages have the same fingerprint, skip the duplicate.',
    ],
  },
  {
    slug: 'typeahead-search',
    title: 'Typeahead / Instant Search',
    difficulty: 'hard',
    category: 'Developer Tools',
    description: 'Design an instant search feature that returns results across multiple entity types (users, products, articles) as the user types.',
    companies: ['Elasticsearch', 'Algolia', 'Shopify', 'LinkedIn'],
    tags: ['Search', 'Distributed Systems', 'Indexing'],
    order: 17,
    functionalRequirements: [
      'Return mixed results (users, products, articles) for any query prefix',
      'Results ranked by relevance, popularity, and personalization',
      'Spell correction for common typos',
      'Faceted filtering: narrow results by category, price, date',
      'Highlighting of matched query terms in results',
      'Index updates appear in search within 5 seconds',
      'Support 50+ languages with language-aware tokenization',
    ],
    nonFunctionalRequirements: [
      'Query latency < 50ms (P99)',
      'Index size: 10 billion documents across 10 shards',
      'Index update throughput: 100,000 documents per second',
    ],
    hints: [
      'Core entities: Document, Index, Shard, InvertedIndex (term → postings list), Posting (docId, TF, positions), QueryParser, Scorer, Highlighter. Each shard holds a subset of documents and an inverted index for fast term lookups.',
      'Query processing: tokenize query → lookup term in inverted index → get candidate docIds → score each by TF-IDF × BM25 × PersonalizationBoost → merge and rank → return top-K. Use a two-phase retrieval: candidate generation (recall) then precise scoring (precision).',
      'Near-real-time indexing: new documents go to an in-memory buffer (commit log). A background thread flushes the buffer to a new segment file every second. Periodic merges combine small segments into larger ones (like LSM-tree). Searches query both segments and the in-memory buffer simultaneously.',
    ],
  },
  {
    slug: 'facebook',
    title: 'Facebook / Social Graph',
    difficulty: 'hard',
    category: 'Social Media',
    description: 'Design Facebook — social graph, news feed ranking, groups, events, marketplace, and real-time notifications at 3-billion-user scale.',
    companies: ['Meta', 'Google', 'Snap'],
    tags: ['Social Graph', 'Feed Ranking', 'Scalability'],
    order: 18,
    functionalRequirements: [
      'Friend/follow graph with mutual friend suggestions',
      'News feed: ranked posts from friends, groups, and pages',
      'Groups: public and private, with posts, events, and members',
      'Events: create, RSVP, invite friends',
      'Real-time notifications for likes, comments, tags',
      'Marketplace: buy/sell listings with location filtering',
      'Privacy settings: public, friends, custom audiences',
    ],
    nonFunctionalRequirements: [
      '3 billion MAU, 2 billion DAU',
      'News feed ranked in < 500ms using ML model',
      'Social graph: average 500 friends, max 5,000',
      'Real-time notifications delivered in < 2 seconds',
    ],
    hints: [
      'The social graph is a massive undirected graph stored in TAO (Facebook\'s distributed graph DB) — optimized for fast edge traversals. Friends-of-friends queries use BFS limited to depth 2 with sampling for very high-degree nodes (celebrities).',
      'News Feed ranking: candidate generation (retrieve last 500 posts from friends/groups) → feature extraction (recency, interaction probability, relationship closeness) → ML ranking model scores each post → top-300 posts shown. The ranker is updated continuously with implicit feedback (likes, comments, time spent).',
      'Real-time notifications: use a long-polling or WebSocket connection per client. When an event fires (like, comment), publish to a Notification Queue. A Notification Service fans out to all relevant users\' push channels. For web, use SSE; for mobile, FCM/APNs.',
    ],
  },
]

async function main() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI env var not set')

  await mongoose.connect(uri)
  console.log('Connected to MongoDB')

  let inserted = 0
  let updated  = 0

  for (const p of EXTRA_PROBLEMS) {
    await Problem.findOneAndUpdate(
      { slug: p.slug },
      { $set: p },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    )
    const existing = await Problem.findOne({ slug: p.slug })
    if (existing) {
      const isNew = existing.createdAt.getTime() >= Date.now() - 5000
      isNew ? inserted++ : updated++
    }
    console.log(`  ✓ ${p.difficulty.padEnd(6)} ${p.title}`)
  }

  const total = await Problem.countDocuments({ isActive: true })
  console.log(`\nDone — total active problems: ${total}`)
  await mongoose.disconnect()
}

main().catch(err => { console.error(err); process.exit(1) })
