/**
 * Run with:  npx ts-node -r dotenv/config src/scripts/seed-problems.ts
 */
import 'dotenv/config'
import mongoose from 'mongoose'
import { Problem } from '../models/problem.model'

const PROBLEMS = [
  // ─── EASY ─────────────────────────────────────────────────────────────────
  {
    slug: 'parking-lot',
    title: 'Parking Lot System',
    difficulty: 'easy',
    category: 'Transportation',
    description: 'Design a parking lot system that manages vehicle entry/exit, tracks slot availability across multiple floors, and supports different vehicle sizes.',
    companies: ['Amazon', 'Google', 'Microsoft'],
    tags: ['OOP', 'Design Patterns'],
    order: 1,
    functionalRequirements: [
      'Support multiple floors and parking slots per floor',
      'Handle different vehicle types: motorcycle, car, bus/truck',
      'Assign the nearest available slot on entry',
      'Release the slot on vehicle exit',
      'Calculate parking fee based on duration and vehicle type',
      'Display real-time availability for each floor',
      'Issue a parking ticket with slot info and entry time',
    ],
    nonFunctionalRequirements: [
      'System should support up to 10,000 slots across all floors',
      'Slot assignment should respond in under 100ms',
      'Handle concurrent entry/exit requests safely (thread-safe)',
      'System should be highly available with 99.9% uptime',
    ],
    hints: [
      'Start by identifying the core entities: ParkingLot, Floor, ParkingSlot, Vehicle, and Ticket. Each slot should know its type (compact, large, motorcycle) and whether it\'s occupied.',
      'Use the Strategy pattern for fee calculation — create a FeeCalculator interface with different implementations per vehicle type. Use the Singleton pattern for the ParkingLot itself.',
      'For concurrent slot assignment, maintain a sorted data structure (priority queue) of available slots per floor per type. Use a mutex/lock when assigning or releasing slots to prevent race conditions.',
    ],
  },
  {
    slug: 'library-management',
    title: 'Library Management System',
    difficulty: 'easy',
    category: 'Education',
    description: 'Design a library system that manages books, members, and borrowing/returning operations with fine calculation.',
    companies: ['Microsoft', 'Infosys', 'Wipro'],
    tags: ['OOP', 'CRUD'],
    order: 2,
    functionalRequirements: [
      'Members can search books by title, author, subject, or publication date',
      'Members can borrow and return books',
      'Track multiple copies of the same book',
      'Reserve a book if all copies are borrowed',
      'Calculate fines for overdue returns',
      'Admin can add, update, or remove books',
      'Send notifications for due dates and reservations',
    ],
    nonFunctionalRequirements: [
      'Support up to 100,000 books and 10,000 active members',
      'Search results returned within 500ms',
      'Fine calculation must be accurate to the day',
      'System must prevent duplicate borrowing of the same copy',
    ],
    hints: [
      'Core entities: Library, Book, BookItem (physical copy), Member, BookReservation, BookLending, Fine. A Book can have many BookItems — each BookItem tracks its current state (Available, Reserved, Loaned, Lost).',
      'Use the Observer pattern for notifications: when a reserved book becomes available, notify the member. Book search can use different search strategies (by title, author, subject) via the Strategy pattern.',
      'Model the state transitions for BookItem using a State machine: Available → Reserved → Loaned → Available. Fine calculation should be: (return_date - due_date) * daily_fine_rate, only if return_date > due_date.',
    ],
  },
  {
    slug: 'atm-machine',
    title: 'ATM Machine',
    difficulty: 'easy',
    category: 'Banking',
    description: 'Design an ATM system supporting card authentication, balance inquiry, cash withdrawal, and deposit operations.',
    companies: ['JPMorgan', 'Goldman Sachs', 'Visa'],
    tags: ['State Machine', 'Security'],
    order: 3,
    functionalRequirements: [
      'User inserts card and enters PIN for authentication',
      'Support balance inquiry, cash withdrawal, deposit, and PIN change',
      'Dispense correct denomination of cash',
      'Block card after 3 consecutive failed PIN attempts',
      'Print or show transaction receipt',
      'Handle session timeout after inactivity',
      'Maintain transaction logs',
    ],
    nonFunctionalRequirements: [
      'PIN verification must complete within 2 seconds',
      'Cash dispensing mechanism should be accurate to the cent',
      'All transactions must be ACID-compliant',
      'Communication with bank must be encrypted (TLS)',
    ],
    hints: [
      'Model the ATM as a State Machine with states: Idle, CardInserted, PINVerified, SelectingTransaction, Processing, PrintingReceipt, EjectingCard. Transitions happen on events like card insert, PIN entry, transaction selection.',
      'Key classes: ATM, Card, Account, Bank, CashDispenser, CardReader, Display, Printer, Keypad. The CashDispenser uses the Chain of Responsibility pattern to dispense the fewest bills (e.g., $100 → $50 → $20 → $10 → $5 → $1).',
      'Use the Command pattern for transactions (WithdrawCommand, DepositCommand, BalanceCommand) so each transaction is an object that can be executed, logged, and potentially rolled back. Connect to the Bank via a BankingService interface.',
    ],
  },
  {
    slug: 'elevator-system',
    title: 'Elevator System',
    difficulty: 'easy',
    category: 'Infrastructure',
    description: 'Design an elevator system for a multi-floor building that efficiently dispatches elevators based on requests.',
    companies: ['Amazon', 'Apple', 'Uber'],
    tags: ['Scheduling', 'OOP'],
    order: 4,
    functionalRequirements: [
      'Users press up/down buttons on each floor',
      'Dispatch the optimal elevator to serve the request',
      'Elevator serves all stops in its current direction before reversing',
      'Handle emergency stop and door open/close',
      'Display current floor and direction on each elevator',
      'Support multiple elevators in the building',
    ],
    nonFunctionalRequirements: [
      'Average wait time should be under 60 seconds',
      'System handles up to 20 elevators and 100 floors',
      'Elevator dispatch decisions made in under 50ms',
      'System is fault-tolerant — other elevators take over if one fails',
    ],
    hints: [
      'Core entities: Building, Elevator, Floor, ElevatorButton, FloorButton, Door, ElevatorController. Each Elevator has a state (Moving Up, Moving Down, Idle, Maintenance) and a list of pending floor stops.',
      'Use the SCAN algorithm (similar to disk scheduling) for elevator movement: keep moving in one direction, stop at requested floors, then reverse when no more requests in that direction.',
      'The ElevatorController dispatches elevators using a scoring function: score each elevator by its proximity and direction alignment with the request. The elevator with the lowest score (shortest estimated wait) gets dispatched.',
    ],
  },
  {
    slug: 'vending-machine',
    title: 'Vending Machine',
    difficulty: 'easy',
    category: 'Retail',
    description: 'Design a vending machine that dispenses products, handles payment, and manages inventory.',
    companies: ['Apple', 'Google', 'Samsung'],
    tags: ['State Machine', 'OOP'],
    order: 5,
    functionalRequirements: [
      'Display available products with prices',
      'Accept cash and digital payments',
      'Return change with the fewest coins',
      'Dispense selected product if in stock and sufficient payment made',
      'Refund inserted money if user cancels',
      'Admin mode to restock items and collect cash',
      'Alert admin when stock is low',
    ],
    nonFunctionalRequirements: [
      'Transaction must complete or fully rollback within 5 seconds',
      'Change dispensing must be exact',
      'System should work offline for cash transactions',
      'Inventory updates in real-time',
    ],
    hints: [
      'Model as a State Machine: Idle → HasMoney → ProductSelected → Dispensing → ReturningChange → Idle. Each state handles a subset of inputs (insert coin, select product, cancel, collect).',
      'Use the Chain of Responsibility for change dispensing: try to give change using the largest denomination first, then smaller ones. Keep a CoinBank that tracks available coins.',
      'Key classes: VendingMachine, Inventory, Product, Coin, PaymentProcessor, Dispenser, Display, AdminPanel. The Product class holds name, price, and stock count.',
    ],
  },
  {
    slug: 'snake-and-ladder',
    title: 'Snake and Ladder Game',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a Snake and Ladder board game that supports multiple players, custom board configurations, and game state management.',
    companies: ['Flipkart', 'Paytm'],
    tags: ['OOP', 'Game Design'],
    order: 6,
    functionalRequirements: [
      'Support 2-4 players taking turns',
      'Roll one or two dice per turn',
      'Land on snakes to slide down, ladders to climb up',
      'First player to reach the final square wins',
      'Support custom board sizes and snake/ladder positions',
      'Display current player positions after each turn',
    ],
    nonFunctionalRequirements: [
      'Game state should be serializable (save and resume)',
      'Board validation: no overlapping snakes/ladders',
      'Dice rolls must be truly random',
    ],
    hints: [
      'Core entities: Game, Board, Cell, Player, Dice, Snake, Ladder. Board contains an array of Cells; each Cell can optionally have a Snake (goes to a lower cell) or Ladder (goes to a higher cell).',
      'Use a GameController to manage turn-taking and check win conditions. Use the Builder pattern for Board construction — BoardBuilder validates no overlapping snakes/ladders before building.',
      'Model Snake and Ladder as subclasses of a Jump abstract class with start, end, and a getDestination() method. This way the board lookup is uniform: check if current cell has a Jump, if so apply it.',
    ],
  },
  {
    slug: 'tic-tac-toe',
    title: 'Tic-Tac-Toe',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a Tic-Tac-Toe game supporting human vs human, human vs AI, and board of configurable size.',
    companies: ['Microsoft', 'Amazon'],
    tags: ['OOP', 'Game Design', 'AI'],
    order: 7,
    functionalRequirements: [
      'Support N×N board (not just 3×3)',
      'Two players take turns placing their symbol',
      'Detect win by row, column, or diagonal',
      'Detect draw when board is full with no winner',
      'Support both Human vs Human and Human vs AI modes',
      'AI should play optimally using Minimax algorithm',
    ],
    nonFunctionalRequirements: [
      'Win detection must run in O(1) after each move using incremental counters',
      'AI response time under 500ms for boards up to 5×5',
    ],
    hints: [
      'Core entities: Game, Board, Player (Human/AI subclasses), Move, Symbol. Board has a 2D grid and tracks row/column/diagonal counts per player for O(1) win detection.',
      'Use the Strategy pattern for player logic: Player interface with makeMove() method. HumanPlayer reads input; AIPlayer uses Minimax with Alpha-Beta pruning.',
      'For scalable win detection, maintain four counters per player: rowCount[], colCount[], diag1Count, diag2Count. After each move, increment the relevant counters. If any counter reaches N, that player wins.',
    ],
  },

  // ─── MEDIUM ───────────────────────────────────────────────────────────────
  {
    slug: 'hotel-booking',
    title: 'Hotel Booking System',
    difficulty: 'medium',
    category: 'Travel',
    description: 'Design a hotel booking system where users search, book, and manage hotel room reservations with real-time availability.',
    companies: ['Booking.com', 'Airbnb', 'Expedia'],
    tags: ['Scheduling', 'OOP', 'Concurrency'],
    order: 1,
    functionalRequirements: [
      'Search hotels by location, dates, and guest count',
      'View room types, amenities, photos, and pricing',
      'Book one or more rooms for a date range',
      'Modify or cancel existing bookings',
      'Support room type pricing rules (weekends, seasonal)',
      'Process payments and issue booking confirmations',
      'Hotel admins can manage rooms, prices, and availability',
    ],
    nonFunctionalRequirements: [
      'Handle 10,000 concurrent search requests with sub-second response',
      'Prevent double-booking of the same room via ACID transactions',
      'Payment processing with exactly-once semantics',
      'Availability data can be slightly stale (eventual consistency acceptable for search, strong for booking)',
    ],
    hints: [
      'Core entities: Hotel, Room, RoomType, Booking, Guest, Payment, PricingRule. Room has a RoomType (standard, deluxe, suite) and a BookingCalendar tracking reserved dates.',
      'For availability search, use an interval-based approach: query rooms where no existing Booking overlaps [checkIn, checkOut). For concurrency safety, use optimistic locking or a distributed lock when finalizing a booking.',
      'Use the Strategy pattern for pricing: BasePriceStrategy, WeekendSurchargeStrategy, SeasonalStrategy can be chained using the Decorator pattern. The final price = base × all applicable modifiers.',
    ],
  },
  {
    slug: 'movie-ticket-booking',
    title: 'Movie Ticket Booking',
    difficulty: 'medium',
    category: 'Entertainment',
    description: 'Design a system like BookMyShow — users can browse movies, select showtimes, pick seats, and book tickets.',
    companies: ['BookMyShow', 'Fandango', 'AMC'],
    tags: ['Concurrency', 'Seat Reservation', 'OOP'],
    order: 2,
    functionalRequirements: [
      'Browse movies currently showing in theatres near the user',
      'View available showtimes for a movie',
      'Select seats from an interactive seat map',
      'Reserve seats for 10 minutes while payment is processed',
      'Book tickets and receive a confirmation with QR code',
      'Support cancellation with refund policy',
      'Theatre admins manage movies and showtimes',
    ],
    nonFunctionalRequirements: [
      'Seat reservation must be atomic — two users cannot book the same seat',
      'System handles flash booking spikes (e.g., popular movie release)',
      'Seat map must reflect real-time availability',
      'Temporary reservation expires automatically after 10 minutes',
    ],
    hints: [
      'Core entities: Movie, Theatre, Screen, Show, Seat, Booking, Payment, User. Each Show links a Movie to a Screen at a specific time. Seat has a status (Available, Temporarily Reserved, Booked) and position (row, column).',
      'For seat reservation, use a two-phase approach: phase 1 = temporarily lock the seat with a TTL (10 min) using a distributed lock or a database reservation record; phase 2 = confirm and charge payment, then mark as Booked.',
      'Model seats with SeatType (Regular, Premium, VIP) that affects pricing. Use the Observer pattern to notify waiting users when a reserved seat is released. The Show\'s seat map can be modeled as a 2D boolean array for quick availability display.',
    ],
  },
  {
    slug: 'food-delivery',
    title: 'Food Delivery App',
    difficulty: 'medium',
    category: 'Food-Tech',
    description: 'Design a food delivery platform like Zomato or Swiggy — users order food from restaurants and get real-time delivery tracking.',
    companies: ['Zomato', 'Swiggy', 'DoorDash', 'Uber Eats'],
    tags: ['Real-time', 'OOP', 'Geolocation'],
    order: 3,
    functionalRequirements: [
      'Users browse restaurants filtered by cuisine, rating, and delivery time',
      'Add items to cart and place orders',
      'Real-time order status: placed → accepted → preparing → picked up → delivered',
      'Delivery agent assigned automatically based on proximity',
      'Live tracking of delivery agent on a map',
      'Rating and review system for restaurants and agents',
      'Support multiple payment methods and promo codes',
    ],
    nonFunctionalRequirements: [
      'Delivery agent assignment within 30 seconds of order placement',
      'Location updates pushed every 5 seconds during delivery',
      'System handles 100,000 active orders concurrently',
      'Order status updates delivered with < 2 second latency',
    ],
    hints: [
      'Core entities: User, Restaurant, MenuItem, Order, OrderItem, DeliveryAgent, DeliveryAssignment, Payment, Review. Order has a state machine: Placed → Accepted → Preparing → ReadyForPickup → PickedUp → Delivered.',
      'For agent assignment, use a geospatial query to find available agents within a radius. Score them by distance + current load. Use a pub/sub system (e.g., message queue) to notify the best agent — if they decline, try the next.',
      'Use the Observer pattern for real-time updates: Order is the subject; User, Restaurant, DeliveryAgent are observers. When order status changes, push updates to all subscribers via WebSocket.',
    ],
  },
  {
    slug: 'amazon-locker',
    title: 'Amazon Locker System',
    difficulty: 'medium',
    category: 'Logistics',
    description: 'Design Amazon\'s package locker system where packages are stored in lockers and customers retrieve them using a one-time code.',
    companies: ['Amazon'],
    tags: ['OOP', 'Code Generation'],
    order: 4,
    functionalRequirements: [
      'Assign an available locker of appropriate size for a package',
      'Notify the customer with a one-time access code when package is stored',
      'Customer enters code to unlock and retrieve package',
      'Handle packages not picked up within the return window (3 days)',
      'Multiple locker locations — find the nearest to delivery address',
      'Locker sizes: small, medium, large, extra-large',
    ],
    nonFunctionalRequirements: [
      'Code verification must be instant (< 100ms)',
      'One-time codes expire after 72 hours',
      'System handles 500 lockers per location with concurrent access',
      'Audit log of all access events',
    ],
    hints: [
      'Core entities: LockerLocation, Locker, LockerSize, Package, AccessCode, Notification. LockerLocation has many Lockers; each Locker tracks its size, availability, and current package.',
      'For locker assignment, match the package\'s size to the smallest available locker that fits it. Generate a cryptographically random 6-digit AccessCode with an expiry timestamp. Store the code hashed in the DB.',
      'Model the package lifecycle as a State Machine: InTransit → StoredInLocker → Retrieved / ReturnInitiated → ReturnedToWarehouse. When the 72-hour window expires, a background job changes state to ReturnInitiated.',
    ],
  },
  {
    slug: 'splitwise',
    title: 'Splitwise / Expense Splitter',
    difficulty: 'medium',
    category: 'Fintech',
    description: 'Design an expense splitting app where groups of users can track shared expenses, split costs, and settle debts.',
    companies: ['Splitwise', 'Google Pay', 'PhonePe'],
    tags: ['Graph', 'OOP', 'Finance'],
    order: 5,
    functionalRequirements: [
      'Users create groups (trips, households, friends)',
      'Add expenses and split them equally, unequally, by percentage, or by shares',
      'Show each member\'s net balance (how much they owe or are owed)',
      'Simplify debts: minimize the number of transactions needed to settle',
      'Record settlements when someone pays back',
      'Multi-currency support with exchange rates',
      'Expense history and detailed breakdown',
    ],
    nonFunctionalRequirements: [
      'Balance calculation is always consistent (no rounding errors)',
      'Debt simplification runs in O(n log n)',
      'Support groups up to 50 members',
      'All monetary amounts stored as integers (cents) to avoid floating-point issues',
    ],
    hints: [
      'Core entities: User, Group, Expense, ExpenseSplit, Settlement. An Expense has a payer and multiple Splits (each split records who owes what amount). Balance = sum(what others owe me) − sum(what I owe others).',
      'For split types, use the Strategy pattern: EqualSplit, PercentageSplit, ExactSplit, ShareSplit — each implements calculateAmounts(totalAmount, members). This makes adding new split types easy.',
      'Debt simplification uses a greedy algorithm: compute each person\'s net balance. Keep two heaps (max-creditors and max-debtors). Each step: take the biggest creditor and biggest debtor, settle the smaller amount, repeat. This minimizes transactions.',
    ],
  },
  {
    slug: 'cab-booking',
    title: 'Cab Booking System',
    difficulty: 'medium',
    category: 'Transportation',
    description: 'Design a ride-hailing platform like Uber (simplified) — users request rides, drivers accept, and the system manages matching and pricing.',
    companies: ['Uber', 'Lyft', 'Ola'],
    tags: ['Geolocation', 'Real-time', 'Matching'],
    order: 6,
    functionalRequirements: [
      'Rider requests a ride specifying pickup and drop-off locations',
      'System matches the rider to the nearest available driver',
      'Show estimated fare before confirming the ride',
      'Driver can accept or reject the ride request',
      'Real-time trip tracking for both rider and driver',
      'Fare calculation based on distance, time, and surge pricing',
      'Rating system for riders and drivers',
    ],
    nonFunctionalRequirements: [
      'Driver matching completes within 5 seconds of request',
      'Support 1 million active rides concurrently',
      'Location updates every 3 seconds during a trip',
      'Surge pricing calculated in real-time based on supply/demand',
    ],
    hints: [
      'Core entities: Rider, Driver, Vehicle, Trip, TripRequest, Location, FareCalculator, Rating. Trip has a State Machine: Requested → DriverAccepted → InProgress → Completed / Cancelled.',
      'For driver matching, maintain drivers in a geospatial index (e.g., QuadTree or geohash grid). Query for available drivers within radius R, rank by distance, and send requests sequentially until one accepts or R expands.',
      'Surge pricing uses a multiplier based on demand/supply ratio in a geographic zone. FareCalculator applies: base_fare + (distance × per_km_rate + time × per_min_rate) × surge_multiplier. Use the Strategy pattern for different vehicle types (economy, premium, XL).',
    ],
  },
  {
    slug: 'shopping-cart',
    title: 'Online Shopping Cart',
    difficulty: 'medium',
    category: 'E-commerce',
    description: 'Design an e-commerce shopping cart system supporting product catalogue, cart management, promotions, checkout, and order tracking.',
    companies: ['Amazon', 'Flipkart', 'Shopify'],
    tags: ['OOP', 'E-commerce', 'Inventory'],
    order: 7,
    functionalRequirements: [
      'Browse and search the product catalog with filters',
      'Add, update, or remove items from the cart',
      'Apply promo codes and automatic discounts',
      'Checkout with address selection and payment',
      'Inventory management — prevent overselling',
      'Order history with status tracking',
      'Wishlist to save items for later',
    ],
    nonFunctionalRequirements: [
      'Cart operations must be atomic to prevent inventory inconsistency',
      'Search results returned within 300ms',
      'Flash sale: handle 50,000 concurrent purchases of the same product',
      'Cart data persisted across sessions and devices',
    ],
    hints: [
      'Core entities: Product, Inventory, Cart, CartItem, Order, OrderItem, Payment, Address, Coupon, User. Cart is user-scoped and can exist before checkout. Order is created from Cart on checkout.',
      'Use optimistic locking for inventory: read stock count, decrement in the same transaction with a WHERE stock >= requested_qty. If 0 rows affected, reject the order. This prevents overselling without full table locks.',
      'For promotions, use the Chain of Responsibility or Composite pattern: DiscountRule interface with evaluate(cart) → discount. Chain: ProductDiscount → CategoryDiscount → CouponDiscount → BulkDiscount. Apply all and sum (or take the best).',
    ],
  },

  // ─── HARD ─────────────────────────────────────────────────────────────────
  {
    slug: 'twitter',
    title: 'Twitter / X',
    difficulty: 'hard',
    category: 'Social Media',
    description: 'Design a Twitter-like social platform supporting tweets, follows, timelines, trending topics, and notifications at massive scale.',
    companies: ['Twitter', 'Meta', 'Google'],
    tags: ['Fan-out', 'Feed Generation', 'Scalability'],
    order: 1,
    functionalRequirements: [
      'Post tweets (text up to 280 chars, images, videos)',
      'Follow and unfollow other users',
      'Home timeline shows tweets from followed users, reverse chronological',
      'Like, retweet, quote-tweet, and reply to tweets',
      'Trending topics based on hashtag frequency',
      'User search and tweet search',
      'Notifications for likes, retweets, follows, and mentions',
    ],
    nonFunctionalRequirements: [
      'Support 300 million DAU with 500 million tweets per day',
      'Timeline reads must be < 200ms (P99)',
      'Eventual consistency acceptable for timelines',
      'Tweets must be durable once posted (no loss)',
      'Trending topics updated every 30 seconds',
    ],
    hints: [
      'Core entities: User, Tweet, Follow, Like, Retweet, Hashtag, Notification, Timeline. The key design challenge is the home timeline: fan-out on write (push tweets to followers\' timelines on post) vs fan-out on read (pull tweets on request). Hybrid: fan-out on write for normal users, fan-out on read for celebrities (>1M followers).',
      'Use a Timeline Service backed by a cache (Redis sorted set, score = tweet timestamp). On tweet creation: for each follower, push tweet ID into their timeline cache. Cap timeline cache at 800 entries. For display, fetch tweet details from a Tweet Cache by ID.',
      'For trending topics, use a Count-Min Sketch (probabilistic data structure) to count hashtag occurrences in a sliding 24-hour window efficiently. A MapReduce job or stream processor aggregates counts every 30 seconds and updates the trending list.',
    ],
  },
  {
    slug: 'whatsapp',
    title: 'WhatsApp Messenger',
    difficulty: 'hard',
    category: 'Messaging',
    description: 'Design a real-time messaging system like WhatsApp supporting 1-1 chats, group messages, media sharing, and message status (sent/delivered/read).',
    companies: ['Meta', 'Google', 'Telegram'],
    tags: ['Real-time', 'WebSocket', 'Message Queue'],
    order: 2,
    functionalRequirements: [
      'Send and receive text messages in real-time',
      'Create groups with up to 256 members',
      'Share media (images, videos, documents)',
      'Message status: single tick (sent), double tick (delivered), blue tick (read)',
      'End-to-end encryption for all messages',
      'Last seen and online status',
      'Push notifications for offline users',
    ],
    nonFunctionalRequirements: [
      'Support 2 billion users with 100 billion messages per day',
      'Message delivery latency < 1 second for online users',
      'Messages must not be lost even if recipient is offline for days',
      'End-to-end encrypted — server should not be able to read messages',
    ],
    hints: [
      'Core entities: User, Message, Chat (1-1), Group, GroupMessage, MessageStatus, MediaFile. The key challenge is message delivery: use a WebSocket connection per user for real-time delivery. Messages are stored in a queue (Kafka) and consumed by a delivery service.',
      'For offline delivery: when a user sends a message to an offline recipient, store the message in a persistent message queue associated with the recipient\'s user ID. When recipient reconnects, their device polls or the server pushes all queued messages.',
      'For group messaging with 256 members, avoid fan-out at the application layer. Instead, store a single GroupMessage and let each member\'s client poll or subscribe to the group\'s message stream. Track per-user read receipts in a separate MessageStatus table.',
    ],
  },
  {
    slug: 'netflix',
    title: 'Netflix Streaming Service',
    difficulty: 'hard',
    category: 'Streaming',
    description: 'Design Netflix — a video streaming platform supporting content upload, transcoding, personalised recommendations, and adaptive bitrate streaming at global scale.',
    companies: ['Netflix', 'YouTube', 'Amazon Prime'],
    tags: ['CDN', 'Transcoding', 'Recommendation', 'Streaming'],
    order: 3,
    functionalRequirements: [
      'Users sign up, subscribe to a plan, and manage profiles (up to 5 per account)',
      'Browse and search the content catalog by genre, language, and type',
      'Stream videos with adaptive bitrate (auto-adjust quality based on bandwidth)',
      'Continue watching from where you left off',
      'Personalised recommendations based on watch history',
      'Download content for offline viewing (premium plan)',
      'Multiple simultaneous streams per account (plan-dependent)',
    ],
    nonFunctionalRequirements: [
      '220 million subscribers across 190 countries',
      'Video start time < 2 seconds globally via CDN',
      'Adaptive bitrate from 240p to 4K within the same session',
      'Recommendation model updated daily; inference < 100ms',
      '99.99% streaming availability',
    ],
    hints: [
      'Core entities: User, Profile, Subscription, Content (Movie/Show/Episode), VideoAsset, WatchHistory, WatchProgress. The content pipeline: Upload → Transcode (multiple resolutions + codecs) → Store chunks in object storage → Distribute via CDN.',
      'For adaptive bitrate streaming, split each video into 2-10 second segments at multiple bitrates (240p, 480p, 720p, 1080p, 4K). Serve an HLS or DASH manifest listing all segments. The client player switches bitrate between segments based on measured bandwidth.',
      'Recommendation uses collaborative filtering: represent each user and content as embeddings via matrix factorization. Use an Approximate Nearest Neighbour index (e.g., FAISS) to quickly find content similar to what the user has watched. Store precomputed recommendations and refresh nightly.',
    ],
  },
  {
    slug: 'google-drive',
    title: 'Google Drive',
    difficulty: 'hard',
    category: 'Storage',
    description: 'Design a cloud file storage system like Google Drive supporting file upload, sync, sharing, versioning, and collaborative access.',
    companies: ['Google', 'Dropbox', 'Microsoft'],
    tags: ['Distributed Storage', 'Sync', 'Versioning'],
    order: 4,
    functionalRequirements: [
      'Upload and download files of any type/size',
      'Organise files in a hierarchical folder structure',
      'Share files/folders with view or edit permissions',
      'Real-time collaborative editing for supported file types',
      'Version history — restore any previous version',
      'Sync files across multiple devices automatically',
      'Full-text search across all user files',
    ],
    nonFunctionalRequirements: [
      '1 billion users, 15 GB free storage per user',
      'Large file uploads (up to 5 TB) via resumable multipart upload',
      'Sync conflict resolution without data loss',
      'File deduplication at the block level to save storage',
      'Global access with < 100ms metadata operations',
    ],
    hints: [
      'Core entities: User, File, Folder, FileVersion, FileBlock, SyncDevice, SharePermission. Split large files into fixed-size blocks (~4MB each). Each block is content-addressed (SHA-256 hash). If two users upload the same file, only one copy of each block is stored (deduplication).',
      'For the sync protocol: maintain a local and remote change log (vector clock or Merkle tree per folder). On sync, compare the logs to find conflicting changes. If two devices modify the same file, create a conflict copy rather than losing data.',
      'Metadata (file names, folder structure, permissions) is stored in a relational DB (sharded by user). Actual file blocks are stored in object storage (GCS/S3). A chunk server maps block hashes to object storage locations. The client uploads blocks directly to object storage via pre-signed URLs.',
    ],
  },
  {
    slug: 'instagram',
    title: 'Instagram',
    difficulty: 'hard',
    category: 'Social Media',
    description: 'Design Instagram — a photo/video sharing social network with feeds, stories, explore, direct messages, and influencer-scale follower graphs.',
    companies: ['Meta', 'Snap', 'TikTok'],
    tags: ['Feed Generation', 'Media Processing', 'CDN'],
    order: 5,
    functionalRequirements: [
      'Upload photos and videos with captions, tags, and location',
      'Follow other users and see their posts in a ranked feed',
      'Stories that disappear after 24 hours',
      'Explore page with trending and personalised content',
      'Like, comment, save, and share posts',
      'Direct messaging between users',
      'Notifications for interactions on your content',
    ],
    nonFunctionalRequirements: [
      '2 billion DAU, 100 million photos uploaded per day',
      'Feed ranked by ML model, refreshed on each open',
      'Photos served via CDN globally in < 100ms',
      'Stories deleted exactly at 24h via background jobs',
      'Influencers with 100M+ followers — timeline fan-out strategy must adapt',
    ],
    hints: [
      'Core entities: User, Post, Media, Story, Follow, Like, Comment, DirectMessage, Notification, Feed. Media pipeline: Upload → Validate → Resize/transcode to multiple resolutions → Store in object storage → Invalidate CDN cache → Index for search.',
      'Feed generation uses a hybrid strategy: for users with < 1M followers, fan-out on write (push post ID to followers\' feed caches on upload). For celebrities (> 1M followers), fan-out on read (fetch their posts at read time and merge with the pre-built feed). Use Redis sorted sets for feed caches.',
      'Stories use a time-based expiry: store story metadata with a TTL. A background worker runs every hour and soft-deletes stories past 24h. Media files are moved to cold storage after deletion. Use Bloom filters to efficiently check if a user has seen a story.',
    ],
  },
  {
    slug: 'uber-full',
    title: 'Uber (Full Design)',
    difficulty: 'hard',
    category: 'Transportation',
    description: 'Full-scale Uber design: real-time matching, dynamic pricing, trip management, driver supply management, and fraud detection.',
    companies: ['Uber', 'Lyft', 'DiDi'],
    tags: ['Geolocation', 'Real-time', 'Surge Pricing', 'Matching'],
    order: 6,
    functionalRequirements: [
      'Rider requests a ride; system finds and assigns best driver in < 30 seconds',
      'Dynamic surge pricing based on real-time supply/demand',
      'Multi-product support: UberX, UberXL, UberPool, UberBlack',
      'Live trip tracking with ETA updates for both rider and driver',
      'Driver supply management and incentives',
      'Fraud detection for fake rides and payment fraud',
      'Dispute resolution and safety features (SOS button)',
    ],
    nonFunctionalRequirements: [
      '14 million trips per day globally across all cities',
      'Driver location updated every 4 seconds',
      'Matching latency < 5 seconds from request to driver assignment',
      'Surge pricing recalculated every 60 seconds per geographic zone',
      'System handles 1 million concurrent active trips',
    ],
    hints: [
      'Split into microservices: TripService, MatchingService, LocationService, PricingService, NotificationService. LocationService maintains a geospatial index (H3 hexagonal grid) of all active drivers, updated every 4 seconds. MatchingService queries LocationService for drivers in the rider\'s hex cell and expands outward.',
      'For driver matching, use a supply-demand index per H3 cell at multiple resolutions. When a trip is requested: query available drivers in resolution-9 cell (≈0.1 km²), rank by ETA, send offer to top driver. If no response in 8 seconds, try the next. Expand search radius if no drivers found.',
      'Surge pricing: for each H3 cell, compute surge_multiplier = f(demand_rate / supply_rate). If ratio > 1.2, apply surge. Use exponential smoothing to prevent wild oscillations. Store surge maps in Redis for sub-millisecond pricing lookups. Cap surge at 8x and notify riders before confirming.',
    ],
  },
]

async function main() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI env var not set')

  await mongoose.connect(uri)
  console.log('Connected to MongoDB')

  let inserted = 0
  let updated  = 0

  for (const p of PROBLEMS) {
    const result = await Problem.findOneAndUpdate(
      { slug: p.slug },
      { $set: p },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    )
    if (result.createdAt.getTime() === result.updatedAt.getTime()) inserted++
    else updated++
    console.log(`  ✓ ${p.difficulty.padEnd(6)} ${p.title}`)
  }

  console.log(`\nDone — ${inserted} inserted, ${updated} updated`)
  await mongoose.disconnect()
}

main().catch(err => { console.error(err); process.exit(1) })
