/**
 * Seed 10 long-form SEO-optimised blog posts.
 * Run: npx ts-node -r dotenv/config src/scripts/seed-blogs.ts
 *
 * Content is kept in plain JS objects using normal double-quoted strings
 * to avoid TypeScript template-literal / backtick parsing issues.
 */
import 'dotenv/config'
import mongoose from 'mongoose'
import { Blog } from '../models/blog.model'

function wpm(content: string) {
  return Math.max(1, Math.ceil(content.trim().split(/\s+/).length / 200))
}

const AUTHOR = { name: 'LLDCanvas Team', role: 'Engineering', avatar: '' }

/* ─────────────────────────────────────────────────────────────────────────────
   Helper: build a markdown string without using backtick template literals.
   We use tagged-string concatenation so TypeScript never sees lone backticks
   inside strings.
───────────────────────────────────────────────────────────────────────────── */
const NL = '\n'
const CB = '`'          // single backtick – used for inline code in markdown
const TRI = CB + CB + CB  // triple backtick – used for code fences

/* eslint-disable max-len */

// ─── Blog 1 ──────────────────────────────────────────────────────────────────
const blog1Content = [
  '## Introduction',
  '',
  'System design interviews are the most misunderstood round in software engineering hiring. Candidates spend months practicing algorithms but walk into design rounds unprepared, treating them like a trivia quiz rather than a structured conversation.',
  '',
  'This guide gives you a complete, battle-tested framework to tackle any system design question - from "Design Twitter" to "Design a distributed rate limiter" - at top tech companies like Google, Meta, Amazon, Uber, and Flipkart.',
  '',
  '> **Before we start:** If you want to practice what you learn here, [LLDCanvas\'s Interview Mode](/features/interview-mode) gives you a timed canvas, structured problem briefs, and analytics on your performance. 110+ real LLD and HLD questions, all in one place.',
  '',
  '---',
  '',
  '## What Interviewers Actually Evaluate',
  '',
  'Most candidates think system design is about knowing the "right" answer. It is not.',
  '',
  'Interviewers evaluate four dimensions:',
  '',
  '1. **Problem clarification** - Do you ask the right questions before jumping to solutions?',
  '2. **Structured thinking** - Can you break a complex problem into manageable pieces?',
  '3. **Technical depth** - Do you know *why* you chose a particular database, queue, or caching strategy?',
  '4. **Trade-off reasoning** - Can you articulate the pros and cons of each decision?',
  '',
  'A candidate who picks a "suboptimal" architecture but explains the trade-offs clearly will almost always score higher than one who jumps to the "correct" answer without reasoning.',
  '',
  '---',
  '',
  '## The 6-Step Framework',
  '',
  '### Step 1: Clarify Requirements (5 minutes)',
  '',
  'Never start designing until you understand what you are building. Ask:',
  '',
  '- **Functional requirements**: What does the system do? What features are in scope?',
  '- **Non-functional requirements**: Scale, latency, availability, consistency?',
  '- **Constraints**: Read-heavy or write-heavy? Global or regional? Real-time or batch?',
  '',
  '**Example for "Design a URL Shortener":**',
  '- How many URLs per day? (100M/day = ~1,150 writes/second)',
  '- How long are shortened URLs valid?',
  '- Do we need analytics on clicks?',
  '- Is 99.9% or 99.99% availability required?',
  '',
  '### Step 2: Estimate Scale (3 minutes)',
  '',
  'Back-of-the-envelope math signals engineering maturity:',
  '',
  '- **Traffic**: QPS = (requests per day) / 86,400',
  '- **Storage**: (records per day) x (bytes per record) x (retention years)',
  '- **Bandwidth**: QPS x (average payload size)',
  '',
  'For a URL shortener with 100M writes/day and 10B reads/day:',
  '- Write QPS: ~1,150/s',
  '- Read QPS: ~115,000/s (100:1 read-to-write ratio)',
  '- Storage per URL: ~500 bytes -> 100M x 500B = 50GB/day',
  '',
  '### Step 3: Define the API (5 minutes)',
  '',
  'Design the public interface before the internals.',
  '',
  TRI,
  'POST /shorten',
  'Body: { url: "https://very-long-url.com/...", alias?: "my-link", ttl?: 86400 }',
  'Response: { shortUrl: "https://lldcanvas.app/abc123" }',
  '',
  'GET /{shortCode}',
  'Response: 301 Redirect to original URL',
  TRI,
  '',
  '### Step 4: Design the High-Level Architecture (15 minutes)',
  '',
  'Draw the major components:',
  '',
  '- **Client** -> **Load Balancer** -> **API Servers** -> **Database**',
  '- Add **Cache** (Redis) for hot reads',
  '- Add **CDN** for static assets',
  '- Add **Message Queue** (Kafka) for async processing',
  '',
  '### Step 5: Deep Dive into Components (15 minutes)',
  '',
  'Pick 2-3 critical components and go deep.',
  '',
  '**Database choice for URL shortener:**',
  '- Key-value pattern -> NoSQL like DynamoDB or Cassandra works well',
  '- Short code generation: Base62 encoding of an auto-incremented ID',
  '',
  '**Caching strategy:**',
  '- LRU cache in Redis for top 20% of URLs (which serve 80% of traffic)',
  '- TTL matches URL expiry',
  '- Cache-aside pattern: check cache first, fall back to DB',
  '',
  '### Step 6: Address Trade-offs (5 minutes)',
  '',
  '- What happens if Redis goes down? (Fallback to DB, tolerable latency increase)',
  '- What if a URL goes viral? (Hot key problem - local cache in app server)',
  '- CAP theorem applies: for URL shortener, AP is acceptable',
  '',
  '---',
  '',
  '## Core Building Blocks to Master',
  '',
  '### Databases',
  '',
  '| Type | Best For | Examples |',
  '|------|----------|---------|',
  '| Relational | ACID transactions, complex queries | PostgreSQL, MySQL |',
  '| Document | Flexible schema, nested data | MongoDB |',
  '| Key-Value | Caching, sessions, simple lookups | Redis, DynamoDB |',
  '| Wide-Column | Time-series, high write throughput | Cassandra |',
  '| Search | Full-text search | Elasticsearch |',
  '',
  '### Caching Strategies',
  '',
  '- **Cache-aside (lazy loading)**: App checks cache; on miss, loads from DB and populates cache.',
  '- **Write-through**: Write to cache and DB simultaneously. Strong consistency, higher write latency.',
  '- **Write-behind (write-back)**: Write to cache only; flush to DB asynchronously.',
  '',
  '### Consistent Hashing',
  '',
  'Used to distribute data across nodes in a way that minimizes reshuffling when nodes are added/removed. Used in Redis Cluster, Cassandra, CDN routing.',
  '',
  '### CAP Theorem',
  '',
  'A distributed system can guarantee at most 2 of 3 properties: Consistency, Availability, Partition Tolerance.',
  '',
  '- **CP systems**: Strong consistency, may sacrifice availability. HBase, ZooKeeper.',
  '- **AP systems**: Always available, may return stale data. Cassandra, DynamoDB.',
  '',
  '---',
  '',
  '## Common System Design Questions',
  '',
  '### Design Twitter',
  '- Read-heavy (100:1 read-write ratio)',
  '- **Fan-out on write** for users with < 1M followers',
  '- **Fan-out on read** for celebrities - too expensive to write to 50M timelines',
  '- **Hybrid approach**: Celebrities pulled on read; regular users pushed on write',
  '',
  '### Design WhatsApp',
  '- WebSocket for persistent connections',
  '- Message routing: sender -> WebSocket server -> Message Queue -> recipient',
  '- **Presence service**: Redis pub/sub for online/offline status',
  '- Message storage: Cassandra (write-heavy, time-ordered)',
  '',
  '### Design YouTube',
  '- Upload pipeline: Raw video -> Transcoding -> Multiple resolutions -> CDN',
  '- HLS for adaptive bitrate streaming',
  '- Video metadata in PostgreSQL; actual files in S3/GCS',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'System design interviews reward structured thinking over encyclopedic knowledge. Master the 6-step framework, understand the core building blocks deeply, and practice applying trade-off reasoning to every decision you make.',
  '',
  'Start practicing today with [LLDCanvas\'s Interview Mode](/features/interview-mode) - 110+ real problems, timed sessions, and analytics to track your improvement.',
].join(NL)

// ─── Blog 2 ──────────────────────────────────────────────────────────────────
const blog2Content = [
  '## What is Low-Level Design?',
  '',
  'Low-Level Design (LLD) is the art of designing the internal structure of a software system: the classes, interfaces, methods, relationships, and design patterns that make a feature work correctly, be maintainable, and scale as requirements change.',
  '',
  '> **Practice as you learn:** [LLDCanvas](/features/editor) gives you a UML canvas with 23 pre-wired design pattern templates and 110+ practice problems.',
  '',
  '---',
  '',
  '## The LLD Interview Roadmap',
  '',
  '### Phase 1: OOP Fundamentals (Week 1)',
  '',
  '**The 4 Pillars:**',
  '',
  '1. **Encapsulation** - Bundle data and behavior together; hide implementation details',
  '2. **Abstraction** - Expose what a component does, hide how it does it',
  '3. **Inheritance** - Model "is-a" relationships',
  '4. **Polymorphism** - Same interface, different behavior',
  '',
  TRI + 'java',
  '// Good: encapsulated with controlled access',
  'public class BankAccount {',
  '  private double balance;',
  '  ',
  '  public void deposit(double amount) {',
  '    if (amount <= 0) throw new IllegalArgumentException("Amount must be positive");',
  '    this.balance += amount;',
  '  }',
  '  ',
  '  public double getBalance() { return balance; }',
  '}',
  TRI,
  '',
  '---',
  '',
  '### Phase 2: SOLID Principles (Week 1-2)',
  '',
  '| Principle | One-line Summary |',
  '|-----------|-----------------|',
  '| **S**ingle Responsibility | One class, one reason to change |',
  '| **O**pen/Closed | Open for extension, closed for modification |',
  '| **L**iskov Substitution | Subclass must be usable wherever parent is used |',
  '| **I**nterface Segregation | Small focused interfaces > one fat interface |',
  '| **D**ependency Inversion | Depend on abstractions, not concretions |',
  '',
  '---',
  '',
  '### Phase 3: Design Patterns (Week 2-4)',
  '',
  '#### Creational Patterns',
  '',
  '**Singleton** - Exactly one instance of a class',
  '',
  TRI + 'java',
  'public class DatabaseConnection {',
  '  private static DatabaseConnection instance;',
  '  private DatabaseConnection() {}',
  '  ',
  '  public static synchronized DatabaseConnection getInstance() {',
  '    if (instance == null) instance = new DatabaseConnection();',
  '    return instance;',
  '  }',
  '}',
  TRI,
  '',
  '**Factory Method** - Let subclasses decide which class to instantiate',
  '**Builder** - Construct complex objects step by step',
  '',
  '#### Structural Patterns',
  '',
  '**Decorator** - Add behavior without subclassing',
  '**Facade** - Simplified interface to a complex subsystem',
  '**Composite** - Treat individual objects and compositions uniformly',
  '',
  '#### Behavioral Patterns',
  '',
  '**Observer** - One-to-many event notification',
  '',
  TRI + 'java',
  'public interface Observer { void update(Event event); }',
  '',
  'public class EventBus {',
  '  private Map<String, List<Observer>> subscribers = new HashMap<>();',
  '  ',
  '  public void subscribe(String event, Observer observer) {',
  '    subscribers.computeIfAbsent(event, k -> new ArrayList<>()).add(observer);',
  '  }',
  '  ',
  '  public void publish(String event, Event data) {',
  '    subscribers.getOrDefault(event, List.of()).forEach(o -> o.update(data));',
  '  }',
  '}',
  TRI,
  '',
  '**Strategy** - Swap algorithms at runtime',
  '**Command** - Encapsulate a request as an object',
  '**State** - Change behavior based on internal state',
  '',
  '---',
  '',
  '### Phase 4: LLD Problem-Solving Framework',
  '',
  '**Step 1: Clarify Requirements (2 min)** - What types of entities? What operations?',
  '**Step 2: Identify Core Entities (3 min)** - Nouns in the requirements become classes',
  '**Step 3: Define Relationships (3 min)** - Has-many, belongs-to, implements',
  '**Step 4: Identify Design Patterns (5 min)** - Which patterns apply?',
  '**Step 5: Write the Class Structure (15 min)** - Start with interfaces, then concrete classes',
  '**Step 6: Handle Edge Cases (5 min)** - Concurrency, null checks, validation',
  '',
  '---',
  '',
  '### Phase 5: Practice Problems by Difficulty',
  '',
  '**Easy:** [Parking Lot](/dashboard/problems/parking-lot), [Vending Machine](/dashboard/problems/vending-machine), [Library Management](/dashboard/problems/library-management)',
  '',
  '**Medium:** [LRU Cache](/dashboard/problems/simple-lru-cache), [Elevator System](/dashboard/problems/elevator-system), [Hotel Booking](/dashboard/problems/hotel-booking), [ATM Machine](/dashboard/problems/atm-machine)',
  '',
  '**Hard:** [Splitwise](/dashboard/problems/splitwise), [Chess Game](/dashboard/problems/chess-game), [Stock Exchange](/dashboard/problems/online-stock-brokerage)',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'LLD mastery comes from three things: deeply understanding OOP principles, internalizing the patterns until they become second nature, and practicing problems until the entity-identification process feels automatic.',
  '',
  'Follow this roadmap, practice consistently, and you will be solving LLD problems with confidence within 4-8 weeks. Use [LLDCanvas](/features/interview-questions) for hands-on practice.',
].join(NL)

// ─── Blog 3 ──────────────────────────────────────────────────────────────────
const blog3Content = [
  '## The Core Distinction',
  '',
  'Imagine you are asked to "Design Netflix." Two very different interviews could follow:',
  '',
  '**Interview A (HLD):** The interviewer wants to know how 200 million users stream video simultaneously. You discuss CDNs, video transcoding pipelines, content delivery, recommendation engines, load balancers, and database choices.',
  '',
  '**Interview B (LLD):** The interviewer wants to know how the ' + CB + 'VideoPlayer' + CB + ', ' + CB + 'Subscription' + CB + ', ' + CB + 'User' + CB + ', and ' + CB + 'WatchHistory' + CB + ' classes relate to each other.',
  '',
  'Same problem, completely different answers. This is the HLD vs LLD distinction.',
  '',
  '---',
  '',
  '## High-Level Design (HLD)',
  '',
  '### What You Design',
  '',
  '- **System components**: API Gateway, Application servers, Databases, Cache, Message Queues, CDN',
  '- **Data stores**: Which database (SQL vs NoSQL), why, and how to organize data',
  '- **APIs**: External interfaces (REST, gRPC, GraphQL)',
  '- **Data flow**: How a request moves through the system end-to-end',
  '- **Scalability approach**: Horizontal scaling, sharding, replication',
  '',
  '### HLD Example: Design Instagram',
  '',
  TRI,
  'Users -> DNS -> CDN (static assets)',
  '             -> Load Balancer',
  '               -> API Gateway',
  '                 -> User Service     -> PostgreSQL (users, follows)',
  '                 -> Post Service     -> PostgreSQL (posts) + S3 (images)',
  '                 -> Feed Service     -> Redis (pre-computed feeds)',
  '                 -> Search Service   -> Elasticsearch',
  '                 -> Notification     -> Kafka -> Push Service',
  TRI,
  '',
  '---',
  '',
  '## Low-Level Design (LLD)',
  '',
  '### What You Design',
  '',
  '- **Classes and interfaces**: Names, attributes, methods',
  '- **Relationships**: Inheritance, composition, aggregation',
  '- **Design patterns**: Which patterns apply and why',
  '- **Algorithms**: Pseudocode for core logic',
  '',
  '### LLD Example: Design the Instagram Post Feature',
  '',
  TRI + 'java',
  'interface MediaContent {',
  '  String getId();',
  '  String getUrl();',
  '  MediaType getType();',
  '}',
  '',
  'class Post {',
  '  private String id;',
  '  private User author;',
  '  private List<MediaContent> media;   // supports carousel posts',
  '  private String caption;',
  '  private PostVisibility visibility;  // PUBLIC, FOLLOWERS, CLOSE_FRIENDS',
  '  private int likesCount;',
  '}',
  '',
  '// Factory for creating different media types',
  'class MediaFactory {',
  '  public static MediaContent create(MediaType type, String url) {',
  '    return switch (type) {',
  '      case PHOTO -> new Photo(url);',
  '      case VIDEO -> new Video(url);',
  '      case REEL  -> new Reel(url);',
  '    };',
  '  }',
  '}',
  TRI,
  '',
  '---',
  '',
  '## Side-by-Side Comparison',
  '',
  '| Dimension | HLD | LLD |',
  '|-----------|-----|-----|',
  '| **Scope** | Entire system | A single component/feature |',
  '| **Output** | Architecture diagram | Class diagram / pseudocode |',
  '| **Focus** | Services, data stores, communication | Classes, patterns, relationships |',
  '| **Key concepts** | CAP, sharding, CDN, queues | SOLID, patterns, OOP |',
  '| **Common mistake** | Skipping scale estimation | Skipping requirement clarification |',
  '',
  '---',
  '',
  '## Which Round Am I In?',
  '',
  '**Signs it is an HLD round:**',
  '- Question is "Design Twitter/Netflix/Uber/WhatsApp"',
  '- Interviewer asks about scale ("how do you handle 10M users?")',
  '- You are expected to draw boxes with arrows between them',
  '',
  '**Signs it is an LLD round:**',
  '- Question is "Design a Parking Lot/Elevator/Chess Game"',
  '- Interviewer asks "what classes would you create?"',
  '- You are expected to draw UML class diagrams',
  '',
  '**When it is ambiguous:** Ask. "Should I focus on the overall system architecture or the class-level design?"',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'HLD and LLD are complementary skills. Great engineers need both: the architectural vision to design scalable systems (HLD) and the design discipline to build clean, maintainable components (LLD).',
  '',
  'Read our [system design guide](/blog/system-design-interview-guide) for HLD prep, and the [LLD roadmap](/blog/lld-interview-roadmap) for LLD prep. Practice both on [LLDCanvas](/features/interview-questions).',
].join(NL)

// ─── Blog 4 ──────────────────────────────────────────────────────────────────
const blog4Content = [
  '## The Top 25 LLD Questions',
  '',
  'These questions are ranked by frequency across interview reports from Google, Amazon, Meta, Flipkart, Swiggy, Uber, Ola, CRED, Razorpay, and other top companies.',
  '',
  '> **Hands-on practice:** All problems are available on [LLDCanvas](/features/interview-questions) with problem briefs, staged hints, and a UML canvas.',
  '',
  '---',
  '',
  '### 1. Design a Parking Lot System',
  '**Frequency:** Very High | **Companies:** Amazon, Google, Flipkart',
  '',
  '**Core entities:** ParkingLot, ParkingFloor, ParkingSpot, Vehicle (Car/Bike/Truck), Ticket, Payment',
  '',
  '**Key patterns:** Factory (vehicle types), Strategy (pricing), Singleton (ParkingLot), Observer (display boards)',
  '',
  '**Critical insight:** Model ParkingSpot with a ' + CB + 'VehicleType' + CB + ' it accepts.',
  '',
  TRI + 'java',
  'public class ParkingSpot {',
  '  private SpotType type;',
  '  private boolean occupied;',
  '  private Vehicle currentVehicle;',
  '  ',
  '  public boolean canFit(Vehicle vehicle) {',
  '    return !occupied && type.accommodates(vehicle.getType());',
  '  }',
  '}',
  TRI,
  '',
  '---',
  '',
  '### 2. Design an LRU Cache',
  '**Frequency:** Very High | **Companies:** Google, Amazon, Uber',
  '',
  '**Core:** HashMap (O(1) lookup) + Doubly Linked List (O(1) eviction)',
  '',
  TRI + 'java',
  'public class LRUCache<K, V> {',
  '  private final int capacity;',
  '  private final Map<K, Node<K,V>> map = new HashMap<>();',
  '  private final Node<K,V> head = new Node<>(null, null);',
  '  private final Node<K,V> tail = new Node<>(null, null);',
  '  ',
  '  public V get(K key) {',
  '    Node<K,V> node = map.get(key);',
  '    if (node == null) return null;',
  '    moveToFront(node);',
  '    return node.value;',
  '  }',
  '}',
  TRI,
  '',
  '---',
  '',
  '### 3. Design an Elevator System',
  '**Frequency:** High | **Companies:** Amazon, Uber, Flipkart',
  '',
  '**Key patterns:** State (IDLE/MOVING_UP/MOVING_DOWN), Strategy (SCAN/LOOK scheduling), Observer (floor displays)',
  '',
  '**Critical insight:** Use SCAN algorithm - elevator moves in one direction until it hits the boundary, then reverses.',
  '',
  '---',
  '',
  '### 4. Design a Vending Machine',
  '**Frequency:** High | **Companies:** Google, Microsoft, Amazon',
  '',
  '**Key patterns:** State (Idle/HasMoney/Dispense/Return), Singleton, Factory',
  '',
  '**Critical insight:** Each state implements ' + CB + 'VendingState' + CB + ' interface with ' + CB + 'insertCoin()' + CB + ', ' + CB + 'selectProduct()' + CB + ', ' + CB + 'dispense()' + CB + '.',
  '',
  '---',
  '',
  '### 5-25: Quick Reference',
  '',
  '| # | Problem | Top Patterns | Key Insight |',
  '|---|---------|-------------|-------------|',
  '| 5 | Library Management | Factory, Strategy, Observer | Book vs BookItem (catalog vs physical copy) |',
  '| 6 | Chess Game | Abstract Factory, Strategy, Command | Each Piece implements getValidMoves() |',
  '| 7 | ATM Machine | State, Chain of Responsibility, Command | ATM as a state machine |',
  '| 8 | Hotel Booking | Factory, Strategy, Command | Atomic availability check |',
  '| 9 | Pub-Sub System | Observer, Strategy, Factory | Push vs pull delivery |',
  '| 10 | Ride-Sharing (Uber) | Strategy, Observer, State, Factory | Trip state machine |',
  '| 11 | Snake and Ladder | State, Command | Board is immutable |',
  '| 12 | Splitwise | Graph, Strategy | Min-cash-flow algorithm |',
  '| 13 | Movie Ticket Booking | Factory, Strategy, Command | Seat locking with expiry |',
  '| 14 | Food Delivery | State, Observer, Strategy | Order state machine |',
  '| 15 | LinkedIn Clone | Composite, Observer | Graph for connections |',
  '| 16 | Online Auction | Observer, Strategy, State | Auction state machine |',
  '| 17 | Car Rental | Factory, Strategy, Command | Vehicle availability matrix |',
  '| 18 | Course Registration | Factory, Observer, Composite | Prerequisite graph |',
  '| 19 | Task Manager | Observer, Command, Composite | Task state machine |',
  '| 20 | Inventory System | Observer, Strategy, Factory | Reorder triggers |',
  '| 21 | Stock Exchange | Command, Observer, Strategy | Order matching engine |',
  '| 22 | Coffee Vending Machine | State, Factory | Focus on ingredient management |',
  '| 23 | Hospital Management | Factory, Observer, Strategy | Priority scheduling |',
  '| 24 | Restaurant Management | Observer, Decorator, State | Order workflow |',
  '| 25 | Airline Management | State, Factory, Strategy | Booking hold + confirm |',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'These 25 questions represent the core of LLD interview preparation. Master the first 10 thoroughly, have strong answers for 11-20, and be aware of 21-25.',
  '',
  'Practice on [LLDCanvas](/features/interview-questions) with a timer to simulate real interview conditions.',
].join(NL)

// ─── Blog 5 ──────────────────────────────────────────────────────────────────
const blog5Content = [
  '## Why SOLID Matters',
  '',
  'Robert C. Martin ("Uncle Bob") compiled five object-oriented design principles under the SOLID acronym in 2000. They remain the most cited design principles in software engineering interviews - and for good reason: they encode hard-won lessons about what makes code easy to change.',
  '',
  '> **See SOLID in action:** The [revision notes on LLDCanvas](/features/revision-notes) cover all five principles with interactive examples.',
  '',
  '---',
  '',
  '## S - Single Responsibility Principle (SRP)',
  '',
  '> *"A class should have only one reason to change."*',
  '',
  '**The Violation:** An ' + CB + 'Employee' + CB + ' class that handles business logic, database persistence, AND report generation has three reasons to change.',
  '',
  TRI + 'java',
  '// BAD: Three responsibilities in one class',
  'public class Employee {',
  '  public double calculatePay() { ... }     // business logic',
  '  public void save() { /* SQL */ }         // DB concern',
  '  public String generateReport() { ... }  // reporting concern',
  '}',
  '',
  '// GOOD: Single responsibility each',
  'public class Employee      { public double calculatePay() { ... } }',
  'public class EmployeeRepo  { public void save(Employee e) { ... } }',
  'public class EmployeeReport{ public String generate(Employee e) { ... } }',
  TRI,
  '',
  '---',
  '',
  '## O - Open/Closed Principle (OCP)',
  '',
  '> *"Open for extension, closed for modification."*',
  '',
  TRI + 'java',
  '// BAD: Adding customer type requires modifying this class',
  'public class DiscountCalculator {',
  '  public double calculate(Order order) {',
  '    if (order.getType() == REGULAR)  return order.getTotal() * 0.05;',
  '    if (order.getType() == PREMIUM)  return order.getTotal() * 0.10;',
  '    // Every new type = modify this method',
  '  }',
  '}',
  '',
  '// GOOD: Strategy pattern - add new class, never touch DiscountCalculator',
  'public interface DiscountStrategy { double calculate(Order o); }',
  'public class RegularDiscount  implements DiscountStrategy { ... }',
  'public class PremiumDiscount  implements DiscountStrategy { ... }',
  TRI,
  '',
  '---',
  '',
  '## L - Liskov Substitution Principle (LSP)',
  '',
  '> *"Objects of a subclass should be replaceable for objects of the parent class without breaking the application."*',
  '',
  '**Classic violation:** Square extending Rectangle. Setting width and height independently on a Square breaks Rectangle\'s area contract.',
  '',
  '**Fix:** Both implement a ' + CB + 'Shape' + CB + ' interface instead of Square inheriting from Rectangle.',
  '',
  '---',
  '',
  '## I - Interface Segregation Principle (ISP)',
  '',
  '> *"Clients should not be forced to depend on interfaces they do not use."*',
  '',
  TRI + 'java',
  '// BAD: Robot forced to implement eat() and sleep()',
  'public interface WorkerInterface {',
  '  void work();',
  '  void eat();',
  '  void sleep();',
  '}',
  '',
  '// GOOD: Focused interfaces',
  'public interface Workable  { void work();  }',
  'public interface Eatable   { void eat();   }',
  'public interface Sleepable { void sleep(); }',
  'public class Robot implements Workable { public void work() { ... } }',
  TRI,
  '',
  '---',
  '',
  '## D - Dependency Inversion Principle (DIP)',
  '',
  '> *"High-level modules should not depend on low-level modules. Both should depend on abstractions."*',
  '',
  TRI + 'java',
  '// BAD: OrderService depends on concrete MySQLOrderRepository',
  'public class OrderService {',
  '  private MySQLOrderRepository repository = new MySQLOrderRepository();',
  '}',
  '',
  '// GOOD: Depends on interface - can swap any implementation',
  'public class OrderService {',
  '  private final OrderRepository repository;',
  '  public OrderService(OrderRepository repo) { this.repository = repo; }',
  '}',
  TRI,
  '',
  '---',
  '',
  '## SOLID in Design Patterns',
  '',
  '| Design Pattern | SOLID Principles Applied |',
  '|---|---|',
  '| Strategy | OCP, DIP |',
  '| Observer | OCP, DIP |',
  '| Factory Method | DIP, OCP |',
  '| Decorator | OCP, SRP |',
  '| Composite | LSP |',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'SOLID principles are not academic rules - they are the distilled wisdom of thousands of engineers who learned the hard way what makes code easy to change. Apply them consistently, explain them fluently in interviews.',
  '',
  'For interactive SOLID exercises, explore [LLDCanvas\'s revision notes](/features/revision-notes) and [practice problems](/features/interview-questions).',
].join(NL)

// ─── Blog 6 ──────────────────────────────────────────────────────────────────
const blog6Content = [
  '## What Are Design Patterns?',
  '',
  'Design patterns are reusable solutions to commonly occurring problems in software design. The Gang of Four (GoF) book "Design Patterns: Elements of Reusable Object-Oriented Software" (1994) defines 23 patterns that remain the most important set in software engineering today.',
  '',
  '> **Practice on a canvas:** [LLDCanvas](/features/editor) has pre-wired templates for all 23 GoF patterns.',
  '',
  '---',
  '',
  '## Creational Patterns',
  '',
  '### Singleton',
  '**Intent:** Ensure only one instance of a class exists.',
  '**Used in:** Logger, configuration manager, connection pool',
  '',
  TRI + 'java',
  'public class Logger {',
  '  private static volatile Logger instance;',
  '  private Logger() {}',
  '  ',
  '  public static Logger getInstance() {',
  '    if (instance == null) {',
  '      synchronized (Logger.class) {',
  '        if (instance == null) instance = new Logger();',
  '      }',
  '    }',
  '    return instance;',
  '  }',
  '}',
  TRI,
  '',
  '### Factory Method',
  '**Intent:** Let subclasses decide which class to instantiate.',
  '',
  TRI + 'java',
  'public abstract class PaymentProcessor {',
  '  public abstract Payment createPayment(double amount);',
  '  ',
  '  public void process(double amount) {',
  '    Payment p = createPayment(amount);',
  '    p.validate(); p.charge(); p.sendReceipt();',
  '  }',
  '}',
  TRI,
  '',
  '### Builder',
  '**Intent:** Construct complex objects step by step.',
  '',
  TRI + 'java',
  'HttpRequest request = new HttpRequest.Builder("GET", "https://api.example.com")',
  '  .header("Authorization", "Bearer token123")',
  '  .timeout(Duration.ofSeconds(30))',
  '  .retry(3)',
  '  .build();',
  TRI,
  '',
  '---',
  '',
  '## Structural Patterns',
  '',
  '### Decorator',
  '**Intent:** Attach additional responsibilities to an object dynamically.',
  '',
  TRI + 'java',
  'Coffee coffee = new SimpleCoffee();',
  'coffee = new MilkDecorator(coffee);   // adds milk',
  'coffee = new SugarDecorator(coffee);  // adds sugar',
  'System.out.println(coffee.cost());    // $1.50',
  TRI,
  '',
  '### Facade',
  '**Intent:** Provide a simplified interface to a complex subsystem.',
  '',
  'Example: ' + CB + 'OrderService.placeOrder()' + CB + ' internally calls inventory, payment, shipping, and notification services.',
  '',
  '### Composite',
  '**Intent:** Treat individual objects and compositions uniformly.',
  '',
  'Example: File system (files and folders), UI component trees.',
  '',
  '---',
  '',
  '## Behavioral Patterns',
  '',
  '### Observer',
  '**Intent:** Define a one-to-many dependency so all dependents are notified when one object changes.',
  '',
  TRI + 'java',
  'public class StockMarket {',
  '  private Map<String, List<StockObserver>> observers = new HashMap<>();',
  '  ',
  '  public void subscribe(String symbol, StockObserver observer) {',
  '    observers.computeIfAbsent(symbol, k -> new ArrayList<>()).add(observer);',
  '  }',
  '  ',
  '  public void updatePrice(String symbol, double price) {',
  '    observers.getOrDefault(symbol, List.of()).forEach(o -> o.onPriceChange(symbol, price));',
  '  }',
  '}',
  TRI,
  '',
  '### Command',
  '**Intent:** Encapsulate a request as an object - enables undo/redo.',
  '',
  '### State',
  '**Intent:** Allow an object to alter its behavior when its internal state changes.',
  '',
  'Real-world: ATM, vending machine, order state machine.',
  '',
  '### Chain of Responsibility',
  '**Intent:** Pass a request through a chain of handlers.',
  '',
  'Real-world: HTTP middleware, authentication pipelines.',
  '',
  '---',
  '',
  '## Pattern Recognition Cheat Sheet',
  '',
  '| Problem Statement | Pattern |',
  '|---|---|',
  '| "Only one instance should exist" | Singleton |',
  '| "Create objects based on type/config" | Factory Method |',
  '| "Object has too many constructor params" | Builder |',
  '| "Add behavior without subclassing" | Decorator |',
  '| "Simplify a complex subsystem" | Facade |',
  '| "Notify many objects when one changes" | Observer |',
  '| "Switch algorithms at runtime" | Strategy |',
  '| "Support undo/redo" | Command |',
  '| "Vary behavior based on internal state" | State |',
  '| "Pass requests through a pipeline" | Chain of Responsibility |',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'Master the top 9 patterns (Singleton, Factory, Observer, Strategy, Decorator, Command, Template Method, Composite, Facade) for interviews. Use [LLDCanvas\'s pattern templates](/features/editor) to practice, and apply them through [real LLD problems](/features/interview-questions).',
].join(NL)

// ─── Blog 7 ──────────────────────────────────────────────────────────────────
const blog7Content = [
  '## Why OOP Fundamentals Matter',
  '',
  'Object-oriented programming remains the dominant paradigm for designing business software. Every LLD interview, every design review, and every "make this code better" conversation assumes solid OOP foundations.',
  '',
  '---',
  '',
  '## The Four Pillars of OOP',
  '',
  '### 1. Encapsulation',
  '',
  '**Definition:** Bundle related data and behavior into a single unit (class), and restrict direct access to internal state.',
  '',
  TRI + 'java',
  '// Without encapsulation',
  'public class BankAccount {',
  '  public double balance;  // Direct access = no validation',
  '}',
  'account.balance = -1000;  // Allowed! This is wrong.',
  '',
  '// With encapsulation',
  'public class BankAccount {',
  '  private double balance;',
  '  public void deposit(double amount) {',
  '    if (amount <= 0) throw new IllegalArgumentException("Amount must be positive");',
  '    balance += amount;',
  '  }',
  '  public double getBalance() { return balance; }',
  '}',
  TRI,
  '',
  '### 2. Abstraction',
  '',
  '**Definition:** Expose only the essential features, hiding implementation details.',
  '',
  TRI + 'java',
  'public interface PaymentGateway {',
  '  boolean processPayment(double amount, String currency);',
  '  PaymentStatus getStatus(String transactionId);',
  '}',
  '',
  '// Client code uses the abstraction - no knowledge of Razorpay vs Stripe',
  'public class CheckoutService {',
  '  private final PaymentGateway gateway;',
  '  public void checkout(Cart cart) { gateway.processPayment(cart.getTotal(), "INR"); }',
  '}',
  TRI,
  '',
  '### 3. Inheritance',
  '',
  '**Definition:** A mechanism where a child class acquires properties and behaviors of a parent class.',
  '',
  '**When to use:** "is-a" relationships. A Dog is an Animal. A SavingsAccount is a BankAccount.',
  '',
  '**The danger:** Deep inheritance hierarchies create tight coupling. Prefer composition.',
  '',
  '### 4. Polymorphism',
  '',
  '**Definition:** The ability for objects of different types to be treated as instances of the same type.',
  '',
  TRI + 'java',
  'Animal[] animals = { new Dog(), new Cat(), new Bird() };',
  'for (Animal a : animals) {',
  '  a.speak();  // Dog: "Woof!", Cat: "Meow!", Bird: "Tweet!"',
  '}',
  TRI,
  '',
  '---',
  '',
  '## Composition vs Inheritance',
  '',
  '**The Problem:** Deep inheritance becomes brittle. Java does not allow multiple inheritance.',
  '',
  TRI + 'java',
  '// Impossible in Java:',
  'class Amphibious extends LandVehicle, WaterVehicle { ... }  // Error!',
  '',
  '// Composition solution:',
  'class AmphibiousVehicle implements Driveable, Sailable {',
  '  private DriveEngine driveEngine = new DriveEngine();',
  '  private SailEngine  sailEngine  = new SailEngine();',
  '  ',
  '  public void drive() { driveEngine.drive(); }',
  '  public void sail()  { sailEngine.sail();   }',
  '}',
  TRI,
  '',
  '**Rule of thumb:** "Favor composition over inheritance" (GoF, Item 16 in Effective Java).',
  '',
  '---',
  '',
  '## Interfaces vs Abstract Classes',
  '',
  '| Feature | Interface | Abstract Class |',
  '|---------|-----------|----------------|',
  '| Multiple inheritance | Yes | No |',
  '| Constructor | No | Yes |',
  '| Fields | Only static final | Any type |',
  '| Method bodies | Default methods only | Yes |',
  '| Use when | Defining a contract | Partial implementation with shared state |',
  '',
  '---',
  '',
  '## Common OOP Interview Questions',
  '',
  '**Q: What is the difference between method overloading and overriding?**',
  '',
  'Overloading = compile-time polymorphism. Same method name, different parameters, same class.',
  'Overriding = runtime polymorphism. Subclass re-implements parent method. Resolved at runtime.',
  '',
  '**Q: Can a constructor be overridden?**',
  '',
  'No. Constructors are not inherited by subclasses.',
  '',
  '**Q: What is the diamond problem?**',
  '',
  'Ambiguity when a class inherits from two classes with the same method. Java avoids it by disallowing multiple class inheritance. Use interfaces + composition instead.',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'OOP mastery is the foundation of software engineering. Master encapsulation, abstraction, inheritance, and polymorphism. Understand composition vs inheritance deeply. Then apply them with [real LLD problems](/features/interview-questions).',
].join(NL)

// ─── Blog 8 ──────────────────────────────────────────────────────────────────
const blog8Content = [
  '## The FAANG System Design Landscape',
  '',
  'System design interviews vary significantly across companies - not just in difficulty, but in what they emphasize and how they score candidates.',
  '',
  '> **Practice with a timer:** Use [LLDCanvas\'s Interview Mode](/features/interview-mode) to simulate real conditions.',
  '',
  '---',
  '',
  '## Universal Scoring Rubric',
  '',
  '| Dimension | What They Evaluate |',
  '|-----------|-------------------|',
  '| **Requirements** | Did you ask the right clarifying questions? |',
  '| **Architecture** | Is the overall design sound? |',
  '| **Deep Dives** | Can you go deep on critical components? |',
  '| **Scale** | Does the design handle the stated scale? |',
  '| **Trade-offs** | Can you reason about pros/cons? |',
  '| **Communication** | Clear, structured, confident explanation? |',
  '',
  '---',
  '',
  '## Google: What They Value',
  '',
  '- Correct scalability intuition (planetary scale)',
  '- Knowledge of distributed systems (Spanner, Bigtable, Chubby)',
  '- Clean, minimal designs - no over-engineering',
  '- Awareness of consistency models, consensus (Paxos/Raft)',
  '',
  '**Tips:** Mention specific scale numbers, discuss monitoring and SLO compliance, code may be asked at L5+.',
  '',
  '**Common questions:** Design Google Search, Google Drive, YouTube, Google Maps.',
  '',
  '---',
  '',
  '## Meta (Facebook): What They Value',
  '',
  '- Social graph challenges',
  '- News Feed architecture (fan-out for celebrities vs regular users)',
  '- Real-time messaging and notification systems',
  '',
  '**Tips:** Know the celebrity problem and hybrid fan-out approach. Privacy is important.',
  '',
  '**Common questions:** Design Facebook News Feed, Instagram, WhatsApp, Messenger.',
  '',
  '---',
  '',
  '## Amazon: What They Value',
  '',
  '- Leadership Principles integration',
  '- High availability design (AWS-grade reliability)',
  '- Cost-efficiency and customer impact framing',
  '',
  '**Tips:** Frame decisions in terms of customer impact. Discuss failure modes explicitly. "Two-pizza team" principle.',
  '',
  '**Common questions:** Design Amazon.com product catalog, inventory management, ride-sharing for AWS Transport.',
  '',
  '---',
  '',
  '## Apple: What They Value',
  '',
  '- Privacy-first design',
  '- Hardware-software integration',
  '- Offline-first experiences',
  '',
  '**Tips:** Always consider on-device vs cloud processing. Discuss end-to-end encryption.',
  '',
  '**Common questions:** Design iCloud sync, Apple Pay backend, Siri.',
  '',
  '---',
  '',
  '## Netflix: What They Value',
  '',
  '- Video streaming infrastructure (ABR, HLS, DASH)',
  '- Chaos engineering mindset (assume failures, design for resilience)',
  '- Microservices and service mesh',
  '',
  '**Tips:** Know the video pipeline (upload -> transcode -> CDN). Discuss circuit breakers, bulkheads.',
  '',
  '**Common questions:** Design Netflix streaming, recommendation engine, Chaos Monkey infrastructure.',
  '',
  '---',
  '',
  '## Universal Strategies',
  '',
  '### During the Interview',
  '',
  '1. **Communicate constantly.** Do not silently draw. Talk through every decision.',
  '2. **Drive the conversation.** Choose which components to deep-dive into.',
  '3. **Name the trade-offs explicitly.**',
  '4. **Admit what you do not know.** Honesty earns respect.',
  '',
  '### The 5 Questions FAANG Always Asks',
  '',
  '1. "How would you handle [failure scenario]?"',
  '2. "How does this scale to 10x the traffic?"',
  '3. "What would you monitor?"',
  '4. "What trade-off did you make here?"',
  '5. "How would you roll this out?"',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'FAANG system design interviews are learnable. Each company has specific emphases, but the universal foundation applies everywhere: requirements clarification, clean architecture, scale reasoning, and trade-off discussion.',
  '',
  'Study the company\'s engineering blog, practice with [LLDCanvas\'s Interview Mode](/features/interview-mode), and develop the habit of thinking out loud as you design.',
].join(NL)

// ─── Blog 9 ──────────────────────────────────────────────────────────────────
const blog9Content = [
  '## Why Distributed Systems Knowledge Matters',
  '',
  'Modern software runs on distributed systems. Your microservices, databases, message queues, and caches all make trade-offs grounded in distributed systems theory.',
  '',
  '---',
  '',
  '## CAP Theorem',
  '',
  '**Statement:** A distributed data store can provide at most 2 of these 3 guarantees:',
  '',
  '- **C**onsistency: Every read receives the most recent write',
  '- **A**vailability: Every request receives a (non-error) response',
  '- **P**artition Tolerance: System continues despite network partitions',
  '',
  '**The key insight:** Network partitions are unavoidable. The real choice is between Consistency and Availability during a partition.',
  '',
  '### CP Systems',
  'Choose consistency over availability. May reject requests during partitions.',
  '**Examples:** HBase, ZooKeeper, etcd',
  '**Use when:** Data correctness is critical (financial transactions, inventory)',
  '',
  '### AP Systems',
  'Choose availability over consistency. May return stale data.',
  '**Examples:** Cassandra, DynamoDB, CouchDB',
  '**Use when:** System must always respond, eventual consistency acceptable',
  '',
  '---',
  '',
  '## Consistency Models',
  '',
  '| Model | Description | Examples |',
  '|-------|-------------|---------|',
  '| **Strong (Linearizability)** | Every read sees the most recent write | Spanner, ZooKeeper |',
  '| **Sequential** | Operations appear in a global sequential order | Many distributed DBs |',
  '| **Causal** | Respects cause-and-effect relationships | Some Cassandra modes |',
  '| **Eventual** | Replicas eventually converge if no new updates | Cassandra default, DNS |',
  '',
  '---',
  '',
  '## Consensus Algorithms',
  '',
  '### Raft',
  '',
  'Raft breaks consensus into three sub-problems:',
  '1. **Leader election**: Nodes elect one leader at a time per "term"',
  '2. **Log replication**: Leader accepts entries, replicates to followers',
  '3. **Safety**: Only one leader per term; committed entries never lost',
  '',
  '**Used in:** etcd (Kubernetes), CockroachDB, TiKV, Consul',
  '',
  '---',
  '',
  '## Distributed Transactions',
  '',
  '### The Problem',
  '',
  'A single business operation spans multiple services:',
  '',
  TRI,
  'PlaceOrder() ->',
  '  1. Deduct from Inventory Service',
  '  2. Create Payment in Payment Service',
  '  3. Create Shipping in Fulfillment Service',
  TRI,
  '',
  'If step 2 succeeds but step 3 fails, you have inconsistent state.',
  '',
  '### Saga Pattern',
  '',
  'Break the distributed transaction into a sequence of local transactions. Each step has a compensating transaction:',
  '',
  '1. Deduct inventory -> on failure: restore inventory',
  '2. Process payment -> on failure: refund payment',
  '3. Create shipment -> on failure: cancel shipment',
  '',
  '**Used in:** Uber, Amazon, most modern microservices architectures.',
  '',
  '---',
  '',
  '## Fault Tolerance Patterns',
  '',
  '### Circuit Breaker',
  '',
  '- **Closed state:** Requests flow normally. Error rate exceeds threshold -> open.',
  '- **Open state:** Requests fail fast. After timeout -> half-open.',
  '- **Half-open state:** Limited requests. If successful -> closed. If fails -> open.',
  '',
  '**Used in:** Netflix Resilience4j, Istio, service meshes.',
  '',
  '### Retry with Exponential Backoff and Jitter',
  '',
  TRI,
  'retry_delay = min(base_delay * 2^attempt + random_jitter, max_delay)',
  TRI,
  '',
  'Jitter prevents the "thundering herd" where all retries happen simultaneously.',
  '',
  '---',
  '',
  '## Data Replication Strategies',
  '',
  '### Single-Leader (Master-Slave)',
  '- One primary accepts writes; replicas sync asynchronously',
  '- Reads can be served from replicas (scales reads)',
  '- **Used in:** PostgreSQL (streaming replication), MySQL',
  '',
  '### Leaderless (Quorum-based)',
  '- Any node can accept a write',
  '- W + R > N ensures consistency (N = replicas, W = write confirms, R = read replicas queried)',
  '- **Used in:** Cassandra, DynamoDB, Riak',
  '',
  '---',
  '',
  '## Consistent Hashing',
  '',
  'Distributes data across nodes minimizing reshuffling when nodes are added/removed.',
  '',
  '- Map both keys and nodes onto a circular hash ring (0 to 2^32)',
  '- Each key is served by the first node clockwise from its position',
  '- Adding a node: only keys between new node and its predecessor need to move',
  '',
  '**Used in:** Redis Cluster, Cassandra, DynamoDB, CDN routing.',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'Distributed systems are complex, but the core concepts are finite and learnable. CAP theorem, consistency models, consensus (Raft), distributed transactions (Saga), and fault tolerance patterns form the foundation.',
  '',
  'Pair this knowledge with practice: try [system design problems on LLDCanvas](/features/interview-questions) that involve distributed components.',
].join(NL)

// ─── Blog 10 ─────────────────────────────────────────────────────────────────
const blog10Content = [
  '## The Question List That Actually Matters',
  '',
  'System design interviews feel overwhelming because the problem space seems infinite. But the same questions appear repeatedly, and the same architectural concepts appear across questions.',
  '',
  '> **Practice with a timer:** For each question, try a 45-minute timed session on [LLDCanvas](/features/interview-mode).',
  '',
  '---',
  '',
  '## Tier 1: Must Know',
  '',
  '### 1. Design Twitter / X',
  '',
  '**The core challenge:** News Feed generation at scale (500M users, read-heavy).',
  '',
  '**Fan-out strategy (the most important decision):**',
  '- Fan-out on write: Write tweet to all followers\' caches. Fast reads, expensive for high-follower accounts.',
  '- Fan-out on read: Fetch recent tweets from all followed accounts on request. Slow for users following thousands.',
  '- **Hybrid (Twitter\'s approach):** Fan-out on write for regular users; skip for celebrities. Mix on read.',
  '',
  '### 2. Design WhatsApp',
  '',
  '- WebSocket connections for persistent real-time communication',
  '- Message routing: sender -> WebSocket server -> routing service -> recipient\'s server',
  '- Online/offline: Heartbeat mechanism, presence in Redis',
  '- Storage: Cassandra (write-heavy, time-ordered, high volume)',
  '',
  '### 3. Design YouTube',
  '',
  '- **Upload pipeline:** Raw video -> Transcoding service -> Multiple resolutions -> CDN',
  '- HLS/DASH for adaptive bitrate streaming',
  '- Video metadata in PostgreSQL; files in S3/GCS',
  '',
  '### 4. Design Uber',
  '',
  '- Location updates every 4-5 seconds: Kafka ingestion, Redis Geo for nearby queries',
  '- Trip state machine: REQUESTED -> DRIVER_ASSIGNED -> DRIVER_ARRIVED -> IN_PROGRESS -> COMPLETED',
  '- Surge pricing: Supply/demand ratio per geohash cell, computed every minute',
  '',
  '### 5. Design Instagram',
  '',
  '- Same fan-out challenge as Twitter',
  '- Stories: 24h TTL in Redis, viewed-by tracking with Redis Set',
  '- Discovery/Explore: Offline collaborative filtering, updated daily',
  '',
  '---',
  '',
  '## Tier 2: Frequently Asked',
  '',
  '| # | System | Core Challenge | Key Decision |',
  '|---|--------|---------------|--------------|',
  '| 6 | URL Shortener | High read QPS | Base62(auto-increment ID) vs MD5 hash |',
  '| 7 | Rate Limiter | Distributed accuracy | Token bucket in Redis with Lua scripts |',
  '| 8 | Google Drive | File sync with conflicts | Chunked upload + deduplication by hash |',
  '| 9 | Notification Service | Fan-out reliability | Kafka -> channel-specific queues |',
  '| 10 | Search Autocomplete | Sub-100ms prefix match | In-memory trie, pre-computed from query logs |',
  '',
  '---',
  '',
  '## Tier 3: Good to Know',
  '',
  '- **Distributed Cache (Redis-like)**: Consistent hashing, eviction policies, replication',
  '- **Message Queue (Kafka-like)**: Partitioned log, consumer groups, offset tracking',
  '- **Web Crawler**: Bloom filter for deduplication, politeness (rate limiting per domain)',
  '- **Real-time Leaderboard**: Redis Sorted Sets (ZADD/ZRANK)',
  '- **API Gateway**: Request routing, auth, rate limiting, logging',
  '',
  '---',
  '',
  '## Common Patterns Across All Questions',
  '',
  '| Component | Questions It Appears In |',
  '|---|---|',
  '| CDN | YouTube, Instagram, Netflix, Google Drive |',
  '| Redis Cache | Almost all |',
  '| Kafka/Message Queue | Uber, Twitter, Notification, YouTube |',
  '| Cassandra | WhatsApp, Twitter, YouTube, Notification |',
  '| PostgreSQL | Instagram, URL Shortener, Google Drive |',
  '| Consistent Hashing | Distributed Cache, Rate Limiter, any sharded system |',
  '| WebSocket | WhatsApp, Uber, any real-time feature |',
  '| Fan-out Strategy | Twitter, Instagram, Facebook Feed |',
  '',
  '---',
  '',
  '## How to Structure Your Prep',
  '',
  '**Week 1:** Master Tier 1 questions (Twitter, WhatsApp, YouTube, Uber, Instagram). These cover 80% of patterns.',
  '',
  '**Week 2:** Cover Tier 2 questions. Each introduces one new important concept.',
  '',
  '**Week 3+:** Mock interview practice with a timer - [LLDCanvas\'s Interview Mode](/features/interview-mode).',
  '',
  'For each session:',
  '1. 5 min: requirements clarification',
  '2. 3 min: scale estimation',
  '3. 5 min: API design',
  '4. 20 min: high-level architecture',
  '5. 10 min: deep dive on 2 components',
  '6. 2 min: trade-offs and follow-ups',
  '',
  '---',
  '',
  '## Conclusion',
  '',
  'System design interviews are a learnable skill. The questions repeat, the building blocks are finite, and the reasoning framework is consistent.',
  '',
  'Start your preparation with [LLDCanvas\'s practice problems](/features/interview-questions), use [Interview Mode](/features/interview-mode) for timed sessions, and check out the [complete system design guide](/blog/system-design-interview-guide) for the foundational framework.',
].join(NL)

// ─── Blog metadata + content ──────────────────────────────────────────────────

const BLOGS = [
  {
    slug: 'system-design-interview-guide',
    title: 'Complete System Design Interview Guide 2025',
    subtitle: 'Everything you need to know to ace system design rounds at top tech companies',
    excerpt: 'A comprehensive, step-by-step guide to system design interviews: what interviewers look for, how to structure your answer, key topics to master, and a framework you can apply to any question.',
    category: 'System Design',
    tags: ['System Design', 'Interview Prep', 'FAANG', 'Software Engineering', 'Architecture'],
    isFeatured: true,
    relatedSlugs: ['lld-interview-roadmap', 'hld-vs-lld-explained', 'most-asked-system-design-questions', 'crack-system-design-faang'],
    seo: {
      metaTitle: 'Complete System Design Interview Guide 2025 | LLDCanvas',
      metaDescription: 'Master system design interviews with our complete 2025 guide. Covers HLD, LLD, scalability, databases, caching, load balancing, and a proven answer framework.',
      keywords: ['system design interview', 'system design guide', 'how to crack system design', 'HLD interview', 'LLD interview'],
    },
    faq: [
      { q: 'How long are system design interviews?', a: 'Typically 45-60 minutes. You spend ~5 min on clarification, 35-40 min designing, and 5 min on trade-offs.' },
      { q: 'Do I need to memorize architectures?', a: 'No. Interviewers care about your reasoning process. Understand the core building blocks deeply and you can derive any architecture.' },
      { q: 'What is the difference between HLD and LLD?', a: 'High-Level Design focuses on overall architecture - services, databases, APIs. Low-Level Design focuses on class structure, design patterns, and object-oriented modeling.' },
    ],
    content: blog1Content,
  },
  {
    slug: 'lld-interview-roadmap',
    title: 'Ultimate Low-Level Design (LLD) Interview Roadmap',
    subtitle: 'A complete learning path from OOP basics to expert-level design patterns',
    excerpt: 'The definitive roadmap for mastering Low-Level Design interviews. Covers OOP fundamentals, SOLID principles, all 23 GoF design patterns, and a systematic approach to solving any LLD problem.',
    category: 'Low-Level Design',
    tags: ['LLD', 'Low-Level Design', 'OOP', 'Design Patterns', 'Interview Roadmap', 'SOLID'],
    isFeatured: true,
    relatedSlugs: ['solid-principles-explained', 'design-patterns-guide', 'lld-interview-questions', 'oop-concepts-for-interviews'],
    seo: {
      metaTitle: 'Ultimate LLD Interview Roadmap 2025 | Low-Level Design Guide | LLDCanvas',
      metaDescription: 'Complete Low-Level Design (LLD) roadmap for software engineering interviews. Master OOP, SOLID principles, 23 design patterns, and a proven framework for solving LLD problems.',
      keywords: ['LLD interview', 'low level design roadmap', 'LLD preparation', 'machine coding round'],
    },
    faq: [
      { q: 'What is Low-Level Design (LLD)?', a: 'LLD focuses on the detailed design of a software component - class structure, interfaces, design patterns, and object relationships.' },
      { q: 'How long does it take to prepare for LLD interviews?', a: 'With focused daily practice of 1-2 hours, most engineers are interview-ready in 4-8 weeks.' },
    ],
    content: blog2Content,
  },
  {
    slug: 'hld-vs-lld-explained',
    title: 'HLD vs LLD: Key Differences Explained with Examples',
    subtitle: 'Understand when interviewers want a distributed architecture and when they want a class diagram',
    excerpt: 'High-Level Design and Low-Level Design are both asked in software engineering interviews, but they test completely different skills. This guide explains the differences, what each involves, and how to prepare for both.',
    category: 'System Design',
    tags: ['HLD', 'LLD', 'System Design', 'Software Architecture', 'Interview Prep'],
    isFeatured: false,
    relatedSlugs: ['system-design-interview-guide', 'lld-interview-roadmap', 'lld-interview-questions'],
    seo: {
      metaTitle: 'HLD vs LLD: Differences Explained with Examples | LLDCanvas',
      metaDescription: 'Understand the difference between High-Level Design (HLD) and Low-Level Design (LLD) in software engineering interviews. Examples, diagrams, and preparation tips.',
      keywords: ['HLD vs LLD', 'high level design vs low level design', 'system design interview types'],
    },
    faq: [
      { q: 'Which is harder, HLD or LLD?', a: 'They test different skills. HLD requires broad architectural knowledge. LLD requires deep OOP and design pattern knowledge.' },
      { q: 'Do all companies ask both HLD and LLD?', a: 'Not necessarily. Product companies typically ask both. Service-based companies often focus more on LLD.' },
    ],
    content: blog3Content,
  },
  {
    slug: 'lld-interview-questions',
    title: 'Top 25 LLD Interview Questions and Answers (2025)',
    subtitle: 'The most commonly asked Low-Level Design questions with detailed solutions and key design insights',
    excerpt: 'A curated list of the top 25 LLD interview questions asked at top tech companies, with detailed answers, design patterns used, and tips for each.',
    category: 'Low-Level Design',
    tags: ['LLD', 'Interview Questions', 'Low-Level Design', 'FAANG', 'Machine Coding'],
    isFeatured: false,
    relatedSlugs: ['lld-interview-roadmap', 'design-patterns-guide', 'solid-principles-explained'],
    seo: {
      metaTitle: 'Top 25 LLD Interview Questions and Answers 2025 | LLDCanvas',
      metaDescription: 'Top 25 Low-Level Design (LLD) interview questions asked at Google, Amazon, Flipkart, and Uber with detailed answers and design patterns used.',
      keywords: ['LLD interview questions', 'low level design questions', 'machine coding questions'],
    },
    faq: [
      { q: 'What are the most commonly asked LLD questions?', a: 'Parking Lot, LRU Cache, Elevator System, Vending Machine, Chess Game, Hotel Booking, and ATM Machine appear most frequently.' },
      { q: 'Should I write actual code or just class diagrams?', a: 'Most LLD rounds expect working code. Draw the class diagram first, then implement the core classes.' },
    ],
    content: blog4Content,
  },
  {
    slug: 'solid-principles-explained',
    title: 'SOLID Principles Explained with Real-World Examples',
    subtitle: 'The five principles every software engineer needs to master for clean, maintainable code',
    excerpt: 'A deep dive into all five SOLID principles with real-world examples, code comparisons, and practical tips for applying them in interviews and production code.',
    category: 'Object-Oriented Design',
    tags: ['SOLID', 'OOP', 'Software Design', 'Clean Code', 'Interview Prep'],
    isFeatured: false,
    relatedSlugs: ['lld-interview-roadmap', 'design-patterns-guide', 'oop-concepts-for-interviews'],
    seo: {
      metaTitle: 'SOLID Principles Explained with Examples 2025 | LLDCanvas',
      metaDescription: 'Master SOLID principles with real code examples and interview tips. Single Responsibility, Open/Closed, Liskov, Interface Segregation, Dependency Inversion.',
      keywords: ['SOLID principles', 'SOLID principles explained', 'single responsibility principle', 'dependency inversion principle'],
    },
    faq: [
      { q: 'Why are SOLID principles important in interviews?', a: 'SOLID principles are the foundation of every design pattern question and every code review conversation.' },
      { q: 'Which SOLID principle is violated most often?', a: 'Single Responsibility Principle - "God classes" that do everything are extremely common.' },
    ],
    content: blog5Content,
  },
  {
    slug: 'design-patterns-guide',
    title: 'Design Patterns Every Software Engineer Must Know',
    subtitle: 'A practical guide to the 23 Gang of Four patterns with real-world examples',
    excerpt: 'A comprehensive guide to the 23 Gang of Four design patterns - what they are, when to use them, real-world examples, and how they appear in software engineering interviews.',
    category: 'Design Patterns',
    tags: ['Design Patterns', 'Gang of Four', 'OOP', 'Software Engineering', 'GoF'],
    isFeatured: false,
    relatedSlugs: ['solid-principles-explained', 'lld-interview-roadmap', 'oop-concepts-for-interviews'],
    seo: {
      metaTitle: 'Design Patterns Every Software Engineer Must Know | LLDCanvas',
      metaDescription: 'Complete guide to the 23 Gang of Four design patterns with real-world examples, code samples, and interview applications.',
      keywords: ['design patterns', 'gang of four patterns', 'creational patterns', 'behavioral patterns'],
    },
    faq: [
      { q: 'How many design patterns are there?', a: 'The GoF book defines 23 patterns. These form the foundation; there are many more beyond GoF.' },
      { q: 'Which patterns are most asked in interviews?', a: 'Singleton, Factory, Observer, Strategy, Decorator, Command, Template Method, Composite, and Facade are asked most frequently.' },
    ],
    content: blog6Content,
  },
  {
    slug: 'oop-concepts-for-interviews',
    title: 'OOP Concepts Explained for Software Engineering Interviews',
    subtitle: 'Master object-oriented programming fundamentals that every interview tests',
    excerpt: 'A complete guide to OOP concepts for software engineering interviews: the 4 pillars, abstraction vs encapsulation, composition vs inheritance, polymorphism types, and common interview questions.',
    category: 'Object-Oriented Design',
    tags: ['OOP', 'Object-Oriented Programming', 'Interview Prep', 'Software Engineering'],
    isFeatured: false,
    relatedSlugs: ['solid-principles-explained', 'design-patterns-guide', 'lld-interview-roadmap'],
    seo: {
      metaTitle: 'OOP Concepts for Software Engineering Interviews | LLDCanvas',
      metaDescription: 'Master OOP concepts for interviews: the 4 pillars, encapsulation, inheritance, polymorphism, abstraction, and composition vs inheritance.',
      keywords: ['OOP concepts interview', 'object oriented programming interview', 'four pillars of OOP'],
    },
    faq: [
      { q: 'What are the 4 pillars of OOP?', a: 'Encapsulation, Abstraction, Inheritance, and Polymorphism.' },
      { q: 'When should I prefer composition over inheritance?', a: 'Prefer composition when the relationship is "has-a" rather than "is-a", or when you need runtime flexibility.' },
    ],
    content: blog7Content,
  },
  {
    slug: 'crack-system-design-faang',
    title: 'How to Crack System Design Interviews at FAANG Companies',
    subtitle: 'Insider strategies for Google, Meta, Amazon, Apple, and Netflix system design rounds',
    excerpt: 'A detailed guide on cracking system design interviews at top tech companies: what each company emphasizes, how to structure your answers, scoring rubrics, and specific tips for Google, Meta, Amazon, Apple, and Netflix.',
    category: 'System Design',
    tags: ['FAANG', 'System Design', 'Google', 'Amazon', 'Meta', 'Interview Prep'],
    isFeatured: false,
    relatedSlugs: ['system-design-interview-guide', 'hld-vs-lld-explained', 'most-asked-system-design-questions'],
    seo: {
      metaTitle: 'How to Crack System Design Interviews at FAANG | LLDCanvas',
      metaDescription: 'Insider guide to cracking system design interviews at Google, Meta, Amazon, Apple, and Netflix.',
      keywords: ['FAANG system design interview', 'Google system design', 'Amazon system design'],
    },
    faq: [
      { q: 'How is system design scored at FAANG?', a: 'Most use a rubric with dimensions like problem clarification, architecture correctness, scalability, reliability, and communication.' },
    ],
    content: blog8Content,
  },
  {
    slug: 'distributed-systems-concepts',
    title: 'Distributed Systems Concepts Every Software Engineer Should Know',
    subtitle: 'From CAP theorem to consensus algorithms - essential distributed systems knowledge for interviews',
    excerpt: 'A comprehensive guide to distributed systems fundamentals: CAP theorem, consistency models, consensus algorithms, distributed transactions, fault tolerance, and how these apply in system design interviews.',
    category: 'System Design',
    tags: ['Distributed Systems', 'CAP Theorem', 'Consistency', 'System Design', 'Fault Tolerance'],
    isFeatured: false,
    relatedSlugs: ['system-design-interview-guide', 'crack-system-design-faang', 'most-asked-system-design-questions'],
    seo: {
      metaTitle: 'Distributed Systems Concepts for Software Engineers | LLDCanvas',
      metaDescription: 'Master distributed systems fundamentals for system design interviews: CAP theorem, consistency models, Raft, distributed transactions, and fault tolerance.',
      keywords: ['distributed systems concepts', 'CAP theorem explained', 'consistency models', 'consensus algorithms'],
    },
    faq: [
      { q: 'What is the difference between consistency and availability in CAP?', a: 'Consistency means every read gets the most recent write. Availability means every request receives a response. In a partition, systems must choose which to sacrifice.' },
    ],
    content: blog9Content,
  },
  {
    slug: 'most-asked-system-design-questions',
    title: 'Most Asked System Design Questions at Top Tech Companies (2025)',
    subtitle: 'A curated list of the most frequently asked system design questions with key design insights',
    excerpt: 'The most frequently asked system design questions across top tech companies, with key entities, architecture highlights, critical design decisions, and what interviewers look for in each answer.',
    category: 'System Design',
    tags: ['System Design', 'Interview Questions', 'FAANG', 'HLD', 'Software Architecture'],
    isFeatured: false,
    relatedSlugs: ['system-design-interview-guide', 'crack-system-design-faang', 'hld-vs-lld-explained'],
    seo: {
      metaTitle: 'Most Asked System Design Interview Questions 2025 | LLDCanvas',
      metaDescription: 'Top system design questions at Google, Meta, Amazon, Uber, and Netflix with key architecture insights and what interviewers look for.',
      keywords: ['most asked system design questions', 'top system design interview questions', 'system design questions 2025'],
    },
    faq: [
      { q: 'How many system design questions should I prepare?', a: 'Prepare 15-20 questions deeply. Most problems share common patterns (caching, queues, databases, CDNs).' },
    ],
    content: blog10Content,
  },
]

async function main() {
  await mongoose.connect(process.env.MONGODB_URI!)
  console.log('Connected to MongoDB')

  let added = 0
  let skipped = 0

  for (const b of BLOGS) {
    const existing = await Blog.findOne({ slug: b.slug })
    if (existing) {
      console.log(`  SKIP  ${b.slug}`)
      skipped++
      continue
    }

    const rt = wpm(b.content)
    await Blog.create({
      ...b,
      author: AUTHOR,
      status:      'published',
      publishedAt: new Date(),
      readingTime: rt,
    })
    console.log(`  ADD   ${b.slug}  (${rt} min read)`)
    added++
  }

  console.log(`\nDone — added ${added}, skipped ${skipped}`)
  await mongoose.disconnect()
}

main().catch(err => { console.error(err); process.exit(1) })
