/**
 * Adds 53 more practice problems (16 easy, 20 medium, 17 hard) to bring the
 * total library past 100. Additive/upsert by slug — safe to re-run.
 *
 * Run with:  npx ts-node -r dotenv/config src/scripts/seed-problems-batch2.ts
 */
import 'dotenv/config'
import mongoose from 'mongoose'
import { Problem } from '../models/problem.model'

const PROBLEMS = [
  // ─── EASY ─────────────────────────────────────────────────────────────────
  {
    slug: 'restaurant-table-reservation',
    title: 'Restaurant Table Reservation System',
    difficulty: 'easy',
    category: 'Hospitality',
    description: 'Design a system that manages restaurant table reservations, walk-ins, and table assignment based on party size.',
    companies: ['OpenTable', 'Resy', 'Zomato'],
    tags: ['OOP', 'Scheduling'],
    order: 14,
    functionalRequirements: [
      'Book a table for a given date, time, and party size',
      'Support tables of different capacities (2, 4, 6, 8 seats)',
      'Handle walk-in customers with a waitlist',
      'Cancel or modify an existing reservation',
      'Assign the smallest table that fits the party size',
      'Notify staff when a reserved time slot is approaching',
    ],
    nonFunctionalRequirements: [
      'Support up to 200 tables per restaurant',
      'Reservation confirmation within 1 second',
      'No double-booking of the same table/time slot',
    ],
    hints: [
      'Core entities: Restaurant, Table, Reservation, Customer, Waitlist. Each Table has a capacity and a list of booked TimeSlots. Use an interval data structure (sorted list of [start,end) ranges) per table to check availability in O(log n).',
      'Table assignment: sort available tables by capacity ascending and pick the first that fits the party size (best-fit), so larger tables stay free for bigger parties.',
      'Use the Observer pattern for waitlist notifications — when a table frees up or a reservation is cancelled, notify the next matching party on the Waitlist queue.',
    ],
  },
  {
    slug: 'basic-calculator',
    title: 'Basic Calculator with Undo/Redo',
    difficulty: 'easy',
    category: 'Productivity',
    description: 'Design a calculator supporting basic arithmetic operations with full undo/redo history of operations.',
    companies: ['Google', 'Microsoft'],
    tags: ['OOP', 'Command Pattern'],
    order: 15,
    functionalRequirements: [
      'Support add, subtract, multiply, divide operations',
      'Maintain a running result and operation history',
      'Undo the last operation, restoring the previous result',
      'Redo an undone operation',
      'Clear the calculator state',
      'Support chained operations (e.g. 5 + 3 * 2)',
    ],
    nonFunctionalRequirements: [
      'Undo/redo should be O(1) per operation',
      'History should support at least 100 steps',
    ],
    hints: [
      'Use the Command pattern: each operation (Add, Subtract, Multiply, Divide) is a Command object with execute() and undo() methods, storing the operand and prior result.',
      'Maintain two stacks: an undoStack of executed Commands and a redoStack. Undo pops from undoStack, calls command.undo(), pushes to redoStack. Redo does the reverse.',
      'Guard divide-by-zero and validate operand types before constructing a Command — invalid commands should never be pushed onto the history stacks.',
    ],
  },
  {
    slug: 'in-memory-file-system',
    title: 'In-Memory File System',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design an in-memory file system supporting directories, files, and standard operations like create, read, delete, and move.',
    companies: ['Google', 'Amazon', 'Microsoft'],
    tags: ['OOP', 'Composite Pattern', 'Tree'],
    order: 16,
    functionalRequirements: [
      'Create, read, update, and delete files',
      'Create and delete directories (recursively)',
      'List contents of a directory',
      'Move/rename a file or directory',
      'Compute total size of a directory (recursive)',
      'Support absolute path resolution (e.g. /a/b/c.txt)',
    ],
    nonFunctionalRequirements: [
      'Path resolution should be O(depth) not O(total nodes)',
      'Support at least 100,000 files across the tree',
    ],
    hints: [
      'Use the Composite pattern: an abstract FileSystemNode with File and Directory subclasses. Directory holds a Map<name, FileSystemNode> of children, so both files and folders can be treated uniformly.',
      'Path resolution: split the path by "/" and walk down the tree one segment at a time from the root Directory, following child Map lookups — O(depth), not a full tree scan.',
      'Directory size is computed recursively: a File returns its own size; a Directory returns the sum of getSize() over all children. Cache the computed size and invalidate it up the parent chain on any mutation for O(1) repeated reads.',
    ],
  },
  {
    slug: 'cron-job-scheduler',
    title: 'Job Scheduler (Cron-like Task Runner)',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design a task scheduler that runs jobs at fixed intervals or specific times, similar to a basic cron system.',
    companies: ['Google', 'Amazon'],
    tags: ['OOP', 'Scheduling', 'Priority Queue'],
    order: 17,
    functionalRequirements: [
      'Schedule a job to run once at a specific time',
      'Schedule a recurring job at a fixed interval',
      'Cancel a scheduled job before it runs',
      'Support job priority for execution ordering',
      'Retry a failed job up to N times',
      'List all pending and completed jobs',
    ],
    nonFunctionalRequirements: [
      'Support thousands of scheduled jobs concurrently',
      'Job dispatch latency within 1 second of scheduled time',
    ],
    hints: [
      'Core entities: Job, Schedule (one-time or recurring interval), JobQueue, Worker. Use a min-heap (priority queue) keyed by nextRunTime so the scheduler always peeks the soonest job in O(log n).',
      'A single scheduler thread polls the heap: if the top job\'s nextRunTime <= now, pop it, dispatch to a worker pool, and if recurring, recompute nextRunTime and re-insert into the heap.',
      'For retries, wrap job execution in a try/catch — on failure, increment an attempt counter and re-schedule with exponential backoff (nextRunTime = now + base * 2^attempt) up to the max retry count.',
    ],
  },
  {
    slug: 'quiz-trivia-engine',
    title: 'Quiz / Trivia Game Engine',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a quiz engine that manages questions, scoring, and timed rounds for a trivia game.',
    companies: ['Kahoot', 'Google'],
    tags: ['OOP', 'State Machine'],
    order: 18,
    functionalRequirements: [
      'Load a set of questions with multiple-choice answers',
      'Track a per-player score across rounds',
      'Support a per-question time limit',
      'Award bonus points for faster correct answers',
      'Show the leaderboard after each round',
      'Support single-player and multiplayer modes',
    ],
    nonFunctionalRequirements: [
      'Support up to 100 concurrent players per game session',
      'Score updates should reflect within 500ms of an answer',
    ],
    hints: [
      'Core entities: Quiz, Question, Choice, Player, Round, Leaderboard. Question stores the correct choice index and a point value; Round tracks a start timestamp and time limit.',
      'Model the game flow as a state machine: WaitingForPlayers → QuestionActive → Reveal → Leaderboard → NextQuestion/GameOver. Each state controls what actions are valid.',
      'Bonus scoring: points = basePoints * max(0, 1 - (answerTime / timeLimit)) rounded to an integer, so faster correct answers score higher, capped at basePoints.',
    ],
  },
  {
    slug: 'digital-wallet',
    title: 'Digital Wallet (Single Currency)',
    difficulty: 'easy',
    category: 'Fintech',
    description: 'Design a digital wallet system supporting deposits, withdrawals, and balance tracking with a full transaction history.',
    companies: ['PayPal', 'Paytm', 'Google Pay'],
    tags: ['OOP', 'Ledger'],
    order: 19,
    functionalRequirements: [
      'Create a wallet for a user with zero starting balance',
      'Deposit funds into a wallet',
      'Withdraw funds if sufficient balance exists',
      'View current balance',
      'View a chronological transaction history',
      'Prevent overdraft (balance cannot go negative)',
    ],
    nonFunctionalRequirements: [
      'All balance updates must be atomic — no lost updates under concurrency',
      'Transaction history must be immutable once written',
    ],
    hints: [
      'Core entities: Wallet, User, Transaction (type: DEPOSIT/WITHDRAW, amount, timestamp, resultingBalance). Never mutate balance directly from arbitrary code paths — only through a single applyTransaction() method.',
      'Treat the wallet as an append-only ledger: balance is derived as the sum of all transaction deltas, or cached and updated atomically alongside each new Transaction insert in the same operation.',
      'Use a per-wallet lock (or a database row-level lock / optimistic versioning with a version column) around the read-balance-then-write sequence to prevent two concurrent withdrawals from both passing the sufficient-balance check.',
    ],
  },
  {
    slug: 'meeting-room-booking',
    title: 'Meeting Room Booking System',
    difficulty: 'easy',
    category: 'Productivity',
    description: 'Design a system that lets employees book meeting rooms, checking for conflicts across a shared calendar.',
    companies: ['Microsoft', 'Google', 'Atlassian'],
    tags: ['OOP', 'Interval Scheduling'],
    order: 20,
    functionalRequirements: [
      'List available rooms for a given time range and capacity',
      'Book a room for a specific time slot',
      'Prevent overlapping bookings for the same room',
      'Cancel an existing booking',
      'Support recurring bookings (e.g. every Monday 10-11am)',
      'Show a room\'s full schedule for a given day',
    ],
    nonFunctionalRequirements: [
      'Conflict check should complete in under 100ms',
      'Support hundreds of rooms across multiple buildings',
    ],
    hints: [
      'Core entities: Room, Booking (startTime, endTime, organizer), Building. Store each room\'s bookings in a sorted structure (e.g. a balanced BST or sorted list by startTime) for efficient overlap checks.',
      'Overlap check between a new booking [s1,e1) and existing [s2,e2): they conflict if s1 < e2 AND s2 < e1. Binary-search the sorted bookings to only compare against nearby entries instead of scanning all bookings.',
      'For recurring bookings, expand the recurrence rule (e.g. weekly for N occurrences) into individual Booking instances upfront and validate each one for conflicts, rather than special-casing recurrence in the conflict checker.',
    ],
  },
  {
    slug: 'contact-management',
    title: 'Contact Management System (Address Book)',
    difficulty: 'easy',
    category: 'Productivity',
    description: 'Design an address book application that stores contacts, supports search, and groups contacts into categories.',
    companies: ['Apple', 'Google', 'Microsoft'],
    tags: ['OOP', 'Search'],
    order: 21,
    functionalRequirements: [
      'Add, edit, and delete a contact (name, phone, email, address)',
      'Search contacts by name, phone, or email (partial match)',
      'Group contacts into labeled categories (e.g. Family, Work)',
      'Merge duplicate contacts',
      'Favorite/star important contacts',
      'Export contacts to a shareable format',
    ],
    nonFunctionalRequirements: [
      'Search should return results in under 200ms for 100,000 contacts',
      'Support offline-first usage with later sync',
    ],
    hints: [
      'Core entities: Contact, ContactGroup, User. A Contact can belong to multiple ContactGroups (many-to-many), modeled via a join collection or an array of group IDs on the contact.',
      'For fast partial-match search, build an in-memory trie or inverted index on name tokens (and normalized phone/email), rather than scanning every contact on each keystroke.',
      'Duplicate merge: detect candidates via normalized phone number or email equality, then union their field values (prefer non-empty fields, keep both phone numbers as a list) into a single surviving Contact record.',
    ],
  },
  {
    slug: 'ludo-board-game',
    title: 'Ludo Board Game',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design the classic Ludo board game supporting 2-4 players, dice rolls, and token movement with capture rules.',
    companies: ['Zynga', 'Ludo King'],
    tags: ['OOP', 'State Machine'],
    order: 22,
    functionalRequirements: [
      'Support 2 to 4 players, each with 4 tokens',
      'Roll a dice and move a token by that many steps',
      'Capture an opponent\'s token landing on the same non-safe cell',
      'Require a 6 to move a token out of the home base',
      'Move a token into the home column after a full lap',
      'Determine the winner when all 4 of a player\'s tokens reach home',
    ],
    nonFunctionalRequirements: [
      'Board state updates should be validated server-side to prevent cheating',
      'Support turn timeouts (auto-skip after 30s of inactivity)',
    ],
    hints: [
      'Core entities: Board, Player, Token, Cell, Dice. Represent the board path as a fixed-size array of Cells per color, with special SafeCell and HomeEntry markers.',
      'Model turn flow as a state machine: RollDice → (if 6) MoveOrRelease → CheckCapture → (if 6 or captured) ExtraTurn else NextPlayer. Encapsulate this in a TurnManager rather than scattering logic across the UI.',
      'Capture logic: when a token lands on a cell, check all opponent tokens on that cell; if the cell isn\'t marked safe, send captured tokens back to their home base and reset their position to -1 (not yet released).',
    ],
  },
  {
    slug: 'memory-matching-game',
    title: 'Memory Matching Card Game',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design a memory card-matching game where players flip pairs of cards trying to find matches.',
    companies: ['Zynga'],
    tags: ['OOP', 'State Machine'],
    order: 23,
    functionalRequirements: [
      'Generate a shuffled board of N pairs of cards (face down)',
      'Flip a card to reveal its face',
      'Check if two flipped cards match; if not, flip them back after a delay',
      'Remove matched pairs from play (or mark them solved)',
      'Track moves taken and elapsed time',
      'Support multiplayer turn-based mode where a match grants another turn',
    ],
    nonFunctionalRequirements: [
      'Board generation must guarantee a fair, uniformly random shuffle',
      'Support board sizes up to 100 cards',
    ],
    hints: [
      'Core entities: Board, Card (value, faceUp, matched), Player, GameSession. Generate pairs by duplicating N distinct values, then apply a Fisher-Yates shuffle for uniform randomness.',
      'Model as a state machine: Idle → OneCardFlipped → TwoCardsFlipped → (Match: MarkSolved, ExtraTurn) or (NoMatch: FlipBackAfterDelay, NextPlayer). Only allow flipping when in Idle or OneCardFlipped state to prevent flipping a 3rd card mid-check.',
      'For multiplayer, track score per player and only advance turn on a non-match, letting a player continue on a successful match — this mirrors the real-world rule.',
    ],
  },
  {
    slug: 'cafeteria-checkout-billing',
    title: 'Cafeteria Self-Checkout Billing System',
    difficulty: 'easy',
    category: 'Retail',
    description: 'Design a self-checkout billing system for a cafeteria that scans items, applies discounts, and generates a bill.',
    companies: ['Amazon', 'Walmart'],
    tags: ['OOP', 'Strategy Pattern'],
    order: 24,
    functionalRequirements: [
      'Scan/add items to a cart with quantity',
      'Look up item price from a catalog',
      'Apply discounts (percentage-off, buy-one-get-one, flat coupon)',
      'Calculate tax based on item category',
      'Generate an itemized bill/receipt',
      'Support multiple payment methods (cash, card, wallet)',
    ],
    nonFunctionalRequirements: [
      'Bill calculation should complete in under 200ms',
      'Handle at least 50 items per cart',
    ],
    hints: [
      'Core entities: Item, Cart, CartLine (item + quantity), Discount, Bill, Payment. Keep pricing/catalog lookup separate from the Cart so prices can change without mutating in-progress carts.',
      'Use the Strategy pattern for discounts: a DiscountStrategy interface with apply(cart) implementations for PercentOff, BOGO, and FlatCoupon — the Cart applies a list of active strategies in a defined order.',
      'Use the Strategy pattern again for Payment (CashPayment, CardPayment, WalletPayment implementing a common process(amount) method), so adding a new payment method doesn\'t touch the billing logic.',
    ],
  },
  {
    slug: 'stopwatch-lap-timer',
    title: 'Stopwatch & Lap Timer',
    difficulty: 'easy',
    category: 'Productivity',
    description: 'Design a stopwatch application supporting start, pause, resume, reset, and lap recording.',
    companies: ['Apple', 'Google'],
    tags: ['OOP', 'State Machine'],
    order: 25,
    functionalRequirements: [
      'Start the stopwatch from zero',
      'Pause and resume without losing elapsed time',
      'Record a lap time while running',
      'List all recorded laps with split and cumulative time',
      'Reset the stopwatch to zero',
      'Identify the fastest and slowest lap',
    ],
    nonFunctionalRequirements: [
      'Elapsed time precision to the millisecond',
      'No drift over long-running sessions (hours)',
    ],
    hints: [
      'Core entities: Stopwatch (state: Idle/Running/Paused), Lap (splitTime, cumulativeTime). Store elapsed time as accumulatedTime + (now - lastStartTimestamp) while running, rather than incrementing a counter on a timer tick, to avoid drift.',
      'On pause, add (now - lastStartTimestamp) into accumulatedTime and clear lastStartTimestamp; on resume, set lastStartTimestamp = now again. This makes elapsed time always computable from just two numbers.',
      'Recording a lap simply snapshots the current elapsed time; splitTime = currentElapsed - previousLap.cumulativeTime. Fastest/slowest lap is a simple min/max scan over recorded splits.',
    ],
  },
  {
    slug: 'simple-lru-cache',
    title: 'Simple LRU Cache',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design an in-memory Least Recently Used (LRU) cache with O(1) get and put operations.',
    companies: ['Amazon', 'Google', 'Microsoft', 'Meta'],
    tags: ['Data Structures', 'HashMap', 'Linked List'],
    order: 26,
    functionalRequirements: [
      'get(key) returns the value if present, else -1/null',
      'put(key, value) inserts or updates a key',
      'Evict the least recently used item when capacity is exceeded',
      'Accessing a key (get or put) marks it as most recently used',
      'Support a configurable fixed capacity',
    ],
    nonFunctionalRequirements: [
      'Both get and put must run in O(1) average time',
      'Support capacities up to 1 million entries',
    ],
    hints: [
      'Combine a HashMap<key, Node> with a doubly linked list ordered by recency. The HashMap gives O(1) lookup of the Node; the linked list gives O(1) reordering (move-to-front) and O(1) eviction from the tail.',
      'On get(key): if present, unlink the Node from its current position and re-insert it at the head (most-recently-used end), then return its value.',
      'On put(key, value): if key exists, update value and move to head. If not and at capacity, remove the tail Node (least recently used) from both the list and the HashMap before inserting the new Node at the head.',
    ],
  },
  {
    slug: 'weather-station-observer',
    title: 'Weather Station Monitoring System',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design a weather station that reads sensor data and pushes updates to multiple displays in real time.',
    companies: ['Google', 'Microsoft'],
    tags: ['Observer Pattern', 'OOP'],
    order: 27,
    functionalRequirements: [
      'Collect temperature, humidity, and pressure readings',
      'Notify all registered displays whenever a new reading arrives',
      'Support adding/removing displays at runtime',
      'Support different display formats (current conditions, statistics, forecast)',
      'Compute running min/max/average for each metric',
    ],
    nonFunctionalRequirements: [
      'New displays should start receiving updates immediately upon registration',
      'Notification to all displays should complete in under 50ms',
    ],
    hints: [
      'This is the textbook Observer pattern: WeatherStation (Subject) maintains a list of Observer (Display) instances and calls notify() → each display\'s update(temp, humidity, pressure) whenever new sensor data arrives.',
      'Keep displays decoupled from the data source: a Display only implements an update() interface and doesn\'t know how readings are collected — the WeatherStation is the only thing that knows about sensors.',
      'For running statistics, maintain incrementally-updated min/max/sum/count in the StatisticsDisplay\'s own update() method rather than recomputing over full history each time — O(1) per reading.',
    ],
  },
  {
    slug: 'text-editor-undo-redo',
    title: 'Text Editor with Undo/Redo',
    difficulty: 'easy',
    category: 'Developer Tools',
    description: 'Design a simple text editor supporting insert, delete, and multi-level undo/redo of edits.',
    companies: ['Microsoft', 'Google'],
    tags: ['Command Pattern', 'OOP'],
    order: 28,
    functionalRequirements: [
      'Insert text at a given cursor position',
      'Delete a range of text',
      'Undo the most recent edit',
      'Redo an undone edit',
      'Support at least 100 levels of undo history',
      'Clear redo history when a new edit is made after an undo',
    ],
    nonFunctionalRequirements: [
      'Undo/redo should not require re-scanning the whole document',
      'Support documents up to 1 million characters',
    ],
    hints: [
      'Use the Command pattern: InsertCommand and DeleteCommand each store enough info to both execute() and undo() themselves — e.g. DeleteCommand stores the deleted text so undo() can re-insert it at the same position.',
      'Maintain an undoStack and redoStack of Commands. Undo pops from undoStack, calls undo(), pushes onto redoStack. Any NEW edit after an undo must clear redoStack — the classic branching-history rule.',
      'For large documents, back the text with a more efficient structure than a plain string (e.g. a rope or a gap buffer) so insert/delete at an arbitrary position is faster than O(n) string copying.',
    ],
  },
  {
    slug: 'battleship-game',
    title: 'Battleship Game',
    difficulty: 'easy',
    category: 'Gaming',
    description: 'Design the Battleship board game supporting ship placement, turn-based firing, and win detection.',
    companies: ['Zynga', 'Electronic Arts'],
    tags: ['OOP', 'State Machine'],
    order: 29,
    functionalRequirements: [
      'Place ships of varying sizes on a grid without overlap',
      'Fire at a coordinate on the opponent\'s board',
      'Report hit, miss, or sunk-ship results',
      'Track each player\'s remaining ships',
      'Alternate turns between two players',
      'Declare a winner when all of a player\'s ships are sunk',
    ],
    nonFunctionalRequirements: [
      'Ship placement validation should reject overlaps/out-of-bounds instantly',
      'Support a standard 10x10 grid with 5 ship types',
    ],
    hints: [
      'Core entities: Board (grid of Cells), Ship (list of occupied coordinates + hit tracking), Player. Each Ship tracks which of its cells have been hit; it\'s "sunk" when all cells are hit.',
      'Placement validation: for each proposed Ship position, check all its cells are in-bounds and not already occupied by another ship — use a Set<coordinate> per board for O(1) occupancy checks.',
      'Model turns as a simple two-state machine (Player1Turn ⇄ Player2Turn), only advancing after a valid fire() call, and check the win condition (all ships sunk) after each shot before switching turns.',
    ],
  },

  // ─── MEDIUM ───────────────────────────────────────────────────────────────
  {
    slug: 'airline-boarding-seat-assignment',
    title: 'Airline Boarding & Seat Assignment System',
    difficulty: 'medium',
    category: 'Travel',
    description: 'Design a system that manages flight seat maps, seat selection, boarding groups, and check-in.',
    companies: ['United Airlines', 'Amadeus', 'Sabre'],
    tags: ['OOP', 'State Machine'],
    order: 21,
    functionalRequirements: [
      'Display a seat map showing available/occupied/blocked seats',
      'Let a passenger select or auto-assign a seat by class',
      'Support seat classes: economy, premium, business, first',
      'Assign boarding groups based on class and check-in time',
      'Handle standby passengers and waitlist promotion',
      'Check in a passenger and issue a boarding pass',
    ],
    nonFunctionalRequirements: [
      'Seat selection must prevent double-booking under concurrency',
      'Support flights with up to 500 seats',
      'Boarding pass issuance within 1 second',
    ],
    hints: [
      'Core entities: Flight, SeatMap, Seat (class, status), Passenger, Booking, BoardingPass. SeatMap holds a 2D grid or a Map<seatNumber, Seat> for O(1) lookup by seat number.',
      'Prevent double-booking with an atomic compare-and-set on seat status: only transition AVAILABLE → RESERVED if the current status is still AVAILABLE (optimistic concurrency / DB row locking), retry auto-assignment on conflict.',
      'Boarding groups: assign each SeatClass a group number, then sort within a group by check-in timestamp for standby/waitlist promotion order. Model check-in state as a State Machine: NotCheckedIn → CheckedIn → Boarded.',
    ],
  },
  {
    slug: 'p2p-digital-wallet',
    title: 'Peer-to-Peer Digital Wallet System',
    difficulty: 'medium',
    category: 'Fintech',
    description: 'Design a P2P payment wallet supporting transfers between users, multiple funding sources, and transaction reconciliation.',
    companies: ['Venmo', 'Cash App', 'PayPal'],
    tags: ['OOP', 'Ledger', 'Concurrency'],
    order: 22,
    functionalRequirements: [
      'Link a bank account or card as a funding source',
      'Transfer money from one user\'s wallet to another',
      'Top up wallet balance from a linked funding source',
      'Withdraw wallet balance to a bank account',
      'View transaction history with running balance',
      'Support transaction requests (request money from a friend)',
    ],
    nonFunctionalRequirements: [
      'Transfers must be atomic — either both debit and credit succeed, or neither does',
      'Support 10,000 transfers per second at peak',
      'Full audit trail; no transaction can be deleted, only reversed',
    ],
    hints: [
      'Model money movement as double-entry bookkeeping: every Transfer creates two linked LedgerEntry rows (a debit on the sender, a credit on the receiver) that must be written in the same atomic transaction.',
      'To avoid deadlocks on concurrent transfers between the same two wallets, always acquire locks on wallet rows in a consistent order (e.g. sort by walletId) before debiting/crediting.',
      'Idempotency: attach a client-generated idempotency key to each transfer request so retries (e.g. after a network timeout) don\'t double-charge — check for an existing Transfer with that key before creating a new one.',
    ],
  },
  {
    slug: 'restaurant-pos-kitchen-display',
    title: 'Restaurant POS & Kitchen Display System',
    difficulty: 'medium',
    category: 'Hospitality',
    description: 'Design a point-of-sale system for restaurants that routes orders to the kitchen display and tracks preparation status.',
    companies: ['Toast', 'Square', 'Clover'],
    tags: ['OOP', 'Observer Pattern', 'State Machine'],
    order: 23,
    functionalRequirements: [
      'Take an order with multiple items from a table or online',
      'Route order items to the correct kitchen station (grill, salad, dessert)',
      'Update item status: queued, preparing, ready, served',
      'Split a bill across multiple payers',
      'Apply modifiers to items (no onions, extra cheese)',
      'Show real-time order status on a kitchen display screen',
    ],
    nonFunctionalRequirements: [
      'Kitchen display updates should propagate within 1 second',
      'Support 100+ concurrent open orders per restaurant',
    ],
    hints: [
      'Core entities: Order, OrderItem (with modifiers), Station, KitchenDisplay, Bill. Each MenuItem maps to a Station (grill/salad/dessert) so OrderItems auto-route on creation.',
      'Use the Observer pattern: Order is a Subject; each Station\'s KitchenDisplay observes only the OrderItems routed to it, so a grill display never sees dessert items.',
      'Model each OrderItem\'s lifecycle as a State Machine (Queued → Preparing → Ready → Served) — station staff can only transition to the next valid state, preventing "Served before Ready" bugs.',
    ],
  },
  {
    slug: 'ebook-lending-platform',
    title: 'E-Book Lending Platform',
    difficulty: 'medium',
    category: 'Education',
    description: 'Design a digital library lending platform (like a Kindle library) supporting borrowing, returning, and licensing limits.',
    companies: ['Amazon Kindle', 'OverDrive', 'Libby'],
    tags: ['OOP', 'Licensing', 'Queue'],
    order: 24,
    functionalRequirements: [
      'Borrow an available e-book copy for a fixed loan period',
      'Auto-return a book when the loan period expires',
      'Waitlist a user for a book with all copies checked out',
      'Support a limited number of concurrent digital "copies" per title',
      'Sync reading progress across devices',
      'Allow early return of a borrowed book',
    ],
    nonFunctionalRequirements: [
      'Loan expiry must be enforced even if the user is offline',
      'Support millions of titles and concurrent borrows',
    ],
    hints: [
      'Core entities: Title, LicenseCopy (bounded count per Title), Loan (startTime, expiryTime), Waitlist. Each Title has N LicenseCopy slots — borrowing acquires one, returning (or expiry) releases it.',
      'Enforce expiry with a scheduled job scanning Loans where expiryTime <= now, marking them EXPIRED and releasing the LicenseCopy — never trust the client to "give back" the book actively.',
      'Waitlist promotion: when a copy is released, pop the next user from that Title\'s FIFO waitlist queue and grant them a time-boxed window (e.g. 3 days) to claim the loan before offering it to the next person.',
    ],
  },
  {
    slug: 'online-auction-system',
    title: 'Online Auction System',
    difficulty: 'medium',
    category: 'E-commerce',
    description: 'Design an online auction platform like eBay supporting bidding, auto-bid increments, and auction closing.',
    companies: ['eBay', 'Sotheby\'s'],
    tags: ['OOP', 'State Machine', 'Observer Pattern'],
    order: 25,
    functionalRequirements: [
      'List an item for auction with a starting price and end time',
      'Place a bid higher than the current highest bid',
      'Support proxy/auto-bidding up to a max amount',
      'Notify outbid users in real time',
      'Automatically close the auction at end time and declare a winner',
      'Extend auction end time on last-minute bids (anti-sniping)',
    ],
    nonFunctionalRequirements: [
      'Bid placement must be strictly ordered — no lost bids under concurrency',
      'Support thousands of concurrent bids on a hot auction',
    ],
    hints: [
      'Core entities: Auction (state: Scheduled/Active/Closed), Item, Bid, ProxyBid (maxAmount). Only accept a Bid if amount > currentHighestBid, using a compare-and-set on the auction\'s highest-bid field to serialize concurrent bids.',
      'Proxy bidding: when a new manual bid comes in, automatically raise any existing ProxyBid up to its maxAmount minus an increment, so proxy bidders don\'t need to be online — this is essentially an English auction with an automated agent.',
      'Anti-sniping: if a bid arrives within the last N seconds of the auction, extend endTime by N seconds. Use the Observer pattern to push outbid notifications to previously-highest bidders via WebSocket.',
    ],
  },
  {
    slug: 'hospital-appointment-scheduling',
    title: 'Hospital Appointment Scheduling System',
    difficulty: 'medium',
    category: 'Healthcare',
    description: 'Design a system for scheduling patient appointments with doctors, considering availability, specialties, and rescheduling.',
    companies: ['Practo', 'Epic Systems', 'Zocdoc'],
    tags: ['OOP', 'Interval Scheduling'],
    order: 26,
    functionalRequirements: [
      'Search doctors by specialty, location, and availability',
      'Book an appointment slot for a patient with a doctor',
      'Prevent double-booking the same doctor/time slot',
      'Reschedule or cancel an appointment',
      'Send reminders before the appointment',
      'Support recurring appointments (e.g. physiotherapy sessions)',
    ],
    nonFunctionalRequirements: [
      'Slot conflict checks must be strongly consistent',
      'Support thousands of doctors and appointments per day',
    ],
    hints: [
      'Core entities: Doctor, Specialty, AvailabilitySlot, Appointment, Patient. Doctors publish AvailabilitySlots (recurring weekly templates expanded into concrete slots), and an Appointment consumes exactly one slot.',
      'Prevent double-booking with a unique constraint on (doctorId, slotStart) at the database level, plus an application-level check — the DB constraint is the real source of truth under concurrency.',
      'For reminders, use a scheduled job that queries appointments starting in the next N hours and haven\'t been reminded yet, dispatching notifications and marking them as reminded (idempotent).',
    ],
  },
  {
    slug: 'gym-membership-class-booking',
    title: 'Gym Membership & Class Booking System',
    difficulty: 'medium',
    category: 'Fitness',
    description: 'Design a gym management system handling memberships, class schedules, and capacity-limited class bookings.',
    companies: ['ClassPass', 'Mindbody'],
    tags: ['OOP', 'Scheduling'],
    order: 27,
    functionalRequirements: [
      'Manage membership plans (monthly, annual, day-pass)',
      'Schedule recurring fitness classes with instructor and capacity',
      'Book a spot in a class, respecting capacity limits',
      'Waitlist members when a class is full',
      'Check in a member via membership ID/QR code',
      'Track class attendance history per member',
    ],
    nonFunctionalRequirements: [
      'Booking must never exceed the class\'s physical capacity',
      'Support hundreds of classes per week across multiple locations',
    ],
    hints: [
      'Core entities: Member, MembershipPlan, GymClass (capacity, instructor, schedule), Booking, Waitlist. A GymClass\'s occurrence is a specific dated instance expanded from its recurring schedule template.',
      'Capacity enforcement: maintain a bookedCount on each class occurrence and only allow booking via an atomic increment-if-under-capacity operation (DB transaction or optimistic locking) to avoid overbooking races.',
      'Waitlist works the same as the e-book/library pattern: FIFO queue per class occurrence, promoted automatically when a booking is cancelled, with a claim window before moving to the next waitlisted member.',
    ],
  },
  {
    slug: 'online-survey-form-builder',
    title: 'Online Survey / Form Builder',
    difficulty: 'medium',
    category: 'Productivity',
    description: 'Design a form-building platform (like Google Forms) supporting custom questions, conditional logic, and response analytics.',
    companies: ['Google Forms', 'Typeform', 'SurveyMonkey'],
    tags: ['OOP', 'Composite Pattern'],
    order: 28,
    functionalRequirements: [
      'Build a form with multiple question types (text, multiple-choice, rating, date)',
      'Support conditional/branching logic (show Q5 only if Q3 = "Yes")',
      'Collect and store form responses',
      'Validate responses against question constraints (required, min/max)',
      'Generate response analytics (counts, averages, charts)',
      'Share a form via a public link',
    ],
    nonFunctionalRequirements: [
      'Support forms with hundreds of questions',
      'Response submission should be reliable even on flaky connections (idempotent retries)',
    ],
    hints: [
      'Core entities: Form, Question (type + validation rules), ConditionalRule, Response, Answer. Use the Strategy pattern for question types — each QuestionType implements its own validate(answer) and render() behavior.',
      'Model conditional logic as a simple rule evaluated against previously answered questions: ConditionalRule(questionId, condition, targetQuestionId) — evaluate rules top-to-bottom while rendering to decide which question to show next.',
      'For analytics, avoid recomputing from all raw Responses on every view — maintain incrementally-updated aggregates (per-choice counts, running sum/count for numeric questions) updated on each new Response submission.',
    ],
  },
  {
    slug: 'event-ticketing-platform',
    title: 'Event Ticketing Platform',
    difficulty: 'medium',
    category: 'Entertainment',
    description: 'Design a ticketing platform (like Ticketmaster) for concerts and sports events with seat selection and high-demand sale handling.',
    companies: ['Ticketmaster', 'StubHub', 'BookMyShow'],
    tags: ['OOP', 'Concurrency', 'State Machine'],
    order: 29,
    functionalRequirements: [
      'Browse events and view available seating sections',
      'Select and reserve seats temporarily during checkout',
      'Release reservation if checkout isn\'t completed in time',
      'Purchase tickets and generate e-tickets with QR codes',
      'Support a virtual waiting room for high-demand on-sales',
      'Resell/transfer a ticket to another user',
    ],
    nonFunctionalRequirements: [
      'No two users can purchase the same seat (strong consistency)',
      'Support massive concurrent traffic spikes at on-sale time',
    ],
    hints: [
      'Core entities: Event, Venue, Seat, Reservation (time-boxed hold), Ticket. Seat status transitions: AVAILABLE → HELD → SOLD, each transition guarded by an atomic compare-and-set to prevent double-selling.',
      'Temporary holds: when a user selects seats, create a Reservation with a short TTL (e.g. 10 min) via a timed lock (Redis SETEX or a DB expiry column + cleanup job); if checkout doesn\'t complete in time, the hold auto-releases the seat back to AVAILABLE.',
      'For high-demand on-sales, put users into a virtual waiting room (a fair queue, e.g. token-bucket admission or a FIFO queue with a randomized initial position) that gradually admits users into the booking flow to protect the seat-selection service from a thundering herd.',
    ],
  },
  {
    slug: 'podcast-platform',
    title: 'Podcast Platform',
    difficulty: 'medium',
    category: 'Streaming',
    description: 'Design a podcast platform supporting show subscriptions, episode downloads, playback position sync, and recommendations.',
    companies: ['Spotify', 'Apple Podcasts'],
    tags: ['OOP', 'Sync'],
    order: 30,
    functionalRequirements: [
      'Subscribe to a podcast show to get new episode notifications',
      'Stream or download an episode for offline playback',
      'Resume playback from the last position, synced across devices',
      'Adjust playback speed',
      'Auto-download new episodes for subscribed shows',
      'Recommend shows based on listening history',
    ],
    nonFunctionalRequirements: [
      'Playback position sync across devices within a few seconds',
      'Support millions of episodes and concurrent streams',
    ],
    hints: [
      'Core entities: Show, Episode, Subscription, PlaybackState (userId, episodeId, positionSeconds, updatedAt), Download. Store PlaybackState server-side, upserted on a debounced timer (e.g. every 10s) during playback, not on every second.',
      'Cross-device sync: when a device resumes an episode, fetch the latest PlaybackState by updatedAt (last-write-wins) — simple and sufficient since a user typically listens on one device at a time.',
      'New-episode notifications: use a fan-out-on-write model for subscriptions with a reasonable subscriber count (notify all subscribers when an episode publishes) versus fan-out-on-read for shows with huge subscriber counts (compute "any new episodes" lazily when the user opens the app).',
    ],
  },
  {
    slug: 'cloud-file-sync-client',
    title: 'Cloud File Sync Client (Dropbox-like)',
    difficulty: 'medium',
    category: 'Storage',
    description: 'Design the client-side sync engine for a cloud storage service that keeps local and remote folders in sync, handling conflicts.',
    companies: ['Dropbox', 'Google Drive', 'OneDrive'],
    tags: ['OOP', 'Sync', 'Conflict Resolution'],
    order: 31,
    functionalRequirements: [
      'Detect local file changes (create, edit, delete, move)',
      'Upload changed files to the cloud and download remote changes locally',
      'Chunk large files for efficient partial re-upload on edit',
      'Detect and resolve sync conflicts (same file edited on two devices)',
      'Support selective sync (only sync chosen folders)',
      'Show sync status per file (syncing, synced, conflict, error)',
    ],
    nonFunctionalRequirements: [
      'Only re-upload changed chunks, not the whole file, on edits',
      'Sync engine must survive process crashes without losing track of pending changes',
    ],
    hints: [
      'Core entities: FileMetadata (path, hash, version, modifiedTime), Chunk, SyncQueue, ConflictRecord. Split files into fixed-size or content-defined chunks and hash each one — on edit, only chunks whose hash changed need re-upload.',
      'Use a local persistent journal/queue of pending changes (append-only log on disk) so if the client crashes mid-sync, it can resume from the journal instead of re-scanning the entire file tree.',
      'Conflict detection: track a version number (or vector clock) per file. If local and remote versions have both advanced independently since the last common sync point, it\'s a conflict — resolve by keeping both as "file.txt" and "file (conflicted copy).txt" rather than silently overwriting.',
    ],
  },
  {
    slug: 'recipe-meal-planning',
    title: 'Recipe & Meal Planning App',
    difficulty: 'medium',
    category: 'Food-Tech',
    description: 'Design an app for browsing recipes, planning weekly meals, and auto-generating a shopping list.',
    companies: ['Yummly', 'Mealime'],
    tags: ['OOP'],
    order: 32,
    functionalRequirements: [
      'Browse and search recipes by ingredient, cuisine, or dietary tag',
      'Add a recipe to a weekly meal plan calendar',
      'Scale recipe ingredient quantities based on serving size',
      'Auto-generate a consolidated shopping list from a week\'s meal plan',
      'Mark shopping list items as purchased',
      'Save favorite recipes',
    ],
    nonFunctionalRequirements: [
      'Shopping list generation should merge duplicate ingredients across recipes',
      'Search should return results in under 500ms',
    ],
    hints: [
      'Core entities: Recipe (ingredients with quantity+unit), MealPlan (date → Recipe), ShoppingList, Ingredient. Normalize ingredient units (e.g. convert tsp/tbsp/cup to a common base) so quantities can be merged correctly.',
      'Shopping list generation: iterate all recipes in the meal plan, scale each ingredient by the plan\'s chosen serving multiplier, group by normalized ingredient name + unit, and sum quantities into one consolidated line item.',
      'For search, build an inverted index over ingredient names, cuisine tags, and dietary tags so multi-filter queries (e.g. "vegetarian" AND "Italian") are a fast set intersection rather than a full scan.',
    ],
  },
  {
    slug: 'fitness-tracker-app',
    title: 'Fitness Tracker App',
    difficulty: 'medium',
    category: 'Fitness',
    description: 'Design a fitness tracking app that logs workouts, steps, and goals, and computes progress analytics.',
    companies: ['Fitbit', 'Strava', 'Apple Health'],
    tags: ['OOP', 'Analytics'],
    order: 33,
    functionalRequirements: [
      'Log workouts (type, duration, calories, distance)',
      'Track daily step count and active minutes',
      'Set fitness goals (weekly steps, weight target) and track progress',
      'Show historical trends (weekly/monthly charts)',
      'Award achievement badges for milestones',
      'Sync data from wearable devices',
    ],
    nonFunctionalRequirements: [
      'Ingest sensor data streams without data loss',
      'Support millions of daily active users logging data continuously',
    ],
    hints: [
      'Core entities: User, Workout, DailyActivity (steps, activeMinutes, date), Goal, Achievement. Store DailyActivity as one row per user per day, updated incrementally as new step-count events arrive from the device.',
      'For trend charts, pre-aggregate DailyActivity into weekly/monthly rollups on a scheduled job rather than summing raw daily rows on every dashboard load — classic write-time vs read-time aggregation trade-off.',
      'Achievements: model as a rule engine — each Achievement has a trigger condition (e.g. "7-day step streak >= 10k") evaluated against the user\'s recent DailyActivity whenever new data lands; award once and never re-evaluate a completed achievement.',
    ],
  },
  {
    slug: 'multiplayer-tictactoe-matchmaking',
    title: 'Multiplayer Tic-Tac-Toe with Matchmaking',
    difficulty: 'medium',
    category: 'Gaming',
    description: 'Design a real-time multiplayer Tic-Tac-Toe game with matchmaking, live moves, and rematches.',
    companies: ['Zynga', 'Discord'],
    tags: ['OOP', 'State Machine', 'Matchmaking'],
    order: 34,
    functionalRequirements: [
      'Match two waiting players into a new game session',
      'Broadcast each move to both players in real time',
      'Validate moves server-side (correct turn, empty cell)',
      'Detect win, loss, and draw conditions',
      'Support a rematch request between the same two players',
      'Handle a player disconnecting mid-game',
    ],
    nonFunctionalRequirements: [
      'Move broadcast latency under 200ms',
      'Support thousands of concurrent game sessions',
    ],
    hints: [
      'Core entities: MatchmakingQueue, GameSession, Board, Player, Move. Matchmaking is simply a FIFO queue — pop two waiting players and create a GameSession as soon as two are available.',
      'Server is authoritative: every Move request is validated against the current Board and whose turn it is before being applied and broadcast — never trust a client-reported win/loss.',
      'Win detection after each move only needs to check the row/column/diagonal through the just-played cell (not the whole board) — O(1) instead of scanning all 8 winning lines every time.',
    ],
  },
  {
    slug: 'elevator-group-control-system',
    title: 'Elevator Group Control System (Multiple Elevators)',
    difficulty: 'medium',
    category: 'Infrastructure',
    description: 'Design a control system that dispatches the optimal elevator among several to serve a hall call, minimizing wait time.',
    companies: ['Otis', 'Schindler', 'Amazon'],
    tags: ['OOP', 'Scheduling', 'Optimization'],
    order: 35,
    functionalRequirements: [
      'Handle hall calls (up/down) from any floor',
      'Handle in-cabin floor requests from passengers',
      'Dispatch the best elevator among N cars for a new hall call',
      'Support elevator states: idle, moving up, moving down, door open',
      'Batch requests along an elevator\'s current direction (SCAN-like)',
      'Handle an elevator going out of service',
    ],
    nonFunctionalRequirements: [
      'Dispatch decision should compute in well under 100ms',
      'Minimize average passenger wait time across the building',
    ],
    hints: [
      'Core entities: ElevatorController (dispatcher), Elevator (state, currentFloor, direction, requestQueue), HallCall, CabinRequest. Each Elevator maintains its own SCAN-ordered request queue (like a disk-scheduling elevator algorithm), serving requests in the current direction before reversing.',
      'Dispatch heuristic: for a new hall call, score each idle/moving elevator by estimated time-to-arrival (distance, current direction alignment, number of pending stops) and assign the lowest-cost one — this is the crux of the classic "elevator group control" problem.',
      'Model each elevator as its own state machine (Idle ⇄ MovingUp ⇄ MovingDown ⇄ DoorOpen) driven independently, with the ElevatorController only responsible for assigning calls, not micromanaging individual elevator movement.',
    ],
  },
  {
    slug: 'online-polling-voting-platform',
    title: 'Online Polling / Voting Platform',
    difficulty: 'medium',
    category: 'Social Media',
    description: 'Design a platform for creating polls and collecting votes at scale, with real-time result aggregation and fraud prevention.',
    companies: ['Twitter/X', 'Slido', 'Doodle'],
    tags: ['OOP', 'Concurrency', 'Real-time'],
    order: 36,
    functionalRequirements: [
      'Create a poll with multiple options and an optional end time',
      'Cast a single vote per user per poll',
      'Show live-updating vote counts and percentages',
      'Prevent duplicate voting (same user, same poll)',
      'Support anonymous vs. authenticated polls',
      'Close a poll and lock in final results',
    ],
    nonFunctionalRequirements: [
      'Vote counting must be accurate under massive concurrent write load',
      'Result display can be eventually consistent (few-second lag acceptable)',
    ],
    hints: [
      'Core entities: Poll, Option, Vote (userId, pollId, optionId, unique together). Enforce one-vote-per-user with a unique index on (pollId, userId) at the database level — this is the real duplicate-vote guard, not just an application check.',
      'For hot polls with huge write volume, don\'t increment a shared counter row directly (contention bottleneck) — instead write append-only Vote records and maintain per-option counters via a sharded counter or a stream-processing aggregator that batches increments.',
      'Live result display: push aggregated counts to clients via WebSocket on a throttled interval (e.g. every 1-2 seconds) computed from the sharded counters, rather than recomputing from all raw Vote rows on every poll.',
    ],
  },
  {
    slug: 'warehouse-order-fulfillment',
    title: 'Warehouse Order Fulfillment System',
    difficulty: 'medium',
    category: 'Logistics',
    description: 'Design a warehouse management system that picks, packs, and ships customer orders from inventory across multiple bins.',
    companies: ['Amazon', 'FedEx', 'DHL'],
    tags: ['OOP', 'Optimization'],
    order: 37,
    functionalRequirements: [
      'Track inventory quantity per SKU across multiple warehouse bins',
      'Allocate inventory to an order at checkout time',
      'Generate an optimized pick list/path for warehouse staff',
      'Pack items into shipment boxes based on size/weight',
      'Update order status: allocated, picking, packed, shipped',
      'Handle partial fulfillment when stock is insufficient',
    ],
    nonFunctionalRequirements: [
      'Inventory allocation must never oversell available stock',
      'Support thousands of orders processed per hour',
    ],
    hints: [
      'Core entities: SKU, Bin, InventoryRecord (SKU, bin, quantity), Order, Allocation, PickList. Allocation should atomically decrement available quantity (reserve) at checkout time — use optimistic locking or a DB transaction to avoid overselling under concurrent checkouts.',
      'Pick list optimization: given a set of allocated bins for an order, sort the picks by warehouse layout position (e.g. serpentine aisle order) so staff walk a near-optimal path instead of jumping randomly between aisles.',
      'Partial fulfillment: if total available quantity across bins is less than ordered quantity, split the order into a fulfilled sub-shipment and a backorder for the remainder, tracked as separate fulfillment records against the same parent Order.',
    ],
  },
  {
    slug: 'customer-support-ticketing',
    title: 'Customer Support Ticketing System',
    difficulty: 'medium',
    category: 'Productivity',
    description: 'Design a support ticketing system (like Zendesk) handling ticket creation, assignment, SLA tracking, and escalation.',
    companies: ['Zendesk', 'Freshdesk', 'Intercom'],
    tags: ['OOP', 'State Machine', 'SLA'],
    order: 38,
    functionalRequirements: [
      'Create a support ticket from a customer inquiry',
      'Auto-assign or manually assign a ticket to an agent',
      'Track ticket status: open, in-progress, waiting, resolved, closed',
      'Set priority and SLA deadlines per ticket',
      'Escalate a ticket that\'s about to breach its SLA',
      'Support internal notes and customer-visible replies on a ticket',
    ],
    nonFunctionalRequirements: [
      'SLA breach detection must run reliably even under system load',
      'Support tens of thousands of open tickets per organization',
    ],
    hints: [
      'Core entities: Ticket (status, priority, SLA deadline), Agent, Reply (internal vs public), EscalationRule. Model ticket status as a State Machine with allowed transitions (Open → InProgress → Waiting → Resolved → Closed, with Reopen from Closed).',
      'SLA deadlines are computed at ticket creation/priority-change time (createdAt + SLA duration for that priority) and stored directly on the ticket — a scheduled job periodically scans tickets nearing/past deadline rather than computing deadlines on every check.',
      'Auto-assignment: use round-robin or least-loaded-agent routing, factoring in agent skill tags matching the ticket\'s category — a simple weighted queue rather than a full ML system covers most real designs at this scope.',
    ],
  },
  {
    slug: 'loyalty-points-rewards-program',
    title: 'Loyalty Points & Rewards Program',
    difficulty: 'medium',
    category: 'Retail',
    description: 'Design a loyalty program that earns points on purchases, tracks tiers, and lets users redeem rewards.',
    companies: ['Starbucks', 'Sephora', 'Amazon'],
    tags: ['OOP', 'Rules Engine'],
    order: 39,
    functionalRequirements: [
      'Earn points on qualifying purchases based on configurable rules',
      'Track a member\'s point balance and lifetime spend',
      'Assign membership tiers (Silver/Gold/Platinum) based on activity',
      'Redeem points for rewards (discounts, free items)',
      'Expire points after a period of inactivity',
      'Show point-earning history and upcoming tier progress',
    ],
    nonFunctionalRequirements: [
      'Point balance updates must be atomic and auditable',
      'Support millions of members with concurrent earn/redeem operations',
    ],
    hints: [
      'Core entities: Member, PointsLedger (append-only entries: earn/redeem/expire), EarningRule, Tier, Reward. Never store a single mutable "balance" field as the source of truth — derive it from summing the PointsLedger, cached for fast reads.',
      'Use a Rules Engine / Strategy pattern for earning: each EarningRule (e.g. "1 point per $1", "2x points on weekends") evaluates a purchase and returns points to award — new promotions become new rules, not new code paths.',
      'Tier evaluation runs periodically (e.g. nightly) over each member\'s trailing 12-month spend/points, comparing against tier thresholds — avoid recalculating tier on every single transaction for performance.',
    ],
  },
  {
    slug: 'social-event-planning-app',
    title: 'Social Event Planning App (Meetup-like)',
    difficulty: 'medium',
    category: 'Social Media',
    description: 'Design an app for creating and discovering local social events, with RSVPs, groups, and recommendations.',
    companies: ['Meetup', 'Eventbrite', 'Facebook Events'],
    tags: ['OOP', 'Geospatial'],
    order: 40,
    functionalRequirements: [
      'Create a group around a shared interest',
      'Create an event under a group with date, location, and capacity',
      'RSVP to an event (going, maybe, not going)',
      'Discover nearby events based on user location and interests',
      'Waitlist attendees once an event reaches capacity',
      'Send event reminders to RSVP\'d attendees',
    ],
    nonFunctionalRequirements: [
      'Nearby-event search should respond in under 300ms',
      'Support millions of groups and events globally',
    ],
    hints: [
      'Core entities: Group, Event (location, capacity, startTime), RSVP, Member, Interest. Index event locations geospatially (geohash or a geo-index like PostGIS/Elasticsearch) for fast "events near me" queries.',
      'Capacity + waitlist follows the same reserve-atomically-then-waitlist-on-full pattern used elsewhere (gym classes, e-book loans): an atomic increment-if-under-capacity on RSVP, FIFO waitlist otherwise.',
      'Recommendations: score events by a simple weighted combination of interest-tag overlap with the user\'s followed Groups/Interests and physical distance, re-ranked and cached per user on a schedule rather than computed live on every page load.',
    ],
  },

  // ─── HARD ─────────────────────────────────────────────────────────────────
  {
    slug: 'collaborative-text-editor',
    title: 'Google Docs — Collaborative Real-Time Text Editor',
    difficulty: 'hard',
    category: 'Productivity',
    description: 'Design a collaborative document editor where multiple users can edit the same document simultaneously with real-time sync and no lost updates.',
    companies: ['Google', 'Microsoft', 'Notion'],
    tags: ['CRDT', 'OT', 'Distributed Systems'],
    order: 20,
    functionalRequirements: [
      'Multiple users edit the same document concurrently in real time',
      'Changes from one user appear on all other connected clients within a second',
      'Support offline edits that merge correctly once reconnected',
      'Maintain full version history with the ability to restore an earlier version',
      'Show live cursor positions of other collaborators',
      'Support comments anchored to specific text ranges',
    ],
    nonFunctionalRequirements: [
      'No lost updates even with simultaneous conflicting edits',
      'Support hundreds of concurrent editors on a single popular document',
      'Convergence: all clients must eventually see the identical document state',
    ],
    hints: [
      'The core challenge is concurrent edit merging. Two approaches: Operational Transformation (OT) — transform incoming remote operations against locally-applied concurrent ones before applying — or CRDTs (Conflict-free Replicated Data Types) where each character/element has a globally unique, order-preserving ID so merges are commutative and always converge without a central transform step.',
      'For a from-scratch design, a sequence CRDT (like RGA or a simplified Logoot) is easier to reason about than OT: each inserted character gets a unique position identifier derived from its neighbors, so concurrent inserts at "the same spot" from different users naturally interleave into a consistent order on every replica.',
      'Architecture: clients send local operations to a central server (or peer-to-peer) which broadcasts them to all other connected clients; the server also persists the operation log for version history/replay, and periodically snapshots the document to avoid replaying the entire history on load.',
    ],
  },
  {
    slug: 'distributed-rate-limiter',
    title: 'Distributed Rate Limiter (Multi-Node)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a rate limiter that enforces a consistent request limit for a client across many API server instances.',
    companies: ['Amazon', 'Cloudflare', 'Stripe'],
    tags: ['Distributed Systems', 'Redis', 'Algorithms'],
    order: 21,
    functionalRequirements: [
      'Enforce a limit like "100 requests per minute per API key" globally, not per-server',
      'Support multiple algorithms: fixed window, sliding window, token bucket',
      'Allow per-client custom limits/tiers',
      'Return remaining quota and reset time to the client',
      'Gracefully degrade if the central rate-limit store becomes unavailable',
    ],
    nonFunctionalRequirements: [
      'Rate-limit check latency should add well under 5ms to each request',
      'Must work correctly across hundreds of stateless API server instances',
      'Should tolerate the rate-limit store being briefly unavailable without blocking all traffic',
    ],
    hints: [
      'Because request limits must hold across many stateless servers, per-process in-memory counters don\'t work — use a shared fast store (Redis) as the single source of truth for counters, since local server memory can\'t coordinate globally.',
      'Sliding window log or sliding window counter in Redis: use INCR with an expiring key per (clientId, windowStart) for fixed windows, or a sorted set of request timestamps trimmed to the window for a precise sliding log — token bucket can be implemented with a Lua script in Redis for atomicity (check-and-decrement in one round trip).',
      'For resilience, if Redis is unreachable, fail open with a conservative local fallback limiter (e.g. each node allows a small fraction of the global limit) rather than rejecting all traffic — document this trade-off explicitly as availability over strict correctness during outages.',
    ],
  },
  {
    slug: 'distributed-job-scheduler',
    title: 'Distributed Job Scheduler (Airflow-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a distributed system for scheduling and executing DAGs of interdependent jobs across a cluster of workers.',
    companies: ['Airbnb (Airflow)', 'Google', 'Uber'],
    tags: ['Distributed Systems', 'DAG', 'Scheduling'],
    order: 22,
    functionalRequirements: [
      'Define a job as a DAG of tasks with dependencies',
      'Schedule DAG runs on a cron-like or event-triggered basis',
      'Execute tasks on any available worker in a cluster, respecting dependency order',
      'Retry failed tasks with backoff, and support manual re-runs',
      'Track task/DAG run status and provide a monitoring view',
      'Prevent the same task instance from running twice concurrently',
    ],
    nonFunctionalRequirements: [
      'Must survive scheduler node failure without losing or duplicating DAG runs',
      'Support thousands of DAGs with tens of thousands of tasks scheduled per day',
      'Task dispatch latency under a few seconds once dependencies are satisfied',
    ],
    hints: [
      'Core entities: DAG (tasks + dependency edges), DAGRun (one execution instance), TaskInstance (status per task per run), Worker. Persist DAGRun/TaskInstance state in a database — the scheduler process itself must be stateless/recoverable, deriving all decisions by querying persisted state, not in-memory data.',
      'Use a leader-election scheme (e.g. via Zookeeper/etcd) so exactly one scheduler instance is actively assigning tasks at a time, with standby instances ready to take over on failure — this avoids duplicate scheduling from multiple active schedulers.',
      'Task dispatch: workers pull ready tasks (all dependencies SUCCESS) from a shared queue rather than the scheduler pushing directly, using a distributed lock or a claim-with-lease pattern (worker claims a task with a lease; if it dies mid-execution, the lease expires and another worker can reclaim it) to guarantee exactly-once execution semantics.',
    ],
  },
  {
    slug: 'news-feed-ranking-system',
    title: 'News Feed Ranking System',
    difficulty: 'hard',
    category: 'Social Media',
    description: 'Design the backend for a social network news feed that aggregates and ranks posts from friends/follows at massive scale.',
    companies: ['Facebook', 'Instagram', 'LinkedIn'],
    tags: ['Distributed Systems', 'Fan-out', 'Ranking'],
    order: 21,
    functionalRequirements: [
      'Aggregate posts from all accounts a user follows into one feed',
      'Rank feed items by relevance (not strictly chronological)',
      'Support near-real-time insertion of new posts into feeds',
      'Handle both regular users and celebrities with millions of followers',
      'Paginate the feed efficiently as the user scrolls',
      'Exclude posts the user has already seen or hidden',
    ],
    nonFunctionalRequirements: [
      'Feed load latency under 200ms for a typical user',
      'Support hundreds of millions of users, billions of posts',
      'System must handle extreme fan-out for celebrity accounts without falling over',
    ],
    hints: [
      'Use a hybrid fan-out strategy: fan-out-on-write (push a new post into each follower\'s precomputed feed, stored e.g. in Redis lists) for regular users with a normal follower count, but fan-out-on-read (merge celebrity posts into the feed at read time instead of writing to millions of follower feeds) for accounts with huge followings — this avoids the "celebrity write storm" problem.',
      'Ranking: compute a relevance score per candidate post (recency decay, affinity between user and poster, engagement signals) — do a first-pass candidate retrieval (recent posts from followed accounts, capped at a few hundred) then rank that smaller candidate set rather than scoring every post in the system.',
      'Feed pagination: since the feed is dynamically ranked and merges multiple sources (precomputed pushed feed + live celebrity posts), use a cursor based on a composite (score, postId, timestamp) rather than simple offset pagination, so new posts arriving don\'t shift already-seen pages.',
    ],
  },
  {
    slug: 'distributed-notification-fanout',
    title: 'Distributed Notification Fanout System',
    difficulty: 'hard',
    category: 'Messaging',
    description: 'Design a system that reliably delivers notifications (push, SMS, email) to millions of users with dedup, retries, and prioritization.',
    companies: ['Amazon (SNS)', 'Meta', 'Twilio'],
    tags: ['Distributed Systems', 'Queueing', 'Fan-out'],
    order: 22,
    functionalRequirements: [
      'Accept a notification request targeting a user, group, or topic subscribers',
      'Fan out a topic notification to all its subscribers',
      'Deliver via multiple channels (push, SMS, email) based on user preference',
      'Deduplicate identical notifications sent in a short window',
      'Retry failed deliveries with backoff and respect provider rate limits',
      'Support notification priority (critical vs. marketing)',
    ],
    nonFunctionalRequirements: [
      'Deliver critical notifications within seconds even under heavy load',
      'Support fanning out to tens of millions of subscribers for a single topic event',
      'At-least-once delivery guarantee with idempotent handling on the client',
    ],
    hints: [
      'Core pipeline: Ingestion API → durable Message Queue (e.g. Kafka) → Fanout workers that expand a topic notification into per-user delivery tasks → per-channel Delivery workers (Push/SMS/Email) that call the respective provider APIs. Decoupling each stage with a queue lets you scale and retry independently.',
      'Deduplication: assign each notification (or the (userId, templateId, dedupeWindow) tuple) an idempotency/dedupe key, checked against a short-TTL cache (Redis) before enqueueing delivery — this prevents duplicate sends from retries or overlapping triggers.',
      'Priority and rate-limit handling: use separate queues per priority tier (critical vs. marketing) so critical notifications aren\'t stuck behind a backlog of bulk marketing sends, and apply a token-bucket limiter per downstream provider (APNs/FCM/Twilio) so a burst doesn\'t get the whole account throttled or banned by the provider.',
    ],
  },
  {
    slug: 'content-delivery-network',
    title: 'Content Delivery Network (CDN)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a CDN that caches and serves static content from edge locations close to users, with origin fetch and cache invalidation.',
    companies: ['Cloudflare', 'Akamai', 'Amazon CloudFront'],
    tags: ['Distributed Systems', 'Caching', 'Networking'],
    order: 23,
    functionalRequirements: [
      'Route a user request to the nearest/best edge server',
      'Serve cached content from the edge if available (cache hit)',
      'Fetch from origin on a cache miss and populate the edge cache',
      'Support cache invalidation/purge for updated content',
      'Support configurable TTLs per content type',
      'Provide cache-hit-ratio and traffic analytics',
    ],
    nonFunctionalRequirements: [
      'Cache hit latency under 20ms from edge',
      'Support petabytes of cacheable content across thousands of edge nodes globally',
      'High availability — an edge node failure shouldn\'t cause origin overload',
    ],
    hints: [
      'Routing to the nearest edge is typically done via DNS-based geo-routing (Anycast IP or GeoDNS resolving to the closest edge PoP) so the client\'s first request already lands near them without any application-level logic.',
      'Each edge node runs its own local cache (keyed by URL + relevant headers, e.g. Vary: Accept-Encoding) with an LRU/LFU eviction policy; on a miss, the edge does a "cache-fill" request to a regional/origin tier rather than every edge node hitting origin directly — a mid-tier cache layer protects the origin from thundering-herd traffic.',
      'Invalidation at scale: rather than pushing a purge to every one of thousands of edges synchronously (slow, unreliable), use a versioned cache key (embed a content version/hash in the cache key) so publishing new content is just a new key — old cached versions simply expire via TTL and are never served again, avoiding a distributed invalidation problem entirely for immutable-content workloads. For mutable paths, maintain a purge queue consumed asynchronously by edges.',
    ],
  },
  {
    slug: 'distributed-lock-manager',
    title: 'Distributed Lock Manager (Zookeeper-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a distributed coordination service that provides mutual exclusion locks and leader election across a cluster of nodes.',
    companies: ['Apache ZooKeeper', 'etcd', 'Google Chubby'],
    tags: ['Distributed Systems', 'Consensus', 'Coordination'],
    order: 24,
    functionalRequirements: [
      'Acquire and release a named distributed lock',
      'Support blocking acquire (wait until available) and try-acquire (fail fast)',
      'Automatically release a lock if the holder crashes (no permanent deadlock)',
      'Support leader election among a group of competing nodes',
      'Notify waiters when a lock becomes available or leadership changes',
      'Ensure at most one holder of a given lock at any time cluster-wide',
    ],
    nonFunctionalRequirements: [
      'The lock service itself must be fault-tolerant (survive minority node failures)',
      'Lock state must be strongly consistent — no split-brain with two simultaneous holders',
      'Failover/re-election should complete within a few seconds of a leader failure',
    ],
    hints: [
      'The lock service\'s own data (who holds which lock) must be replicated via a consensus protocol like Raft or Paxos across an odd number of nodes (e.g. 3 or 5), so it keeps functioning correctly as long as a majority quorum is alive — this is what makes the coordinator itself fault-tolerant and split-brain-proof.',
      'A classic implementation pattern (as in ZooKeeper): create an ephemeral, sequentially-numbered node under a lock path when a client wants the lock; the client holding the lowest-numbered node holds the lock, and each other waiter watches the node just before its own — when that node is deleted (released or the holder\'s session expires), the next waiter is notified.',
      'Crash recovery: bind the lock to the client\'s session (a heartbeat-based liveness lease) — if the holder\'s session/heartbeat times out (crash, network partition), the coordinator automatically deletes its ephemeral lock node, releasing the lock to the next waiter without requiring any manual intervention.',
    ],
  },
  {
    slug: 'ad-click-tracking-billing',
    title: 'Ad Click Tracking & Billing System',
    difficulty: 'hard',
    category: 'Ad-Tech',
    description: 'Design a system that tracks ad impressions/clicks at massive scale and computes accurate billing for advertisers.',
    companies: ['Google Ads', 'Meta Ads', 'Amazon Advertising'],
    tags: ['Distributed Systems', 'Stream Processing', 'Fraud Detection'],
    order: 25,
    functionalRequirements: [
      'Record ad impressions and clicks with low latency',
      'Attribute a click to the correct ad, campaign, and advertiser',
      'Aggregate click/impression counts per campaign in near real time',
      'Compute advertiser billing based on cost-per-click or cost-per-impression',
      'Detect and filter fraudulent/bot clicks before billing',
      'Provide advertisers a near-real-time spend dashboard',
    ],
    nonFunctionalRequirements: [
      'Must handle extremely high write throughput (hundreds of thousands of events/sec)',
      'Billing must be exactly-once — no double-charging or missed charges',
      'Fraud filtering shouldn\'t meaningfully delay legitimate billing',
    ],
    hints: [
      'Ingest raw click/impression events into a durable, high-throughput log (Kafka) first, decoupling ingestion from processing — this absorbs traffic spikes and lets billing/fraud-detection consumers process at their own pace without dropping events.',
      'Use stream processing (e.g. a windowed aggregation job) to compute near-real-time counts per campaign for the dashboard, while a separate, more rigorous batch job re-processes the full event log later (e.g. hourly) to produce the authoritative, fraud-filtered billing numbers — this "speed layer + batch layer" (Lambda architecture) balances real-time visibility with billing correctness.',
      'Exactly-once billing: assign each click event a unique ID at generation time and dedupe on it during aggregation (e.g. via a distributed idempotency table or Kafka\'s exactly-once semantics) — combined with fraud heuristics (click velocity per IP/device, known bot signatures, impossible geo-velocity) applied as a filter stage before an event counts toward billable spend.',
    ],
  },
  {
    slug: 'live-video-streaming-platform',
    title: 'Live Video Streaming Platform (Twitch-like)',
    difficulty: 'hard',
    category: 'Streaming',
    description: 'Design a platform for low-latency live video broadcasting from a streamer to potentially millions of concurrent viewers.',
    companies: ['Twitch', 'YouTube Live', 'Meta'],
    tags: ['Distributed Systems', 'Video Streaming', 'CDN'],
    order: 24,
    functionalRequirements: [
      'Ingest a live video stream from a broadcaster',
      'Transcode the stream into multiple quality/bitrate renditions',
      'Distribute the live stream to potentially millions of concurrent viewers',
      'Support adaptive bitrate streaming based on viewer bandwidth',
      'Provide live chat alongside the stream',
      'Support stream recording/VOD for later playback',
    ],
    nonFunctionalRequirements: [
      'End-to-end latency (broadcaster to viewer) as low as a few seconds',
      'Support a single stream scaling to millions of concurrent viewers',
      'Graceful quality degradation under network congestion, not buffering/failure',
    ],
    hints: [
      'Pipeline: Broadcaster encodes and pushes via RTMP/WebRTC to an Ingest server → Transcoding service produces multiple bitrate renditions (e.g. via HLS/DASH segments) → segments are pushed to a CDN/edge network → viewers pull segments from the nearest edge, not from the origin ingest server, which is what allows scaling to millions of viewers.',
      'Adaptive bitrate: the player periodically measures download throughput and switches between available renditions (manifest lists multiple quality variants) — this is a client-side decision, the server just needs to have produced and published all the bitrate variants as short segments (a few seconds each).',
      'Latency vs. scale trade-off: shorter segment durations reduce latency but increase overhead (more requests, harder to cache efficiently) — protocols like Low-Latency HLS/DASH or WebRTC-based fan-out trees are used specifically to push latency down from the traditional ~30s of HLS to a few seconds while still using a CDN for the actual fan-out to viewers.',
    ],
  },
  {
    slug: 'distributed-task-queue',
    title: 'Distributed Task Queue (Celery/Sidekiq-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a distributed background job processing system with reliable delivery, retries, and worker scaling.',
    companies: ['Amazon (SQS)', 'Shopify (Sidekiq)', 'Instagram (Celery)'],
    tags: ['Distributed Systems', 'Queueing', 'Reliability'],
    order: 25,
    functionalRequirements: [
      'Enqueue a task with a payload for asynchronous processing',
      'Distribute tasks across a pool of workers for parallel execution',
      'Retry a failed task with exponential backoff up to a max attempt count',
      'Support delayed/scheduled task execution',
      'Support task priorities and multiple named queues',
      'Move a task to a dead-letter queue after exhausting retries',
    ],
    nonFunctionalRequirements: [
      'At-least-once delivery — a task must never be silently lost',
      'Support horizontal scaling of workers to millions of tasks/day',
      'A crashed worker mid-task must not lose that task permanently',
    ],
    hints: [
      'Use a visibility-timeout pattern (as in SQS): when a worker pulls a task, it becomes invisible to other workers for a configured duration rather than being deleted immediately; the worker explicitly deletes it on success. If the worker crashes before deleting it, the visibility timeout expires and another worker picks it up — this is what gives at-least-once delivery without a task ever being permanently lost.',
      'Delayed/scheduled tasks: store them in a separate delayed-set (e.g. a Redis sorted set scored by executeAt) and a lightweight mover process periodically shifts due tasks into the live queue — avoids workers busy-polling for tasks that aren\'t ready yet.',
      'Retries with backoff: track an attempt counter on the task; on failure, re-enqueue with a computed delay (base * 2^attempt, capped) using the same delayed-set mechanism; once attempts exceed the max, route the task to a dead-letter queue for manual inspection instead of retrying forever.',
    ],
  },
  {
    slug: 'distributed-unique-id-generator',
    title: 'Distributed Unique ID Generator (Snowflake-like)',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a service that generates globally unique, roughly time-sortable IDs across many machines without coordination.',
    companies: ['Twitter (Snowflake)', 'Instagram', 'Discord'],
    tags: ['Distributed Systems', 'Algorithms'],
    order: 26,
    functionalRequirements: [
      'Generate a unique ID with no central coordination required per request',
      'IDs should be roughly sortable by creation time',
      'Support many ID-generating nodes running independently',
      'Guarantee no collisions even under massive concurrent generation',
      'IDs should fit in a compact fixed-size integer (e.g. 64 bits)',
    ],
    nonFunctionalRequirements: [
      'Generate IDs at extremely high throughput per node (tens of thousands/sec) with no network round-trip',
      'Must remain correct even if a node\'s clock drifts or resets slightly',
      'No single point of failure — any node can generate IDs independently',
    ],
    hints: [
      'The classic Snowflake layout packs a 64-bit integer as: 1 unused sign bit + 41 bits timestamp (ms since a custom epoch) + 10 bits machine/worker ID + 12 bits per-millisecond sequence number. Because each node has a unique machine ID and its own local sequence counter, no coordination between nodes is needed at generation time.',
      'Within a single millisecond, a node increments its 12-bit sequence counter (up to 4096 IDs/ms/node); if the counter overflows before the millisecond ticks over, the generator busy-waits for the next millisecond — this bounds max throughput per node while guaranteeing local uniqueness.',
      'Clock issues: if a node detects its system clock has moved backward (NTP correction), it must refuse to generate IDs until the clock catches up past the last recorded timestamp — otherwise it could reuse a (timestamp, sequence) pair already issued, breaking global uniqueness. Machine IDs themselves are typically assigned via a coordination service (e.g. Zookeeper) once at startup, not per-request.',
    ],
  },
  {
    slug: 'search-engine-indexing-system',
    title: 'Search Engine Indexing System',
    difficulty: 'hard',
    category: 'Developer Tools',
    description: 'Design the backend indexing pipeline that powers full-text search over a massive, constantly growing document corpus.',
    companies: ['Google', 'Elasticsearch', 'Bing'],
    tags: ['Distributed Systems', 'Inverted Index', 'Search'],
    order: 27,
    functionalRequirements: [
      'Ingest and tokenize documents from a large, growing corpus',
      'Build an inverted index mapping terms to the documents containing them',
      'Support full-text search queries returning ranked results',
      'Support incremental index updates as new documents arrive (near real-time)',
      'Support phrase and boolean (AND/OR/NOT) queries',
      'Rank results by relevance (e.g. TF-IDF/BM25) not just presence',
    ],
    nonFunctionalRequirements: [
      'Search queries should return in well under 200ms',
      'Support indexing billions of documents',
      'Indexing throughput must keep pace with a high document ingestion rate',
    ],
    hints: [
      'Core structure: an Inverted Index — a map from each term to a postings list of (documentId, term frequency, positions) for every document containing that term. Query time then becomes intersecting/unioning postings lists for the query terms rather than scanning documents.',
      'Indexing pipeline: Document ingestion → Tokenization/normalization (lowercasing, stemming, stop-word removal) → Postings list updates. Shard the index by document ID or term range across many index-server nodes so both indexing and query load are distributed, then merge partial results from each shard for a query (scatter-gather).',
      'Relevance ranking: compute a score like BM25/TF-IDF combining term frequency in the document, inverse document frequency across the corpus, and document length normalization — the query engine retrieves candidate documents via the inverted index (cheap) then ranks only that candidate set (expensive), never scoring the entire corpus per query.',
    ],
  },
  {
    slug: 'distributed-session-store',
    title: 'Distributed Session Store',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a globally distributed session store that keeps a logged-in user\'s session valid and consistent across regions and servers.',
    companies: ['Amazon', 'Cloudflare', 'Netflix'],
    tags: ['Distributed Systems', 'Caching', 'Consistency'],
    order: 28,
    functionalRequirements: [
      'Create and validate a user session token on login',
      'Look up session data (user identity, permissions) on every authenticated request',
      'Invalidate a session on logout or password change, everywhere immediately',
      'Support sessions surviving a single data center outage',
      'Support session data replication across geographic regions for low-latency reads',
      'Expire sessions automatically after inactivity',
    ],
    nonFunctionalRequirements: [
      'Session lookup latency should add only a few milliseconds to each request',
      'Session invalidation (e.g. security logout) must propagate globally within seconds',
      'Must tolerate a full region failure without logging out unaffected users',
    ],
    hints: [
      'Use a fast distributed key-value store (e.g. a Redis cluster or DynamoDB global tables) as the session backing store, replicated across regions, so any edge server can validate a session with a local/nearby read rather than round-tripping to a single home region for every request.',
      'For low read latency with global distribution, use a "write to home region, replicate asynchronously, read from nearest replica" model for normal reads, but for security-sensitive events (logout, password change) perform a synchronous invalidation broadcast (e.g. publish an invalidation event to all regions via a pub/sub system) rather than waiting for the normal async replication lag.',
      'To survive a region outage without logging users out, don\'t pin a session strictly to one region as the sole source of truth — replicate session writes to at least one other region synchronously (or use a quorum-based store) so a region failure fails over reads to a replica that\'s already current.',
    ],
  },
  {
    slug: 'realtime-collaborative-code-editor',
    title: 'Real-Time Collaborative Code Editor',
    difficulty: 'hard',
    category: 'Developer Tools',
    description: 'Design a browser-based collaborative code editor (like this app\'s own canvas, but for code) supporting multi-cursor editing and live execution.',
    companies: ['Replit', 'CodeSandbox', 'VS Code Live Share'],
    tags: ['Distributed Systems', 'CRDT', 'Sandboxing'],
    order: 29,
    functionalRequirements: [
      'Multiple users edit the same code file concurrently with live sync',
      'Show each collaborator\'s live cursor and selection',
      'Support running/executing the code and streaming output back to all viewers',
      'Support multiple files/folders in a shared workspace',
      'Persist the workspace so it can be reopened later',
      'Support permission levels (owner, editor, viewer)',
    ],
    nonFunctionalRequirements: [
      'Keystroke-to-remote-view latency under 100ms for a good typing experience',
      'Code execution must be sandboxed and resource-limited per session',
      'Support dozens of concurrent collaborators per workspace without conflicts',
    ],
    hints: [
      'Text sync uses the same core approach as a collaborative doc editor — a sequence CRDT or OT — but scoped per-file within a shared Workspace; cursor/selection state is much simpler and can be broadcast as ephemeral presence data (not part of the durable document state) via WebSocket without needing conflict resolution.',
      'Code execution must run in an isolated, resource-capped sandbox (container or microVM) per session — never execute arbitrary user code in the same process as your collaboration server — with strict CPU/memory/time limits and no network access by default to prevent abuse.',
      'Output streaming: the sandbox\'s stdout/stderr is streamed back over the same WebSocket channel as an ordered event log, tagged with the execution run ID, so multiple viewers watching the same run see identical, ordered output — treat it as just another real-time stream alongside the document\'s edit operations.',
    ],
  },
  {
    slug: 'fraud-detection-system',
    title: 'Fraud Detection System',
    difficulty: 'hard',
    category: 'Fintech',
    description: 'Design a real-time system that scores financial transactions for fraud risk and blocks/flags suspicious activity before it completes.',
    companies: ['Stripe', 'PayPal', 'Visa'],
    tags: ['Distributed Systems', 'Stream Processing', 'Rules Engine'],
    order: 26,
    functionalRequirements: [
      'Score an incoming transaction for fraud risk in real time, before it\'s approved',
      'Combine rule-based checks (velocity, geo-mismatch, blacklists) with a risk model score',
      'Support configurable rules that can be updated without a code deploy',
      'Flag high-risk transactions for manual review instead of auto-blocking',
      'Maintain a feedback loop from confirmed fraud/false-positive outcomes',
      'Provide an audit trail of why a transaction was scored the way it was',
    ],
    nonFunctionalRequirements: [
      'Fraud scoring must complete within the payment\'s synchronous approval window (tens of milliseconds)',
      'Must handle tens of thousands of transactions per second at peak',
      'False-positive rate must stay low enough to not meaningfully harm legitimate users',
    ],
    hints: [
      'Split into a fast synchronous path and a slower asynchronous path: the synchronous path (within the payment approval window) runs only cheap, precomputed-feature rule checks (e.g. velocity counters from a fast in-memory store, blacklist lookups) and a lightweight model inference; the full deep analysis and case review happen asynchronously afterward without blocking the transaction.',
      'Maintain real-time aggregated features (e.g. "transactions from this card in the last 10 minutes", "distinct countries in the last hour") via a stream-processing layer that continuously updates counters per entity (card, device, IP) — these precomputed features are what make sub-50ms scoring possible, since computing them from raw history on every transaction would be far too slow.',
      'Use a layered decision system: hard rules (blacklists, impossible geo-velocity) that auto-block; a risk score from a model combining dozens of features that routes medium-risk transactions to manual review and lets low-risk ones straight through; and a feedback loop where confirmed fraud/false-positive labels from manual review get fed back to periodically retrain the model.',
    ],
  },
  {
    slug: 'distributed-metrics-monitoring',
    title: 'Distributed Metrics & Monitoring System',
    difficulty: 'hard',
    category: 'Infrastructure',
    description: 'Design a monitoring system (like Prometheus) that collects, stores, and alerts on time-series metrics from thousands of services.',
    companies: ['Prometheus', 'Datadog', 'Grafana'],
    tags: ['Distributed Systems', 'Time-Series', 'Alerting'],
    order: 27,
    functionalRequirements: [
      'Collect numeric metrics (counters, gauges, histograms) from thousands of services',
      'Store metrics as time series, queryable by service/metric name and time range',
      'Support aggregation queries (sum, avg, percentile) over time windows',
      'Define alert rules that trigger when a metric crosses a threshold',
      'Visualize metrics on dashboards with live-updating graphs',
      'Retain high-resolution recent data and downsampled older data',
    ],
    nonFunctionalRequirements: [
      'Ingest metrics from tens of thousands of hosts at high frequency (every few seconds) without data loss',
      'Query latency for dashboard graphs under a second for common time ranges',
      'Storage must scale efficiently — raw high-resolution data for years would be prohibitively expensive',
    ],
    hints: [
      'Use either a pull model (a central server periodically scrapes a metrics endpoint on each monitored service, like Prometheus) or a push model (agents push metrics to a collector) — pull simplifies service discovery and avoids overwhelming the collector during a metrics spike, since the collector controls its own scrape rate.',
      'Store data in a purpose-built time-series database with columnar, delta/delta-of-delta compression for timestamps and values (metrics are highly compressible since consecutive values change little) — a generic row-oriented database would be far too expensive at this ingestion volume.',
      'Downsampling: run background jobs that roll up raw high-resolution data (e.g. 15s intervals) into coarser aggregates (5min, 1hr) after it ages past a retention threshold, then delete the raw data — dashboards querying old, wide time ranges automatically hit the downsampled tier, keeping both storage cost and query latency bounded.',
    ],
  },
  {
    slug: 'multiplayer-game-matchmaking',
    title: 'Multiplayer Game Matchmaking System',
    difficulty: 'hard',
    category: 'Gaming',
    description: 'Design a matchmaking service that pairs players of similar skill into balanced game sessions at scale, with low wait times.',
    companies: ['Riot Games', 'Activision', 'Epic Games'],
    tags: ['Distributed Systems', 'Matchmaking', 'Optimization'],
    order: 28,
    functionalRequirements: [
      'Queue a player for a match, optionally as part of a pre-formed party',
      'Match players into balanced teams based on skill rating (e.g. Elo/MMR)',
      'Support different game modes with different team sizes',
      'Widen matchmaking criteria gradually if a match isn\'t found quickly',
      'Assign a matched group to an available game server',
      'Update player skill ratings after a match concludes',
    ],
    nonFunctionalRequirements: [
      'Median matchmaking wait time should stay low (seconds, not minutes) even at moderate population',
      'Support millions of concurrent queued players globally across regions',
      'Match balance (skill gap between teams) should stay within a reasonable bound',
    ],
    hints: [
      'Core entities: MatchmakingTicket (player/party, skill rating, queue time, region, game mode), MatchmakingPool (per region/mode), GameServer. Use a skill rating system (Elo or a Bayesian system like TrueSkill) as the primary matching key, bucketing tickets by skill range for efficient candidate search instead of comparing every waiting player pairwise.',
      'Gradually widen the acceptable skill range (and region) the longer a ticket waits in the pool — this trades off match quality for wait time, which is the fundamental matchmaking trade-off; log both metrics so the widening curve can be tuned.',
      'Party handling: a pre-formed party must be matched as a unit (never split across teams), and its effective skill for matching purposes is typically an average or weighted combination of its members\' individual ratings — treat a party as a single "virtual player" with that combined rating when searching the pool.',
    ],
  },
]

async function main() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI env var not set')
  await mongoose.connect(uri)

  for (const p of PROBLEMS) {
    await Problem.findOneAndUpdate({ slug: p.slug }, { $set: p }, { upsert: true, new: true, setDefaultsOnInsert: true })
    console.log(`  ✓ ${p.difficulty.padEnd(6)} ${p.title}`)
  }

  const total = await Problem.countDocuments({ isActive: true })
  console.log(`\nTotal active problems: ${total}`)
  await mongoose.disconnect()
}

main().catch(err => { console.error(err); process.exit(1) })
